import { Item, registerItem } from "@shared/modules/items";
import { makeItemKeys } from "@shared/modules/items/lib/make-item-keys";
import LEFTHAND_ITEMS from "./lefthand.json";

export const LeftHand = makeItemKeys<LeftHandItemKey>()({
  MaleDeepSeaWatch: "SP_M_LEFT_WRIST_0_0",
  MaleGoldWatch: "SP_M_LEFT_WRIST_0_1",
  MaleSilverWatch: "SP_M_LEFT_WRIST_0_2",
  MaleBlackWatch: "SP_M_LEFT_WRIST_0_3",
  MaleGoldFacedSilverWatch: "SP_M_LEFT_WRIST_0_4",
  MaleWhiteLedBlackStrap: "SP_M_LEFT_WRIST_1_0",
  MaleRedLedWhiteStrap: "SP_M_LEFT_WRIST_1_1",
  MaleRedLedBrownStrap: "SP_M_LEFT_WRIST_1_2",
  MaleWhiteLedTanStrap: "SP_M_LEFT_WRIST_1_3",
  MaleYellowLed: "SP_M_LEFT_WRIST_1_4",
  MaleBlackSports: "SP_M_LEFT_WRIST_2_0",
  MaleRedSports: "SP_M_LEFT_WRIST_2_1",
  MaleWhiteSports: "SP_M_LEFT_WRIST_2_2",
  MaleYellowSports: "SP_M_LEFT_WRIST_2_3",
  MaleBlueSports: "SP_M_LEFT_WRIST_2_4",
  FemalePewterWatch: "SP_F_LEFT_WRIST_0_4",
  MalePendulusSportBlackSports: "DLC_MP_BEACH_M_WATCH_1_0",
  MalePfisterDesignRedSports: "DLC_MP_BEACH_M_WATCH_1_1",
  MaleWhiteSports2: "DLC_MP_BEACH_M_WATCH_1_2",
  MaleYellowSports2: "DLC_MP_BEACH_M_WATCH_1_3",
  MaleBlueSports2: "DLC_MP_BEACH_M_WATCH_1_4",
  FemaleSilverBeadedBracelet: "DLC_MP_X22_F_PLEFT_WRIST_0_0",
  FemaleMonoBeadedBracelet: "DLC_MP_X22_F_PLEFT_WRIST_0_1",
  FemaleGoldBeadedBracelet: "DLC_MP_X22_F_PLEFT_WRIST_0_2",
  FemaleRoseBeadedBracelet: "DLC_MP_X22_F_PLEFT_WRIST_0_3",
  FemaleCopperBeadedBracelet: "DLC_MP_X22_F_PLEFT_WRIST_0_4",
  FemaleOxBloodBraceletEnsemble: "DLC_MP_X22_F_PLEFT_WRIST_1_0",
  FemaleGreenBraceletEnsemble: "DLC_MP_X22_F_PLEFT_WRIST_1_1",
  FemaleTanBraceletEnsemble: "DLC_MP_X22_F_PLEFT_WRIST_1_2",
  FemaleBlushBraceletEnsemble: "DLC_MP_X22_F_PLEFT_WRIST_1_3",
  FemaleDarkBraceletEnsemble: "DLC_MP_X22_F_PLEFT_WRIST_1_4",
  MaleSilverBeadedBracelet: "DLC_MP_X22_M_PLEFT_WRIST_0_0",
  MaleMonoBeadedBracelet: "DLC_MP_X22_M_PLEFT_WRIST_0_1",
  MaleGoldBeadedBracelet: "DLC_MP_X22_M_PLEFT_WRIST_0_2",
  MaleRoseBeadedBracelet: "DLC_MP_X22_M_PLEFT_WRIST_0_3",
  MaleCopperBeadedBracelet: "DLC_MP_X22_M_PLEFT_WRIST_0_4",
  MaleOxBloodBraceletEnsemble: "DLC_MP_X22_M_PLEFT_WRIST_1_0",
  MaleGreenBraceletEnsemble: "DLC_MP_X22_M_PLEFT_WRIST_1_1",
  MaleTanBraceletEnsemble: "DLC_MP_X22_M_PLEFT_WRIST_1_2",
  MaleBlushBraceletEnsemble: "DLC_MP_X22_M_PLEFT_WRIST_1_3",
  MaleDarkBraceletEnsemble: "DLC_MP_X22_M_PLEFT_WRIST_1_4",
  MaleRedLedWhiteStrap2: "DLC_MP_HIPS_M_WATCH_0_0",
  MaleRedLedBrownStrap2: "DLC_MP_HIPS_M_WATCH_0_1",
  MaleWhiteLedGoldStrap: "DLC_MP_HIPS_M_WATCH_0_2",
  MaleYellowLedYellowStrap: "DLC_MP_HIPS_M_WATCH_0_3",
  FemaleBlueBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_0",
  FemaleRedBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_1",
  FemaleSunsetBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_10",
  FemaleTropicalBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_11",
  FemalePinkBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_2",
  FemaleYellowBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_3",
  FemaleOrangeBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_4",
  FemaleGreenBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_5",
  FemaleRedBlueBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_6",
  FemaleYellowOrangeBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_7",
  FemaleGreenPinkBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_8",
  FemaleRainbowBanglesL: "DLC_MP_H4_F_PLEFT_WRIST_0_9",
  MaleBlueBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_0",
  MaleRedBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_1",
  MaleSunsetBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_10",
  MaleTropicalBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_11",
  MalePinkBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_2",
  MaleYellowBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_3",
  MaleOrangeBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_4",
  MaleGreenBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_5",
  MaleRedBlueBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_6",
  MaleYellowOrangeBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_7",
  MaleGreenPinkBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_8",
  MaleRainbowBanglesL: "DLC_MP_H4_M_PLEFT_WRIST_0_9",
  MalePinkGoldKronosQuantum: "MP_DLC_LUXE_M_PLEFT_WRIST_0_0",
  MaleSilverKronosQuantum: "MP_DLC_LUXE_M_PLEFT_WRIST_0_1",
  MaleCarbonKronosQuantum: "MP_DLC_LUXE_M_PLEFT_WRIST_0_2",
  MalePlatinumGaulleRetroHex: "MP_DLC_LUXE_M_PLEFT_WRIST_1_0",
  MaleCarbonGaulleRetroHex: "MP_DLC_LUXE_M_PLEFT_WRIST_1_1",
  MaleGoldGaulleRetroHex: "MP_DLC_LUXE_M_PLEFT_WRIST_1_2",
  MaleGoldCovgariSupernova: "MP_DLC_LUXE_M_PLEFT_WRIST_2_0",
  MaleCarbonCovgariSupernova: "MP_DLC_LUXE_M_PLEFT_WRIST_2_1",
  MalePinkGoldCovgariSupernova: "MP_DLC_LUXE_M_PLEFT_WRIST_2_2",
  MalePlatinumPendulusGalaxis: "MP_DLC_LUXE_M_PLEFT_WRIST_3_0",
  MaleCarbonPendulusGalaxis: "MP_DLC_LUXE_M_PLEFT_WRIST_3_1",
  MaleGoldPendulusGalaxis: "MP_DLC_LUXE_M_PLEFT_WRIST_3_2",
  MaleSilverCrowexChromosphere: "MP_DLC_LUXE_M_PLEFT_WRIST_4_0",
  MaleGoldCrowexChromosphere: "MP_DLC_LUXE_M_PLEFT_WRIST_4_1",
  MaleCarbonCrowexChromosphere: "MP_DLC_LUXE_M_PLEFT_WRIST_4_2",
  MalePinkGoldVangelicoGeomeister: "MP_DLC_LUXE_M_PLEFT_WRIST_5_0",
  MaleSilverVangelicoGeomeister: "MP_DLC_LUXE_M_PLEFT_WRIST_5_1",
  MaleGoldVangelicoGeomeister: "MP_DLC_LUXE_M_PLEFT_WRIST_5_2",
  MaleGoldIfruitLink: "MP_DLC_LUXE_M_PLEFT_WRIST_6_0",
  MaleSilverIfruitLink: "MP_DLC_LUXE_M_PLEFT_WRIST_6_1",
  MalePinkGoldIfruitLink: "MP_DLC_LUXE_M_PLEFT_WRIST_6_2",
  MaleCarbonIfruitTech: "MP_DLC_LUXE_M_PLEFT_WRIST_7_0",
  MaleLimeIfruitTech: "MP_DLC_LUXE_M_PLEFT_WRIST_7_1",
  MalePrbIfruitTech: "MP_DLC_LUXE_M_PLEFT_WRIST_7_2",
  MaleLightWristChainL: "DLC_MP_BIKER_M_PLEFT_WRIST_0_0",
  MaleChunkyWristChainL: "DLC_MP_BIKER_M_PLEFT_WRIST_1_0",
  MaleSquareWristChainL: "DLC_MP_BIKER_M_PLEFT_WRIST_2_0",
  MaleSkullWristChainL: "DLC_MP_BIKER_M_PLEFT_WRIST_3_0",
  MaleTreadWristChainL: "DLC_MP_BIKER_M_PLEFT_WRIST_4_0",
  MaleGearWristChainsL: "DLC_MP_BIKER_M_PLEFT_WRIST_5_0",
  MaleSpikedGauntletL: "DLC_MP_BIKER_M_PLEFT_WRIST_6_0",
  MaleBlackGauntletL: "DLC_MP_BIKER_M_PLEFT_WRIST_7_0",
  MaleChocolateGauntletL: "DLC_MP_BIKER_M_PLEFT_WRIST_7_1",
  MaleTanGauntletL: "DLC_MP_BIKER_M_PLEFT_WRIST_7_2",
  MaleOxBloodGauntletL: "DLC_MP_BIKER_M_PLEFT_WRIST_7_3",
  FemaleLightWristChainL: "DLC_MP_BIKER_F_PLEFT_WRIST_0_0",
  FemaleChunkyWristChainL: "DLC_MP_BIKER_F_PLEFT_WRIST_1_0",
  FemaleSquareWristChainL: "DLC_MP_BIKER_F_PLEFT_WRIST_2_0",
  FemaleSkullWristChainL: "DLC_MP_BIKER_F_PLEFT_WRIST_3_0",
  FemaleTreadWristChainL: "DLC_MP_BIKER_F_PLEFT_WRIST_4_0",
  FemaleGearWristChainsL: "DLC_MP_BIKER_F_PLEFT_WRIST_5_0",
  FemaleSpikedGauntletL: "DLC_MP_BIKER_F_PLEFT_WRIST_6_0",
  FemaleBlackGauntletL: "DLC_MP_BIKER_F_PLEFT_WRIST_7_0",
  FemaleChocolateGauntletL: "DLC_MP_BIKER_F_PLEFT_WRIST_7_1",
  FemaleTanGauntletL: "DLC_MP_BIKER_F_PLEFT_WRIST_7_2",
  FemaleOxBloodGauntletL: "DLC_MP_BIKER_F_PLEFT_WRIST_7_3",
  FemaleGoldEnduringWatch: "DLC_MP_VWD_F_PLEFT_WRIST_0_0",
  FemaleSilverEnduringWatch: "DLC_MP_VWD_F_PLEFT_WRIST_0_1",
  FemaleBlackEnduringWatch: "DLC_MP_VWD_F_PLEFT_WRIST_0_2",
  FemaleDeckEnduringWatch: "DLC_MP_VWD_F_PLEFT_WRIST_0_3",
  FemaleRoyalEnduringWatch: "DLC_MP_VWD_F_PLEFT_WRIST_0_4",
  FemaleRouletteEnduringWatch: "DLC_MP_VWD_F_PLEFT_WRIST_0_5",
  FemaleGoldKronosTempo: "DLC_MP_VWD_F_PLEFT_WRIST_1_0",
  FemaleSilverKronosTempo: "DLC_MP_VWD_F_PLEFT_WRIST_1_1",
  FemaleBlackKronosTempo: "DLC_MP_VWD_F_PLEFT_WRIST_1_2",
  FemaleGoldFiftyKronosTempo: "DLC_MP_VWD_F_PLEFT_WRIST_1_3",
  FemaleGoldRouletteKronosTempo: "DLC_MP_VWD_F_PLEFT_WRIST_1_4",
  FemaleBaroqueKronosTempo: "DLC_MP_VWD_F_PLEFT_WRIST_1_5",
  FemaleGoldKronosPulse: "DLC_MP_VWD_F_PLEFT_WRIST_2_0",
  FemaleSilverKronosPulse: "DLC_MP_VWD_F_PLEFT_WRIST_2_1",
  FemaleBlackKronosPulse: "DLC_MP_VWD_F_PLEFT_WRIST_2_2",
  FemaleSilverFiftyKronosPulse: "DLC_MP_VWD_F_PLEFT_WRIST_2_3",
  FemaleSilverRouletteKronosPulse: "DLC_MP_VWD_F_PLEFT_WRIST_2_4",
  FemaleSpadeKronosPulse: "DLC_MP_VWD_F_PLEFT_WRIST_2_5",
  FemaleRedFameOrShameKronos: "DLC_MP_VWD_F_PLEFT_WRIST_2_6",
  FemaleGreenFameOrShameKronos: "DLC_MP_VWD_F_PLEFT_WRIST_2_7",
  FemaleBlueFameOrShameKronos: "DLC_MP_VWD_F_PLEFT_WRIST_2_8",
  FemaleBlackFameOrShameKronos: "DLC_MP_VWD_F_PLEFT_WRIST_2_9",
  FemaleGoldKronosRa: "DLC_MP_VWD_F_PLEFT_WRIST_3_0",
  FemaleSilverKronosRa: "DLC_MP_VWD_F_PLEFT_WRIST_3_1",
  FemaleBlackKronosRa: "DLC_MP_VWD_F_PLEFT_WRIST_3_2",
  FemaleGoldFiftyKronosRa: "DLC_MP_VWD_F_PLEFT_WRIST_3_3",
  FemaleTanSpadeKronosRa: "DLC_MP_VWD_F_PLEFT_WRIST_3_4",
  FemaleBrownSpadeKronosRa: "DLC_MP_VWD_F_PLEFT_WRIST_3_5",
  FemaleGoldCeaseless: "DLC_MP_VWD_F_PLEFT_WRIST_4_0",
  FemaleSilverCeaseless: "DLC_MP_VWD_F_PLEFT_WRIST_4_1",
  FemaleBlackCeaseless: "DLC_MP_VWD_F_PLEFT_WRIST_4_2",
  FemaleSpadeCeaseless: "DLC_MP_VWD_F_PLEFT_WRIST_4_3",
  FemaleMixedMetalsCeaseless: "DLC_MP_VWD_F_PLEFT_WRIST_4_4",
  FemaleRouletteCeaseless: "DLC_MP_VWD_F_PLEFT_WRIST_4_5",
  FemaleSilverCrowexPoque: "DLC_MP_VWD_F_PLEFT_WRIST_5_0",
  FemaleGoldCrowexPoque: "DLC_MP_VWD_F_PLEFT_WRIST_5_1",
  FemaleBlackCrowexPoque: "DLC_MP_VWD_F_PLEFT_WRIST_5_2",
  FemaleWheelCrowexPoque: "DLC_MP_VWD_F_PLEFT_WRIST_5_3",
  FemaleSuitsCrowexPoque: "DLC_MP_VWD_F_PLEFT_WRIST_5_4",
  FemaleRouletteCrowexPoque: "DLC_MP_VWD_F_PLEFT_WRIST_5_5",
  FemaleGoldKronosQuad: "DLC_MP_VWD_F_PLEFT_WRIST_6_0",
  FemaleSilverKronosQuad: "DLC_MP_VWD_F_PLEFT_WRIST_6_1",
  FemaleBlackKronosQuad: "DLC_MP_VWD_F_PLEFT_WRIST_6_2",
  FemaleRouletteKronosQuad: "DLC_MP_VWD_F_PLEFT_WRIST_6_3",
  FemaleFiftyKronosQuad: "DLC_MP_VWD_F_PLEFT_WRIST_6_4",
  FemaleSuitsKronosQuad: "DLC_MP_VWD_F_PLEFT_WRIST_6_5",
  FemaleSilverCrowexRond: "DLC_MP_VWD_F_PLEFT_WRIST_7_0",
  FemaleGoldCrowexRond: "DLC_MP_VWD_F_PLEFT_WRIST_7_1",
  FemaleBlackCrowexRond: "DLC_MP_VWD_F_PLEFT_WRIST_7_2",
  FemaleSpadeCrowexRond: "DLC_MP_VWD_F_PLEFT_WRIST_7_3",
  FemaleRoyaltyCrowexRond: "DLC_MP_VWD_F_PLEFT_WRIST_7_4",
  FemaleDiceCrowexRond: "DLC_MP_VWD_F_PLEFT_WRIST_7_5",
  FemaleSilverSassWristPiece: "DLC_MP_VWD_F_PLEFT_WRIST_8_0",
  FemaleGoldSassWristPiece: "DLC_MP_VWD_F_PLEFT_WRIST_8_1",
  FemaleBlackSassWristPiece: "DLC_MP_VWD_F_PLEFT_WRIST_8_2",
  FemaleSilverSassBracelet: "DLC_MP_VWD_F_PLEFT_WRIST_9_0",
  FemaleGoldSassBracelet: "DLC_MP_VWD_F_PLEFT_WRIST_9_1",
  FemaleBlackSassBracelet: "DLC_MP_VWD_F_PLEFT_WRIST_9_2",
  MaleGoldEnduringWatch: "DLC_MP_VWD_M_PLEFT_WRIST_0_0",
  MaleSilverEnduringWatch: "DLC_MP_VWD_M_PLEFT_WRIST_0_1",
  MaleBlackEnduringWatch: "DLC_MP_VWD_M_PLEFT_WRIST_0_2",
  MaleDeckEnduringWatch: "DLC_MP_VWD_M_PLEFT_WRIST_0_3",
  MaleRoyalEnduringWatch: "DLC_MP_VWD_M_PLEFT_WRIST_0_4",
  MaleRouletteEnduringWatch: "DLC_MP_VWD_M_PLEFT_WRIST_0_5",
  MaleGoldKronosTempo: "DLC_MP_VWD_M_PLEFT_WRIST_1_0",
  MaleSilverKronosTempo: "DLC_MP_VWD_M_PLEFT_WRIST_1_1",
  MaleBlackKronosTempo: "DLC_MP_VWD_M_PLEFT_WRIST_1_2",
  MaleGoldFiftyKronosTempo: "DLC_MP_VWD_M_PLEFT_WRIST_1_3",
  MaleGoldRouletteKronosTempo: "DLC_MP_VWD_M_PLEFT_WRIST_1_4",
  MaleBaroqueKronosTempo: "DLC_MP_VWD_M_PLEFT_WRIST_1_5",
  MaleGoldKronosPulse: "DLC_MP_VWD_M_PLEFT_WRIST_2_0",
  MaleSilverKronosPulse: "DLC_MP_VWD_M_PLEFT_WRIST_2_1",
  MaleBlackKronosPulse: "DLC_MP_VWD_M_PLEFT_WRIST_2_2",
  MaleSilverFiftyKronosPulse: "DLC_MP_VWD_M_PLEFT_WRIST_2_3",
  MaleSilverRouletteKronosPulse: "DLC_MP_VWD_M_PLEFT_WRIST_2_4",
  MaleSpadeKronosPulse: "DLC_MP_VWD_M_PLEFT_WRIST_2_5",
  MaleRedFameOrShameKronos: "DLC_MP_VWD_M_PLEFT_WRIST_2_6",
  MaleGreenFameOrShameKronos: "DLC_MP_VWD_M_PLEFT_WRIST_2_7",
  MaleBlueFameOrShameKronos: "DLC_MP_VWD_M_PLEFT_WRIST_2_8",
  MaleBlackFameOrShameKronos: "DLC_MP_VWD_M_PLEFT_WRIST_2_9",
  MaleGoldKronosRa: "DLC_MP_VWD_M_PLEFT_WRIST_3_0",
  MaleSilverKronosRa: "DLC_MP_VWD_M_PLEFT_WRIST_3_1",
  MaleBlackKronosRa: "DLC_MP_VWD_M_PLEFT_WRIST_3_2",
  MaleGoldFiftyKronosRa: "DLC_MP_VWD_M_PLEFT_WRIST_3_3",
  MaleTanSpadeKronosRa: "DLC_MP_VWD_M_PLEFT_WRIST_3_4",
  MaleBrownSpadeKronosRa: "DLC_MP_VWD_M_PLEFT_WRIST_3_5",
  MaleGoldCeaseless: "DLC_MP_VWD_M_PLEFT_WRIST_4_0",
  MaleSilverCeaseless: "DLC_MP_VWD_M_PLEFT_WRIST_4_1",
  MaleBlackCeaseless: "DLC_MP_VWD_M_PLEFT_WRIST_4_2",
  MaleSpadeCeaseless: "DLC_MP_VWD_M_PLEFT_WRIST_4_3",
  MaleMixedMetalsCeaseless: "DLC_MP_VWD_M_PLEFT_WRIST_4_4",
  MaleRouletteCeaseless: "DLC_MP_VWD_M_PLEFT_WRIST_4_5",
  MaleSilverCrowexPoque: "DLC_MP_VWD_M_PLEFT_WRIST_5_0",
  MaleGoldCrowexPoque: "DLC_MP_VWD_M_PLEFT_WRIST_5_1",
  MaleBlackCrowexPoque: "DLC_MP_VWD_M_PLEFT_WRIST_5_2",
  MaleWheelCrowexPoque: "DLC_MP_VWD_M_PLEFT_WRIST_5_3",
  MaleSuitsCrowexPoque: "DLC_MP_VWD_M_PLEFT_WRIST_5_4",
  MaleRouletteCrowexPoque: "DLC_MP_VWD_M_PLEFT_WRIST_5_5",
  MaleGoldKronosQuad: "DLC_MP_VWD_M_PLEFT_WRIST_6_0",
  MaleSilverKronosQuad: "DLC_MP_VWD_M_PLEFT_WRIST_6_1",
  MaleBlackKronosQuad: "DLC_MP_VWD_M_PLEFT_WRIST_6_2",
  MaleRouletteKronosQuad: "DLC_MP_VWD_M_PLEFT_WRIST_6_3",
  MaleFiftyKronosQuad: "DLC_MP_VWD_M_PLEFT_WRIST_6_4",
  MaleSuitsKronosQuad: "DLC_MP_VWD_M_PLEFT_WRIST_6_5",
  MaleSilverCrowexRond: "DLC_MP_VWD_M_PLEFT_WRIST_7_0",
  MaleGoldCrowexRond: "DLC_MP_VWD_M_PLEFT_WRIST_7_1",
  MaleBlackCrowexRond: "DLC_MP_VWD_M_PLEFT_WRIST_7_2",
  MaleSpadeCrowexRond: "DLC_MP_VWD_M_PLEFT_WRIST_7_3",
  MaleRoyaltyCrowexRond: "DLC_MP_VWD_M_PLEFT_WRIST_7_4",
  MaleDiceCrowexRond: "DLC_MP_VWD_M_PLEFT_WRIST_7_5",
  MaleSilverSassWristPiece: "DLC_MP_VWD_M_PLEFT_WRIST_8_0",
  MaleGoldSassWristPiece: "DLC_MP_VWD_M_PLEFT_WRIST_8_1",
  MaleBlackSassWristPiece: "DLC_MP_VWD_M_PLEFT_WRIST_8_2",
  MaleSilverSassBracelet: "DLC_MP_VWD_M_PLEFT_WRIST_9_0",
  MaleGoldSassBracelet: "DLC_MP_VWD_M_PLEFT_WRIST_9_1",
  MaleBlackSassBracelet: "DLC_MP_VWD_M_PLEFT_WRIST_9_2",
  FemaleGoldEncrustedBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_0_0",
  FemaleSilverEncrustedBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_0_1",
  FemaleRoseEncrustedBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_0_2",
  FemaleGoldUrsineBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_1_0",
  FemaleSilverUrsineBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_1_1",
  FemaleRoseUrsineBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_1_2",
  FemaleGoldRoundBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_2_0",
  FemaleSilverRoundBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_2_1",
  FemaleRoseRoundBracelet: "DLC_MP_SUM2_F_PLEFT_WRIST_2_2",
  FemaleGoldSquareJewelChain: "DLC_MP_SUM2_F_PLEFT_WRIST_3_0",
  FemaleSilverSquareJewelChain: "DLC_MP_SUM2_F_PLEFT_WRIST_3_1",
  FemaleRoseSquareJewelChain: "DLC_MP_SUM2_F_PLEFT_WRIST_3_2",
  MaleSilverCovgariExplorer: "DLC_MP_LUXE2_M_PLEFT_WRIST_0_0",
  MalePinkGoldCovgariExplorer: "DLC_MP_LUXE2_M_PLEFT_WRIST_0_1",
  MaleGoldCovgariExplorer: "DLC_MP_LUXE2_M_PLEFT_WRIST_0_2",
  MaleSilverPendulusGravity: "DLC_MP_LUXE2_M_PLEFT_WRIST_1_0",
  MaleGoldPendulusGravity: "DLC_MP_LUXE2_M_PLEFT_WRIST_1_1",
  MalePlatinumPendulusGravity: "DLC_MP_LUXE2_M_PLEFT_WRIST_1_2",
  MaleGoldCovgariUniverse: "DLC_MP_LUXE2_M_PLEFT_WRIST_2_0",
  MaleSilverCovgariUniverse: "DLC_MP_LUXE2_M_PLEFT_WRIST_2_1",
  MaleSteelCovgariUniverse: "DLC_MP_LUXE2_M_PLEFT_WRIST_2_2",
  MaleCopperGaulleDestiny: "DLC_MP_LUXE2_M_PLEFT_WRIST_3_0",
  MaleVintageGaulleDestiny: "DLC_MP_LUXE2_M_PLEFT_WRIST_3_1",
  MaleSilverGaulleDestiny: "DLC_MP_LUXE2_M_PLEFT_WRIST_3_2",
  MaleCarbonMediciRadial: "DLC_MP_LUXE2_M_PLEFT_WRIST_4_0",
  MaleSilverMediciRadial: "DLC_MP_LUXE2_M_PLEFT_WRIST_4_1",
  MaleSteelMediciRadial: "DLC_MP_LUXE2_M_PLEFT_WRIST_4_2",
  MaleSilverPendulusTimestar: "DLC_MP_LUXE2_M_PLEFT_WRIST_5_0",
  MaleGoldPendulusTimestar: "DLC_MP_LUXE2_M_PLEFT_WRIST_5_1",
  MaleCarbonPendulusTimestar: "DLC_MP_LUXE2_M_PLEFT_WRIST_5_2",
  MaleCarbonKronosSubmariner: "DLC_MP_LUXE2_M_PLEFT_WRIST_6_0",
  MaleRedKronosSubmariner: "DLC_MP_LUXE2_M_PLEFT_WRIST_6_1",
  MaleYellowKronosSubmariner: "DLC_MP_LUXE2_M_PLEFT_WRIST_6_2",
  MaleRedIfruitSnap: "DLC_MP_LUXE2_M_PLEFT_WRIST_7_0",
  MaleBlueIfruitSnap: "DLC_MP_LUXE2_M_PLEFT_WRIST_7_1",
  MaleMintIfruitSnap: "DLC_MP_LUXE2_M_PLEFT_WRIST_7_2",
  MaleGoldWatch2: "DLC_MP_BUSINESS_M_WATCH0_0",
  MaleSilverWatch2: "DLC_MP_BUSINESS_M_WATCH0_1",
  MaleBlackWatch2: "DLC_MP_BUSINESS_M_WATCH0_2",
  MaleWhiteGoldWatch: "DLC_MP_BUSINESS_M_WATCH0_3",
  FemaleGoldLeChienMarquise: "DLC_MP_LUXE2_F_PLEFT_WRIST_0_0",
  FemaleSilverLeChienMarquise: "DLC_MP_LUXE2_F_PLEFT_WRIST_0_1",
  FemalePinkGoldLeChienMarquise: "DLC_MP_LUXE2_F_PLEFT_WRIST_0_2",
  FemaleGrayFufuJeunesse: "DLC_MP_LUXE2_F_PLEFT_WRIST_1_0",
  FemaleBlackFufuJeunesse: "DLC_MP_LUXE2_F_PLEFT_WRIST_1_1",
  FemaleBlueFufuJeunesse: "DLC_MP_LUXE2_F_PLEFT_WRIST_1_2",
  FemaleSilverAnnaRexPrestige: "DLC_MP_LUXE2_F_PLEFT_WRIST_2_0",
  FemaleGoldAnnaRexPrestige: "DLC_MP_LUXE2_F_PLEFT_WRIST_2_1",
  FemaleCarbonAnnaRexPrestige: "DLC_MP_LUXE2_F_PLEFT_WRIST_2_2",
  FemaleLimeIfruitSnap: "DLC_MP_LUXE2_F_PLEFT_WRIST_3_0",
  FemaleWhiteIfruitSnap: "DLC_MP_LUXE2_F_PLEFT_WRIST_3_1",
  FemaleNeonIfruitSnap: "DLC_MP_LUXE2_F_PLEFT_WRIST_3_2",
  FemaleGoldCacaDiLusso: "DLC_MP_LUXE_F_PLEFT_WRIST_0_0",
  FemaleSilverCacaDiLusso: "DLC_MP_LUXE_F_PLEFT_WRIST_0_1",
  FemalePinkGoldCacaDiLusso: "DLC_MP_LUXE_F_PLEFT_WRIST_0_2",
  FemaleSilverDidierSachsMignon: "DLC_MP_LUXE_F_PLEFT_WRIST_1_0",
  FemalePinkGoldDidierSachsMignon: "DLC_MP_LUXE_F_PLEFT_WRIST_1_1",
  FemaleGoldDidierSachsMignon: "DLC_MP_LUXE_F_PLEFT_WRIST_1_2",
  FemaleGoldIfruitLink: "DLC_MP_LUXE_F_PLEFT_WRIST_2_0",
  FemaleSilverIfruitLink: "DLC_MP_LUXE_F_PLEFT_WRIST_2_1",
  FemalePinkGoldIfruitLink: "DLC_MP_LUXE_F_PLEFT_WRIST_2_2",
  FemaleWhiteIfruitTech: "DLC_MP_LUXE_F_PLEFT_WRIST_3_0",
  FemalePinkIfruitTech: "DLC_MP_LUXE_F_PLEFT_WRIST_3_1",
  FemalePrbIfruitTech: "DLC_MP_LUXE_F_PLEFT_WRIST_3_2",
  MaleGoldEncrustedBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_0_0",
  MaleSilverEncrustedBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_0_1",
  MaleRoseEncrustedBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_0_2",
  MaleGoldUrsineBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_1_0",
  MaleSilverUrsineBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_1_1",
  MaleRoseUrsineBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_1_2",
  MaleGoldRoundBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_2_0",
  MaleSilverRoundBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_2_1",
  MaleRoseRoundBracelet: "DLC_MP_SUM2_M_PLEFT_WRIST_2_2",
  MaleGoldSquareJewelChain: "DLC_MP_SUM2_M_PLEFT_WRIST_3_0",
  MaleSilverSquareJewelChain: "DLC_MP_SUM2_M_PLEFT_WRIST_3_1",
  MaleRoseSquareJewelChain: "DLC_MP_SUM2_M_PLEFT_WRIST_3_2",
  FemaleGoldFashion: "DLC_MP_BUSINESS_F_WATCH0_0",
  FemaleSilverFashion: "DLC_MP_BUSINESS_F_WATCH0_1",
  FemaleCopperFashion: "DLC_MP_BUSINESS_F_WATCH0_2",
  FemaleBlackFashion: "DLC_MP_BUSINESS_F_WATCH0_3",
});

export type LeftHandItemKey = Brand<string, "LeftHandItemKey">;

export type LeftHandItem = {
  key: LeftHandItemKey;

  customName?: string | null;
};

export type LeftHandItemInfo = {
  key: LeftHandItemKey;
  ped: string;
  componentId: number;
  drawableId: number;
  textureId: number;
  name: string;
  price: number;
  restrictionTags: string[] | null;
};

export const lefthand: Record<LeftHandItemKey, LeftHandItemInfo> = LEFTHAND_ITEMS as Record<
  LeftHandItemKey,
  LeftHandItemInfo
>;

/**
 * Register all melee weapons.
 */
for (const [key, info] of Object.entries(lefthand)) {
  registerItem(key as LeftHandItemKey, info);
}

/**
 * Type guards for melee weapons
 */
export function isItemKeyLeftHand(key: string): key is LeftHandItemKey {
  return key in lefthand;
}

export function isItemLeftHand(item: Item): item is LeftHandItem {
  return isItemKeyLeftHand(item.key);
}
