FROM node:20.11.0-bookworm-slim as base
USER root
ARG BRANCH=dev
ARG DATABASE_URL
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG REDIRECT_IP
ARG NODE_ENV
ARG ALTV_HOST
ARG ALTV_NAME
ARG ALTV_PORT
ARG ALTV_PASSWORD
ARG ALTV_ANNOUNCE
ARG ALTV_DEBUG
ARG ALTV_MODULES
ARG ALTV_RESOURCES

ENV ALTV_BRANCH=$BRANCH
ENV DATABASE_URL=$DATABASE_URL
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
ENV REDIRECT_IP=$REDIRECT_IP
ENV NODE_ENV=$NODE_ENV
ENV ALTV_HOST=$ALTV_HOST
ENV ALTV_NAME=$ALTV_NAME
ENV ALTV_PORT=$ALTV_PORT
ENV ALTV_PASSWORD=$ALTV_PASSWORD
ENV ALTV_ANNOUNCE=$ALTV_ANNOUNCE
ENV ALTV_DEBUG=$ALTV_DEBUG
ENV ALTV_MODULES=$ALTV_MODULES
ENV ALTV_RESOURCES=$ALTV_RESOURCES

RUN apt-get update -y && apt-get install -y curl lsof libatomic1 libc-bin wget apt-transport-https ca-certificates gnupg procps stow && apt autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# log env vars to a file
RUN echo "$(printenv | sort)" >> /root/.env

COPY ./docker-scripts /root/setup
COPY ./altv /altv

WORKDIR /root/setup

RUN npm i -g bun && bun install && bun add -g altv-pkg@latest

WORKDIR /altv

RUN bun run /root/setup/server.js

RUN bunx altv-pkg $ALTV_BRANCH
RUN chmod +x altv-server altv-crash-handler

RUN bun i
RUN bun run prisma:generate
RUN bun run build

WORKDIR /altv/src/webview

RUN bun i
RUN bun run build-only

RUN cp -r dist /altv/resources/main/webview

RUN rm -rf /altv/node_modules
RUN rm -rf /altv/src

EXPOSE 7788/udp 7788/tcp 7799/udp 7790/tcp

ENTRYPOINT [ "/altv/altv-server" ]
