name: rift
services:
  # Replica Set (required for Prisma Client)
  mongo:
    build: ./altv/prisma/docker/mongodb_replica
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27018
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

  builder:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    volumes:
      - ./altv:/source
      - node_modules:/source/node_modules
      - altv:/altv
    entrypoint: ["/root/entrypoint.sh", "builder"]
    stdin_open: true
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        BRANCH: ${ALTV_BRANCH}
    restart: unless-stopped
    volumes:
      - ./altv:/source
      - node_modules:/source/node_modules
      - altv:/altv
    entrypoint: ["/root/entrypoint.sh", "server"]
    stdin_open: true
    ports:
      - "7788:7788"
      - "7788:7788/udp"
      - "7790:7790" # discord login
      - "6000:6000" # build watcher
    depends_on:
      - mongo
      - builder
    env_file:
      - .env
volumes:
  node_modules:
  mongo_data:
  altv:
    # graylog_data:
    # graylog_journal:
