FROM node:20.11.0-bookworm-slim as base
USER root
ARG BRANCH=dev
ARG DATABASE_URL
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG REDIRECT_IP
ARG SERVER_ENV
ARG ALTV_HOST
ARG ALTV_NAME
ARG ALTV_PORT
ARG ALTV_PASSWORD
ARG ALTV_ANNOUNCE
ARG ALTV_DEBUG
ARG ALTV_MODULES
ARG ALTV_RESOURCES
ARG S3_ACCESS_KEY
ARG S3_REGION
ARG S3_HOST_BASE
ARG S3_HOST_BUCKET
ARG S3_SECRET_KEY
ARG S3_WEBSITE_ENDPOINT

ENV ALTV_BRANCH=$BRANCH
ENV DATABASE_URL=$DATABASE_URL
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
ENV REDIRECT_IP=$REDIRECT_IP
ENV SERVER_ENV=$SERVER_ENV
ENV ALTV_HOST=$ALTV_HOST
ENV ALTV_NAME=$ALTV_NAME
ENV ALTV_PORT=$ALTV_PORT
ENV ALTV_PASSWORD=$ALTV_PASSWORD
ENV ALTV_ANNOUNCE=$ALTV_ANNOUNCE
ENV ALTV_DEBUG=$ALTV_DEBUG
ENV ALTV_MODULES=$ALTV_MODULES
ENV ALTV_RESOURCES=$ALTV_RESOURCES
ENV S3_ACCESS_KEY=$S3_ACCESS_KEY
ENV S3_REGION=$S3_REGION
ENV S3_HOST_BASE=$S3_HOST_BASE
ENV S3_HOST_BUCKET=$S3_HOST_BUCKET
ENV S3_SECRET_KEY=$S3_SECRET_KEY
ENV S3_WEBSITE_ENDPOINT=$S3_WEBSITE_ENDPOINT

RUN apt-get update -y && \
  apt-get install -y \
  # for altv server
  curl \
  lsof \
  libatomic1 \
  libc-bin \
  wget \
  apt-transport-https \
  ca-certificates \
  gnupg \
  # utils
  procps \
  stow \
  # cdn sync
  s3cmd && \
  # cleanup
  apt autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Generate .s3cfg for CDN sync
RUN echo " \
  [default] \
  access_key = ${S3_ACCESS_KEY} \
  access_token = \
  add_encoding_exts = \
  add_headers = \
  bucket_location = ${S3_REGION} \
  ca_certs_file = \
  cache_file = \
  check_ssl_certificate = True \
  check_ssl_hostname = True \
  cloudfront_host = cloudfront.amazonaws.com \
  connection_max_age = 5 \
  connection_pooling = True \
  content_disposition =  \
  content_type =  \
  default_mime_type = binary/octet-stream \
  delay_updates = False \
  delete_after = False \
  delete_after_fetch = False \
  delete_removed = False \
  dry_run = False \
  enable_multipart = True \
  encoding = UTF-8 \
  encrypt = False \
  expiry_date =  \
  expiry_days =  \
  expiry_prefix =  \
  follow_symlinks = False \
  force = False \
  get_continue = False \
  gpg_command = /usr/bin/gpg \
  gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s \
  gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s \
  gpg_passphrase = 5284691367 \
  guess_mime_type = True \
  host_base = ${S3_HOST_BASE} \
  host_bucket = ${S3_HOST_BUCKET} \
  human_readable_sizes = False \
  invalidate_default_index_on_cf = False \
  invalidate_default_index_root_on_cf = True \
  invalidate_on_cf = False \
  kms_key =  \
  limit = -1 \
  limitrate = 0 \
  list_md5 = False \
  log_target_prefix =  \
  long_listing = False \
  max_delete = -1 \
  mime_type =  \
  multipart_chunk_size_mb = 15 \
  multipart_copy_chunk_size_mb = 1024 \
  multipart_max_chunks = 10000 \
  preserve_attrs = True \
  progress_meter = True \
  proxy_host =  \
  proxy_port = 0 \
  public_url_use_https = False \
  put_continue = False \
  recursive = False \
  recv_chunk = 65536 \
  reduced_redundancy = False \
  requester_pays = False \
  restore_days = 1 \
  restore_priority = Standard \
  secret_key = ${S3_SECRET_KEY} \
  send_chunk = 65536 \
  server_side_encryption = False \
  signature_v2 = False \
  signurl_use_https = False \
  simpledb_host = sdb.amazonaws.com \
  skip_existing = False \
  socket_timeout = 300 \
  ssl_client_cert_file =  \
  ssl_client_key_file =  \
  stats = False \
  stop_on_error = False \
  storage_class =  \
  throttle_max = 100 \
  upload_id =  \
  urlencoding_mode = normal \
  use_http_expect = False \
  use_https = True \
  use_mime_magic = True \
  verbosity = WARNING \
  website_endpoint = ${S3_WEBSITE_ENDPOINT} \
  website_error =  \
  website_index = index.html \
  " > /root/.s3cfg

COPY ./docker-scripts /root/setup
COPY ./altv /altv

# Install global packages, setup the environment, and build the project
RUN npm install -g bun && \
  bun add -g altv-pkg@latest && \
  cd /root/setup && \
  bun install && \
  cd /altv && \
  bun run /root/setup/server.js && \
  bunx altv-pkg $ALTV_BRANCH && \
  chmod +x altv-server altv-crash-handler && \
  bun install && \
  bun run prisma:generate && \
  bun run build && \
  cd src/webview && \
  bun install && \
  bun run build-only && \
  mkdir /altv/resources/main/client/webview && \
  mv dist/index.html /altv/resources/main/client/webview && \
  s3cmd sync dist/ s3://altv-rift/webview-assets/ --acl-public --delete-removed && \
  rm -rf /root/setup /altv/src && \
  find /altv/node_modules -mindepth 1 -maxdepth 1 ! -name '.prisma' -exec rm -rf {} +

# Expose necessary ports
EXPOSE 7788/udp 7788/tcp 7799/udp 7790/tcp

# Set the entrypoint
WORKDIR /altv
ENTRYPOINT ["/altv/altv-server"]
