FROM node:20.11.0-bookworm-slim as base
USER root
ARG BRANCH=dev
ARG DATABASE_URL
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG REDIRECT_IP
ARG NODE_ENV
ARG ALTV_HOST
ARG ALTV_NAME
ARG ALTV_PORT
ARG ALTV_PASSWORD
ARG ALTV_ANNOUNCE
ARG ALTV_DEBUG
ARG ALTV_MODULES
ARG ALTV_RESOURCES

ENV ALTV_BRANCH=$BRANCH
ENV DATABASE_URL=$DATABASE_URL
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
ENV REDIRECT_IP=$REDIRECT_IP
ENV NODE_ENV=$NODE_ENV
ENV ALTV_HOST=$ALTV_HOST
ENV ALTV_NAME=$ALTV_NAME
ENV ALTV_PORT=$ALTV_PORT
ENV ALTV_PASSWORD=$ALTV_PASSWORD
ENV ALTV_ANNOUNCE=$ALTV_ANNOUNCE
ENV ALTV_DEBUG=$ALTV_DEBUG
ENV ALTV_MODULES=$ALTV_MODULES
ENV ALTV_RESOURCES=$ALTV_RESOURCES

RUN apt-get update -y && apt-get install -y curl lsof libatomic1 libc-bin wget apt-transport-https ca-certificates gnupg procps stow && apt autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./docker-scripts /root/setup
COPY ./altv /altv

# Install global packages, setup the environment, and build the project
RUN echo "$(printenv | sort)" >> .env && \
  npm install -g bun && \
  bun add -g altv-pkg@latest && \
  cd /root/setup && \
  bun install && \
  cd /altv && \
  bun run /root/setup/server.js && \
  bunx altv-pkg $ALTV_BRANCH && \
  chmod +x altv-server altv-crash-handler && \
  bun install && \
  bun run prisma:generate && \
  bun run build && \
  cd src/webview && \
  bun install && \
  bun run build-only && \
  cp -r dist /altv/resources/main/webview && \
  rm -rf /root/setup && \
  rm -rf /altv/src && \
  find node_modules -mindepth 1 -maxdepth 1 ! -name '.prisma' -exec rm -rf {} +

# Expose necessary ports
EXPOSE 7788/udp 7788/tcp 7799/udp 7790/tcp

# Set the entrypoint
WORKDIR /altv
ENTRYPOINT ["/altv/altv-server"]
