services:
  server:
    image: "${IMAGE_NAME}:latest"
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      labels:
        runnumber: "${GITHUB_RUN_ID}"
    restart: unless-stopped
    volumes:
      - ./altv:/altv
    stdin_open: true
    ports:
      - '7788:7788'
      - '7788:7788/udp'
      - '7790:7790' # discord login
    environment:
      - DATABASE_URL
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - REDIRECT_IP
      - NODE_ENV
      - ALTV_HOST
      - ALTV_NAME
      - ALTV_PORT
      - ALTV_PASSWORD
      - ALTV_ANNOUNCE
      - ALTV_DEBUG
      - ALTV_MODULES
      - ALTV_RESOURCES
