version: '3.7'

services:
  # Replica Set (required for Prisma Client)
  mongo:
    build: ./prisma/docker/mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
