name = "dev"

modules = ["js-module"]

resources = ["main", "qa-tools", "assets"]

debug = true

announce = false
host = '192.168.68.102'
port = 8888

[js-module]
extra-cli-args = [
  # resource restart in js module needs more memory
  "--max-old-space-size=8192",
]
