name = "yolo"

modules = ['js-module-v2', 'js-module']

resources = ["resource-control", "main", "qa-tools"]

debug = true

announce = false
host = '0.0.0.0'
port = 8888

[js-module]
extra-cli-args = [
  # resource restart in js module needs more memory
  "--max-old-space-size=8192",
]

[js-module-v2]
extra-cli-args = [
  # resource restart in js module needs more memory
  "--max-old-space-size=8192",
]
