import { Item, registerItems } from "@shared/modules/items";
import { makeKeys } from "@shared/utility/make-keys";
const EARRINGS_ITEMS: Record<string, EarringsItemInfo> = (await import("./earrings.json")).default as any;

export const Earrings = makeKeys<EarringsItemKey>()({
  FemaleGrayEarpiece: "DLC_MP_HEIST_F_EAR0_0",
  FemaleRedEarpiece: "DLC_MP_HEIST_F_EAR1_0",
  FemaleLcdEarpiece: "DLC_MP_HEIST_F_EAR2_0",
  MaleGrayEarpiece: "DLC_MP_HEIST_M_EAR0_0",
  MaleRedEarpiece: "DLC_MP_HEIST_M_EAR1_0",
  MaleLcdEarpiece: "DLC_MP_HEIST_M_EAR2_0",
  MaleGoldAngledHoopL: "DLC_MP_LUXE_M_PEARS_0_0",
  MaleBlackAngledHoopL: "DLC_MP_LUXE_M_PEARS_0_1",
  MalePlatinumAngledHoopL: "DLC_MP_LUXE_M_PEARS_0_2",
  MaleGoldAngledHoopR: "DLC_MP_LUXE_M_PEARS_1_0",
  MaleBlackAngledHoopR: "DLC_MP_LUXE_M_PEARS_1_1",
  MalePlatinumAngledHoopR: "DLC_MP_LUXE_M_PEARS_1_2",
  MaleGoldPillowStudR: "DLC_MP_LUXE_M_PEARS_10_0",
  MaleBlackPillowStudR: "DLC_MP_LUXE_M_PEARS_10_1",
  MalePlatinumPillowStudR: "DLC_MP_LUXE_M_PEARS_10_2",
  MaleGoldPillowStuds: "DLC_MP_LUXE_M_PEARS_11_0",
  MaleBlackPillowStuds: "DLC_MP_LUXE_M_PEARS_11_1",
  MalePlatinumPillowStuds: "DLC_MP_LUXE_M_PEARS_11_2",
  MaleGoldGemStudL: "DLC_MP_LUXE_M_PEARS_12_0",
  MaleBlackGemStudL: "DLC_MP_LUXE_M_PEARS_12_1",
  MalePlatinumGemStudL: "DLC_MP_LUXE_M_PEARS_12_2",
  MaleGoldGemStudR: "DLC_MP_LUXE_M_PEARS_13_0",
  MaleBlackGemStudR: "DLC_MP_LUXE_M_PEARS_13_1",
  MalePlatinumGemStudR: "DLC_MP_LUXE_M_PEARS_13_2",
  MaleGoldGemStuds: "DLC_MP_LUXE_M_PEARS_14_0",
  MaleBlackGemStuds: "DLC_MP_LUXE_M_PEARS_14_1",
  MalePlatinumGemStuds: "DLC_MP_LUXE_M_PEARS_14_2",
  MaleGoldIllusionSquareStudL: "DLC_MP_LUXE_M_PEARS_15_0",
  MaleGoldGridSquareStudL: "DLC_MP_LUXE_M_PEARS_15_1",
  MaleGoldNoirSquareStudL: "DLC_MP_LUXE_M_PEARS_15_2",
  MalePlatinumGridSquareStudL: "DLC_MP_LUXE_M_PEARS_15_3",
  MalePlatinumNoirSquareStudL: "DLC_MP_LUXE_M_PEARS_15_4",
  MaleGoldIllusionSquareStudR: "DLC_MP_LUXE_M_PEARS_16_0",
  MaleGoldGridSquareStudR: "DLC_MP_LUXE_M_PEARS_16_1",
  MaleGoldNoirSquareStudR: "DLC_MP_LUXE_M_PEARS_16_2",
  MalePlatinumGridSquareStudR: "DLC_MP_LUXE_M_PEARS_16_3",
  MalePlatinumNoirSquareStudR: "DLC_MP_LUXE_M_PEARS_16_4",
  MaleGoldIllusionSquareStuds: "DLC_MP_LUXE_M_PEARS_17_0",
  MaleGoldGridSquareStuds: "DLC_MP_LUXE_M_PEARS_17_1",
  MaleGoldNoirSquareStuds: "DLC_MP_LUXE_M_PEARS_17_2",
  MalePlatinumGridSquareStuds: "DLC_MP_LUXE_M_PEARS_17_3",
  MalePlatinumNoirSquareStuds: "DLC_MP_LUXE_M_PEARS_17_4",
  MaleGoldAngledHoops: "DLC_MP_LUXE_M_PEARS_2_0",
  MaleBlackAngledHoops: "DLC_MP_LUXE_M_PEARS_2_1",
  MalePlatinumAngledHoops: "DLC_MP_LUXE_M_PEARS_2_2",
  MaleGoldCircleStudL: "DLC_MP_LUXE_M_PEARS_3_0",
  MalePlatinumCircleStudL: "DLC_MP_LUXE_M_PEARS_3_1",
  MaleGoldCircleStudR: "DLC_MP_LUXE_M_PEARS_4_0",
  MalePlatinumCircleStudR: "DLC_MP_LUXE_M_PEARS_4_1",
  MaleGoldCircleStuds: "DLC_MP_LUXE_M_PEARS_5_0",
  MalePlatinumCircleStuds: "DLC_MP_LUXE_M_PEARS_5_1",
  MaleGoldDiamondStudL: "DLC_MP_LUXE_M_PEARS_6_0",
  MaleBlackDiamondStudL: "DLC_MP_LUXE_M_PEARS_6_1",
  MalePlatinumDiamondStudL: "DLC_MP_LUXE_M_PEARS_6_2",
  MaleGoldDiamondStudR: "DLC_MP_LUXE_M_PEARS_7_0",
  MaleBlackDiamondStudR: "DLC_MP_LUXE_M_PEARS_7_1",
  MalePlatinumDiamondStudR: "DLC_MP_LUXE_M_PEARS_7_2",
  MaleGoldDiamondStuds: "DLC_MP_LUXE_M_PEARS_8_0",
  MaleBlackDiamondStuds: "DLC_MP_LUXE_M_PEARS_8_1",
  MalePlatinumDiamondStuds: "DLC_MP_LUXE_M_PEARS_8_2",
  MaleGoldPillowStudL: "DLC_MP_LUXE_M_PEARS_9_0",
  MaleBlackPillowStudL: "DLC_MP_LUXE_M_PEARS_9_1",
  MalePlatinumPillowStudL: "DLC_MP_LUXE_M_PEARS_9_2",
  FemaleFuHoops: "DLC_MP_LOW2_F_PEARS_0_0",
  FemaleScrewYouHoops: "DLC_MP_LOW2_F_PEARS_1_0",
  FemaleAssaultHoops: "DLC_MP_LOW_F_PEARS_0_0",
  FemaleChunkyHoops: "DLC_MP_LOW_F_PEARS_1_0",
  FemaleClassicHoops: "DLC_MP_LOW_F_PEARS_2_0",
  FemaleGoldFameOrShameMics: "DLC_MP_VWD_F_PEARS_0_0",
  FemaleSilverFameOrShameMics: "DLC_MP_VWD_F_PEARS_0_1",
  FemaleClubsEarrings: "DLC_MP_VWD_F_PEARS_1_0",
  FemaleDiamondsEarrings: "DLC_MP_VWD_F_PEARS_1_1",
  FemaleHeartsEarrings: "DLC_MP_VWD_F_PEARS_1_2",
  FemaleSpadesEarrings: "DLC_MP_VWD_F_PEARS_1_3",
  FemaleWhiteDiceEarrings: "DLC_MP_VWD_F_PEARS_2_0",
  FemaleRedDiceEarrings: "DLC_MP_VWD_F_PEARS_2_1",
  FemaleTanDiceEarrings: "DLC_MP_VWD_F_PEARS_2_2",
  FemaleGrayDiceEarrings: "DLC_MP_VWD_F_PEARS_2_3",
  FemaleBlackChipsEarrings: "DLC_MP_VWD_F_PEARS_3_0",
  FemaleYellowChipsEarrings: "DLC_MP_VWD_F_PEARS_3_1",
  FemaleRedChipsEarrings: "DLC_MP_VWD_F_PEARS_3_2",
  FemalePinkChipsEarrings: "DLC_MP_VWD_F_PEARS_3_3",
  MaleGoldFameOrShameMics: "DLC_MP_VWD_M_PEARS_0_0",
  MaleSilverFameOrShameMics: "DLC_MP_VWD_M_PEARS_0_1",
  MaleClubsEarrings: "DLC_MP_VWD_M_PEARS_1_0",
  MaleDiamondsEarrings: "DLC_MP_VWD_M_PEARS_1_1",
  MaleHeartsEarrings: "DLC_MP_VWD_M_PEARS_1_2",
  MaleSpadesEarrings: "DLC_MP_VWD_M_PEARS_1_3",
  MaleWhiteDiceEarrings: "DLC_MP_VWD_M_PEARS_2_0",
  MaleRedDiceEarrings: "DLC_MP_VWD_M_PEARS_2_1",
  MaleTanDiceEarrings: "DLC_MP_VWD_M_PEARS_2_2",
  MaleGrayDiceEarrings: "DLC_MP_VWD_M_PEARS_2_3",
  MaleBlackChipsEarrings: "DLC_MP_VWD_M_PEARS_3_0",
  MaleYellowChipsEarrings: "DLC_MP_VWD_M_PEARS_3_1",
  MaleRedChipsEarrings: "DLC_MP_VWD_M_PEARS_3_2",
  MalePinkChipsEarrings: "DLC_MP_VWD_M_PEARS_3_3",
  FemaleWhiteBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_0",
  FemaleYellowBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_1",
  FemaleTealBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_10",
  FemaleRedBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_11",
  FemaleSalmonBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_2",
  FemaleOrangeBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_3",
  FemalePurpleBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_4",
  FemalePinkBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_5",
  FemaleTurquoiseBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_6",
  FemaleBlueBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_7",
  FemaleBlackBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_8",
  FemaleGrayBeatOffEarphones: "DLC_MP_SUM2_F_PEARS_0_9",
  MaleGoldSnStudL: "DLC_MP_LUXE2_M_PEARS_0_0",
  MalePlatinumSnStudL: "DLC_MP_LUXE2_M_PEARS_0_1",
  MaleGoldSnStudR: "DLC_MP_LUXE2_M_PEARS_1_0",
  MalePlatinumSnStudR: "DLC_MP_LUXE2_M_PEARS_1_1",
  MaleGoldOnyxStudR: "DLC_MP_LUXE2_M_PEARS_10_0",
  MaleBlackOnyxStudR: "DLC_MP_LUXE2_M_PEARS_10_1",
  MalePlatinumOnyxStudR: "DLC_MP_LUXE2_M_PEARS_10_2",
  MaleGoldOnyxStuds: "DLC_MP_LUXE2_M_PEARS_11_0",
  MaleBlackOnyxStuds: "DLC_MP_LUXE2_M_PEARS_11_1",
  MalePlatinumOnyxStuds: "DLC_MP_LUXE2_M_PEARS_11_2",
  MalePlatinumSnBullionStudL: "DLC_MP_LUXE2_M_PEARS_13_0",
  MaleGoldSnBullionStudL: "DLC_MP_LUXE2_M_PEARS_13_1",
  MalePlatinumSnBullionStudR: "DLC_MP_LUXE2_M_PEARS_14_0",
  MaleGoldSnBullionStudR: "DLC_MP_LUXE2_M_PEARS_14_1",
  MalePlatinumSnBullionStuds: "DLC_MP_LUXE2_M_PEARS_15_0",
  MaleGoldSnBullionStuds: "DLC_MP_LUXE2_M_PEARS_15_1",
  MaleGoldSnStuds: "DLC_MP_LUXE2_M_PEARS_2_0",
  MalePlatinumSnStuds: "DLC_MP_LUXE2_M_PEARS_2_1",
  MaleSilverSkullStudL: "DLC_MP_LUXE2_M_PEARS_3_0",
  MaleGoldSkullStudL: "DLC_MP_LUXE2_M_PEARS_3_1",
  MaleBlackSkullStudL: "DLC_MP_LUXE2_M_PEARS_3_2",
  MalePlatinumSkullStudL: "DLC_MP_LUXE2_M_PEARS_3_3",
  MaleSilverSkullStudR: "DLC_MP_LUXE2_M_PEARS_4_0",
  MaleGoldSkullStudR: "DLC_MP_LUXE2_M_PEARS_4_1",
  MaleBlackSkullStudR: "DLC_MP_LUXE2_M_PEARS_4_2",
  MalePlatinumSkullStudR: "DLC_MP_LUXE2_M_PEARS_4_3",
  MaleSilverSkullStuds: "DLC_MP_LUXE2_M_PEARS_5_0",
  MaleGoldSkullStuds: "DLC_MP_LUXE2_M_PEARS_5_1",
  MaleBlackSkullStuds: "DLC_MP_LUXE2_M_PEARS_5_2",
  MalePlatinumSkullStuds: "DLC_MP_LUXE2_M_PEARS_5_3",
  MalePlatinumSpikeStudL: "DLC_MP_LUXE2_M_PEARS_6_0",
  MaleGoldSpikeStudL: "DLC_MP_LUXE2_M_PEARS_6_1",
  MalePlatinumSpikeStudR: "DLC_MP_LUXE2_M_PEARS_7_0",
  MaleGoldSpikeStudR: "DLC_MP_LUXE2_M_PEARS_7_1",
  MalePlatinumSpikeStuds: "DLC_MP_LUXE2_M_PEARS_8_0",
  MaleGoldSpikeStuds: "DLC_MP_LUXE2_M_PEARS_8_1",
  MaleGoldOnyxStudL: "DLC_MP_LUXE2_M_PEARS_9_0",
  MaleBlackOnyxStudL: "DLC_MP_LUXE2_M_PEARS_9_1",
  MalePlatinumOnyxStudL: "DLC_MP_LUXE2_M_PEARS_9_2",
  FemalePlatinumPendulums: "DLC_MP_LUXE_F_PEARS_0_0",
  FemaleGoldPendulums: "DLC_MP_LUXE_F_PEARS_1_0",
  FemaleGoldDiamondRounds: "DLC_MP_LUXE_F_PEARS_2_0",
  FemaleGoldDiamondDrops: "DLC_MP_LUXE_F_PEARS_3_0",
  FemalePlatinumDiamondDrops: "DLC_MP_LUXE_F_PEARS_3_1",
  FemaleBlackGoldDiamondDrops: "DLC_MP_LUXE_F_PEARS_3_2",
  FemaleGoldWaterfalls: "DLC_MP_LUXE_F_PEARS_4_0",
  FemalePlatinumWaterfalls: "DLC_MP_LUXE_F_PEARS_4_1",
  FemaleBlackGoldWaterfalls: "DLC_MP_LUXE_F_PEARS_4_2",
  FemaleGoldTotems: "DLC_MP_LUXE_F_PEARS_5_0",
  FemaleBlackGoldTotems: "DLC_MP_LUXE_F_PEARS_5_1",
  FemalePlatinumTotems: "DLC_MP_LUXE_F_PEARS_5_2",
  FemaleGoldDiamondChains: "DLC_MP_LUXE_F_PEARS_6_0",
  FemalePlatinumDiamondChains: "DLC_MP_LUXE_F_PEARS_6_1",
  FemaleBlackGoldDiamondChains: "DLC_MP_LUXE_F_PEARS_6_2",
  FemaleGoldEmeraldChains: "DLC_MP_LUXE_F_PEARS_7_0",
  FemalePlatinumEmeraldChains: "DLC_MP_LUXE_F_PEARS_7_1",
  FemaleBlackGoldEmeraldChains: "DLC_MP_LUXE_F_PEARS_7_2",
  FemaleGoldSunDrops: "DLC_MP_LUXE_F_PEARS_8_0",
  FemalePlatinumSunDrops: "DLC_MP_LUXE_F_PEARS_8_1",
  FemaleBlackGoldSunDrops: "DLC_MP_LUXE_F_PEARS_8_2",
  FemalePlatinumDiamondStuds: "DLC_MP_LUXE_F_PEARS_9_0",
  FemaleGoldDiamondStuds: "DLC_MP_LUXE_F_PEARS_9_1",
  FemaleBlackGoldDiamondStuds: "DLC_MP_LUXE_F_PEARS_9_2",
  MaleWhiteBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_0",
  MaleYellowBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_1",
  MaleTealBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_10",
  MaleRedBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_11",
  MaleSalmonBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_2",
  MaleOrangeBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_3",
  MalePurpleBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_4",
  MalePinkBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_5",
  MaleTurquoiseBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_6",
  MaleBlueBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_7",
  MaleBlackBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_8",
  MaleGrayBeatOffEarphones: "DLC_MP_SUM2_M_PEARS_0_9",
});

export type EarringsItemKey = Brand<string, "EarringsItemKey">;

export type EarringsItem = {
  key: EarringsItemKey;

  customName?: string | null;
};

export type EarringsItemInfo = {
  key: EarringsItemKey;
  ped: string;
  componentId: number;
  drawableId: number;
  textureId: number;
  name: string;
  price: number;
  restrictionTags: string[] | null;
};

export const earrings = registerItems(Object.values(EARRINGS_ITEMS));

/**
 * Type guards for earrings
 */
export function isItemKeyEarrings(key: string): key is EarringsItemKey {
  return earrings.has(key as EarringsItemKey);
}

export function isItemEarrings(item: Item): item is EarringsItem {
  return isItemKeyEarrings(item.key);
}
