import { makeKeys } from "@shared/utility/make-keys";
import { Scrap } from "@shared/modules/items/registry/materials/scrap.items";
import { WeaponComponent } from "@shared/modules/items/registry/weapon-components/weapon-component.items";
import { getItemName } from "@shared/modules/items/lib";
import { WeaponItemKey } from "@shared/modules/items/registry/weapons/weapon.items";
import { Metal } from "@shared/modules/items/registry/materials/metal.items";
import { ItemGrade } from "@shared/modules/items";
import { registerBlueprint } from "../blueprints.registry";

export const WeaponComponentBlueprint = makeKeys<WeaponComponentBlueprintKey>()({
  COMBATSHOTGUN_CS: "combatshotgun_cs",
  SNIPERRIFLE_CS: "sniperrifle_cs",
  VINTAGEPISTOL_CS: "vintagepistol_cs",
  COMBATPDW_CS: "combatpdw_cs",
  HEAVYSNIPERMK2_CS: "heavysnipermk2_cs",
  HEAVYSNIPER_CS: "heavysniper_cs",
  MICROSMG_CS: "microsmg_cs",
  PISTOL_CS: "pistol_cs",
  PISTOLXM3_CS: "pistolxm3_cs",
  PUMPSHOTGUN_CS: "pumpshotgun_cs",
  APPISTOL_CS: "appistol_cs",
  CERAMICPISTOL_CS: "ceramicpistol_cs",
  SMG_CS: "smg_cs",
  ASSAULTRIFLEMK2_CS: "assaultriflemk2_cs",
  HEAVYSHOTGUN_CS: "heavyshotgun_cs",
  GRENADELAUNCHERSMOKE_CS: "grenadelaunchersmoke_cs",
  PUMPSHOTGUNMK2_CS: "pumpshotgunmk2_cs",
  COMBATPISTOL_CS: "combatpistol_cs",
  GUSENBERG_CS: "gusenberg_cs",
  COMPACTRIFLE_CS: "compactrifle_cs",
  MARKSMANRIFLEMK2_CS: "marksmanriflemk2_cs",
  RAILGUN_CS: "railgun_cs",
  PRECISIONRIFLE_CS: "precisionrifle_cs",
  SMGMK2_CS: "smgmk2_cs",
  BULLPUPRIFLE_CS: "bullpuprifle_cs",
  COMBATMG_CS: "combatmg_cs",
  CARBINERIFLE_CS: "carbinerifle_cs",
  BULLPUPRIFLEMK2_CS: "bullpupriflemk2_cs",
  SNSPISTOLMK2_CS: "snspistolmk2_cs",
  FLASHLIGHT_CS: "flashlight_cs",
  SPECIALCARBINEMK2_CS: "specialcarbinemk2_cs",
  DOUBLEACTION_CS: "doubleaction_cs",
  PISTOL50_CS: "pistol50_cs",
  MG_CS: "mg_cs",
  MILITARYRIFLE_CS: "militaryrifle_cs",
  BULLPUPSHOTGUN_CS: "bullpupshotgun_cs",
  GRENADELAUNCHER_CS: "grenadelauncher_cs",
  MUSKET_CS: "musket_cs",
  ADVANCEDRIFLE_CS: "advancedrifle_cs",
  RAYPISTOL_CS: "raypistol_cs",
  MINISMG_CS: "minismg_cs",
  SNSPISTOL_CS: "snspistol_cs",
  PISTOLMK2_CS: "pistolmk2_cs",
  ASSAULTRIFLE_CS: "assaultrifle_cs",
  SPECIALCARBINE_CS: "specialcarbine_cs",
  MARKSMANRIFLE_CS: "marksmanrifle_cs",
  HEAVYRIFLE_CS: "heavyrifle_cs",
  REVOLVERMK2_CS: "revolvermk2_cs",
  TACTICALRIFLE_CS: "tacticalrifle_cs",
  HEAVYPISTOL_CS: "heavypistol_cs",
  MACHINEPISTOL_CS: "machinepistol_cs",
  COMBATMGMK2_CS: "combatmgmk2_cs",
  ASSAULTSHOTGUN_CS: "assaultshotgun_cs",
  ASSAULTSMG_CS: "assaultsmg_cs",
  CARBINERIFLEMK2_CS: "carbineriflemk2_cs",
  RAILGUNXM3_CS: "railgunxm3_cs",
});

export type WeaponComponentBlueprintKey = Brand<string, "WeaponComponentBlueprintKey">;

Object.entries({
  [WeaponComponentBlueprint.COMBATSHOTGUN_CS]: [
    WeaponComponent.COMBATSHOTGUN_FLASH,
    WeaponComponent.COMBATSHOTGUN_SUPP,
    WeaponComponent.COMBATSHOTGUN_SHELL,
  ],
  [WeaponComponentBlueprint.SNIPERRIFLE_CS]: [
    WeaponComponent.SNIPERRIFLE_SUPP,
    WeaponComponent.SNIPERRIFLE_SCOPE_MAX,
    WeaponComponent.SNIPERRIFLE_SCOPE_LRG,
  ],
  [WeaponComponentBlueprint.VINTAGEPISTOL_CS]: [
    WeaponComponent.VINTAGEPISTOL_CLIP2,
    WeaponComponent.VINTAGEPISTOL_CLIP1,
    WeaponComponent.VINTAGEPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.COMBATPDW_CS]: [
    WeaponComponent.COMBATPDW_GRIP,
    WeaponComponent.COMBATPDW_CLIP2,
    WeaponComponent.COMBATPDW_CLIP1,
    WeaponComponent.COMBATPDW_CLIP_DRM,
    WeaponComponent.COMBATPDW_FLASH,
    WeaponComponent.COMBATPDW_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.HEAVYSNIPERMK2_CS]: [
    WeaponComponent.HEAVYSNIPERMK2_CLIP_INC,
    WeaponComponent.HEAVYSNIPERMK2_BARR2,
    WeaponComponent.HEAVYSNIPERMK2_CLIP2,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_TH,
    WeaponComponent.HEAVYSNIPERMK2_CLIP_FMJ,
    WeaponComponent.HEAVYSNIPERMK2_MUZZ8,
    WeaponComponent.HEAVYSNIPERMK2_MUZZ9,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_LRG2,
    WeaponComponent.HEAVYSNIPERMK2_CLIP_EX,
    WeaponComponent.HEAVYSNIPERMK2_BARR,
    WeaponComponent.HEAVYSNIPERMK2_SUPP,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_NV,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_MAX,
    WeaponComponent.HEAVYSNIPERMK2_CLIP_AP,
    WeaponComponent.HEAVYSNIPERMK2_CLIP1,
  ],
  [WeaponComponentBlueprint.HEAVYSNIPER_CS]: [
    WeaponComponent.HEAVYSNIPER_SCOPE_MAX,
    WeaponComponent.HEAVYSNIPER_SCOPE_LRG,
  ],
  [WeaponComponentBlueprint.MICROSMG_CS]: [
    WeaponComponent.MICROSMG_CLIP2,
    WeaponComponent.MICROSMG_FLASH,
    WeaponComponent.MICROSMG_SCOPE_MAC,
    WeaponComponent.MICROSMG_SUPP,
    WeaponComponent.MICROSMG_CLIP1,
  ],
  [WeaponComponentBlueprint.PISTOL_CS]: [
    WeaponComponent.PISTOL_FLASH,
    WeaponComponent.PISTOL_SUPP,
    WeaponComponent.PISTOL_CLIP2,
    WeaponComponent.PISTOL_CLIP1,
  ],
  [WeaponComponentBlueprint.PISTOLXM3_CS]: [
    WeaponComponent.PISTOLXM3_CLIP1,
    WeaponComponent.PISTOLXM3_SUPP,
  ],
  [WeaponComponentBlueprint.PUMPSHOTGUN_CS]: [
    WeaponComponent.PUMPSHOTGUN_FLASH,
    WeaponComponent.PUMPSHOTGUN_SUPP,
  ],
  [WeaponComponentBlueprint.APPISTOL_CS]: [
    WeaponComponent.APPISTOL_CLIP2,
    WeaponComponent.APPISTOL_CLIP1,
    WeaponComponent.APPISTOL_FLASH,
    WeaponComponent.APPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.CERAMICPISTOL_CS]: [
    WeaponComponent.CERAMICPISTOL_CLIP1,
    WeaponComponent.CERAMICPISTOL_CLIP2,
    WeaponComponent.CERAMICPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.SMG_CS]: [
    WeaponComponent.SMG_CLIP1,
    WeaponComponent.SMG_CLIP2,
    WeaponComponent.SMG_SCOPE_MAC,
    WeaponComponent.SMG_CLIP_DRM,
    WeaponComponent.SMG_FLASH,
    WeaponComponent.SMG_SUPP,
  ],
  [WeaponComponentBlueprint.ASSAULTRIFLEMK2_CS]: [
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ5,
    WeaponComponent.ASSAULTRIFLEMK2_SCOPE_MAC2,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ6,
    WeaponComponent.ASSAULTRIFLEMK2_HOLO,
    WeaponComponent.ASSAULTRIFLEMK2_BARR,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ7,
    WeaponComponent.ASSAULTRIFLEMK2_BARR2,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_FMJ,
    WeaponComponent.ASSAULTRIFLEMK2_FLASH,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP1,
    WeaponComponent.ASSAULTRIFLEMK2_GRIP,
    WeaponComponent.ASSAULTRIFLEMK2_SUPP,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_AP,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ1,
    WeaponComponent.ASSAULTRIFLEMK2_SCOPE_MED2,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ2,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP2,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ3,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ4,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_TR,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_INC,
  ],
  [WeaponComponentBlueprint.HEAVYSHOTGUN_CS]: [
    WeaponComponent.HEAVYSHOTGUN_GRIP,
    WeaponComponent.HEAVYSHOTGUN_CLIP1,
    WeaponComponent.HEAVYSHOTGUN_FLASH,
    WeaponComponent.HEAVYSHOTGUN_CLIP_DRM,
    WeaponComponent.HEAVYSHOTGUN_CLIP2,
    WeaponComponent.HEAVYSHOTGUN_SUPP,
  ],
  [WeaponComponentBlueprint.GRENADELAUNCHERSMOKE_CS]: [
    WeaponComponent.GRENADELAUNCHERSMOKE_GRIP,
    WeaponComponent.GRENADELAUNCHERSMOKE_FLASH,
    WeaponComponent.GRENADELAUNCHERSMOKE_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.PUMPSHOTGUNMK2_CS]: [
    WeaponComponent.PUMPSHOTGUNMK2_SCOPE_MAC2,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_EX,
    WeaponComponent.PUMPSHOTGUNMK2_SCOPE_SML2,
    WeaponComponent.PUMPSHOTGUNMK2_HOLO,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_AP,
    WeaponComponent.PUMPSHOTGUNMK2_MUZZ8,
    WeaponComponent.PUMPSHOTGUNMK2_FLASH,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_INC,
    WeaponComponent.PUMPSHOTGUNMK2_SUPP,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_HP,
  ],
  [WeaponComponentBlueprint.COMBATPISTOL_CS]: [
    WeaponComponent.COMBATPISTOL_CLIP1,
    WeaponComponent.COMBATPISTOL_FLASH,
    WeaponComponent.COMBATPISTOL_SUPP,
    WeaponComponent.COMBATPISTOL_CLIP2,
  ],
  [WeaponComponentBlueprint.GUSENBERG_CS]: [
    WeaponComponent.GUSENBERG_CLIP1,
    WeaponComponent.GUSENBERG_CLIP2,
  ],
  [WeaponComponentBlueprint.COMPACTRIFLE_CS]: [
    WeaponComponent.COMPACTRIFLE_CLIP1,
    WeaponComponent.COMPACTRIFLE_CLIP2,
    WeaponComponent.COMPACTRIFLE_CLIP_DRM,
  ],
  [WeaponComponentBlueprint.MARKSMANRIFLEMK2_CS]: [
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ5,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ6,
    WeaponComponent.MARKSMANRIFLEMK2_BARR,
    WeaponComponent.MARKSMANRIFLEMK2_HOLO,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ7,
    WeaponComponent.MARKSMANRIFLEMK2_SCOPE_LRG2,
    WeaponComponent.MARKSMANRIFLEMK2_BARR2,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_INC,
    WeaponComponent.MARKSMANRIFLEMK2_FLASH,
    WeaponComponent.MARKSMANRIFLEMK2_SUPP,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP1,
    WeaponComponent.MARKSMANRIFLEMK2_GRIP,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ1,
    WeaponComponent.MARKSMANRIFLEMK2_SCOPE_MED2,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ2,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_TR,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ3,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_FMJ,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP2,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ4,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_AP,
  ],
  [WeaponComponentBlueprint.RAILGUN_CS]: [WeaponComponent.RAILGUN_CLIP1],
  [WeaponComponentBlueprint.PRECISIONRIFLE_CS]: [WeaponComponent.PRECISIONRIFLE_CLIP1],
  [WeaponComponentBlueprint.SMGMK2_CS]: [
    WeaponComponent.SMGMK2_MUZZ5,
    WeaponComponent.SMGMK2_CLIP_FMJ,
    WeaponComponent.SMGMK2_MUZZ6,
    WeaponComponent.SMGMK2_CLIP_HP,
    WeaponComponent.SMGMK2_SCOPE_SML2,
    WeaponComponent.SMGMK2_CLIP1,
    WeaponComponent.SMGMK2_MUZZ7,
    WeaponComponent.SMGMK2_FLASH,
    WeaponComponent.SMGMK2_CLIP_TR,
    WeaponComponent.SMGMK2_HOLO,
    WeaponComponent.SMGMK2_BARR2,
    WeaponComponent.SMGMK2_CLIP2,
    WeaponComponent.SMGMK2_MUZZ1,
    WeaponComponent.SMGMK2_SUPP,
    WeaponComponent.SMGMK2_MUZZ2,
    WeaponComponent.SMGMK2_BARR,
    WeaponComponent.SMGMK2_CLIP_INC,
    WeaponComponent.SMGMK2_MUZZ3,
    WeaponComponent.SMGMK2_SCOPE_MAC2,
    WeaponComponent.SMGMK2_MUZZ4,
  ],
  [WeaponComponentBlueprint.BULLPUPRIFLE_CS]: [
    WeaponComponent.BULLPUPRIFLE_GRIP,
    WeaponComponent.BULLPUPRIFLE_FLASH,
    WeaponComponent.BULLPUPRIFLE_SUPP,
    WeaponComponent.BULLPUPRIFLE_SCOPE_SML,
    WeaponComponent.BULLPUPRIFLE_CLIP2,
    WeaponComponent.BULLPUPRIFLE_CLIP1,
  ],
  [WeaponComponentBlueprint.COMBATMG_CS]: [
    WeaponComponent.COMBATMG_GRIP,
    WeaponComponent.COMBATMG_SCOPE_LRG,
    WeaponComponent.COMBATMG_CLIP2,
    WeaponComponent.COMBATMG_CLIP1,
  ],
  [WeaponComponentBlueprint.CARBINERIFLE_CS]: [
    WeaponComponent.CARBINERIFLE_GRIP,
    WeaponComponent.CARBINERIFLE_FLASH,
    WeaponComponent.CARBINERIFLE_SUPP,
    WeaponComponent.CARBINERIFLE_CLIP2,
    WeaponComponent.CARBINERIFLE_CLIP1,
    WeaponComponent.CARBINERIFLE_SCOPE_LRG,
    WeaponComponent.CARBINERIFLE_CLIP_BOX,
  ],
  [WeaponComponentBlueprint.BULLPUPRIFLEMK2_CS]: [
    WeaponComponent.BULLPUPRIFLEMK2_CLIP1,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ5,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ6,
    WeaponComponent.BULLPUPRIFLEMK2_BARR2,
    WeaponComponent.BULLPUPRIFLEMK2_SCOPE_SML2,
    WeaponComponent.BULLPUPRIFLEMK2_HOLO,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_FMJ,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ7,
    WeaponComponent.BULLPUPRIFLEMK2_BARR,
    WeaponComponent.BULLPUPRIFLEMK2_FLASH,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_TR,
    WeaponComponent.BULLPUPRIFLEMK2_SUPP,
    WeaponComponent.BULLPUPRIFLEMK2_GRIP,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_INC,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ1,
    WeaponComponent.BULLPUPRIFLEMK2_SCOPE_MAC2,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ2,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ3,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ4,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP2,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_AP,
  ],
  [WeaponComponentBlueprint.SNSPISTOLMK2_CS]: [
    WeaponComponent.SNSPISTOLMK2_CLIP1,
    WeaponComponent.SNSPISTOLMK2_SCOPE_PI,
    WeaponComponent.SNSPISTOLMK2_FLASH,
    WeaponComponent.SNSPISTOLMK2_SUPP,
    WeaponComponent.SNSPISTOLMK2_CLIP_HP,
    WeaponComponent.SNSPISTOLMK2_CLIP_TR,
    WeaponComponent.SNSPISTOLMK2_COMP,
    WeaponComponent.SNSPISTOLMK2_CLIP_FMJ,
    WeaponComponent.SNSPISTOLMK2_CLIP2,
    WeaponComponent.SNSPISTOLMK2_CLIP_INC,
  ],
  [WeaponComponentBlueprint.FLASHLIGHT_CS]: [WeaponComponent.FLASHLIGHT_FLASH],
  [WeaponComponentBlueprint.SPECIALCARBINEMK2_CS]: [
    WeaponComponent.SPECIALCARBINEMK2_MUZZ5,
    WeaponComponent.SPECIALCARBINEMK2_SCOPE_MAC2,
    WeaponComponent.SPECIALCARBINEMK2_CLIP1,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ6,
    WeaponComponent.SPECIALCARBINEMK2_HOLO,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ7,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_FMJ,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_AP,
    WeaponComponent.SPECIALCARBINEMK2_FLASH,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_TR,
    WeaponComponent.SPECIALCARBINEMK2_GRIP,
    WeaponComponent.SPECIALCARBINEMK2_SUPP,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ1,
    WeaponComponent.SPECIALCARBINEMK2_SCOPE_MED2,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ2,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_INC,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ3,
    WeaponComponent.SPECIALCARBINEMK2_CLIP2,
    WeaponComponent.SPECIALCARBINEMK2_BARR,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ4,
    WeaponComponent.SPECIALCARBINEMK2_BARR2,
  ],
  [WeaponComponentBlueprint.DOUBLEACTION_CS]: [WeaponComponent.DOUBLEACTION_CLIP1],
  [WeaponComponentBlueprint.PISTOL50_CS]: [
    WeaponComponent.PISTOL50_CLIP1,
    WeaponComponent.PISTOL50_FLASH,
    WeaponComponent.PISTOL50_SUPP,
    WeaponComponent.PISTOL50_CLIP2,
  ],
  [WeaponComponentBlueprint.MG_CS]: [
    WeaponComponent.MG_SCOPE_SML,
    WeaponComponent.MG_CLIP2,
    WeaponComponent.MG_CLIP1,
  ],
  [WeaponComponentBlueprint.MILITARYRIFLE_CS]: [
    WeaponComponent.MILITARYRIFLE_CLIP1,
    WeaponComponent.MILITARYRIFLE_CLIP2,
    WeaponComponent.MILITARYRIFLE_MRFL_SIGHT,
    WeaponComponent.MILITARYRIFLE_FLASH,
    WeaponComponent.MILITARYRIFLE_SUPP,
    WeaponComponent.MILITARYRIFLE_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.BULLPUPSHOTGUN_CS]: [
    WeaponComponent.BULLPUPSHOTGUN_GRIP,
    WeaponComponent.BULLPUPSHOTGUN_FLASH,
    WeaponComponent.BULLPUPSHOTGUN_SUPP,
  ],
  [WeaponComponentBlueprint.GRENADELAUNCHER_CS]: [
    WeaponComponent.GRENADELAUNCHER_GRIP,
    WeaponComponent.GRENADELAUNCHER_FLASH,
    WeaponComponent.GRENADELAUNCHER_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.MUSKET_CS]: [WeaponComponent.MUSKET_CLIP1],
  [WeaponComponentBlueprint.ADVANCEDRIFLE_CS]: [
    WeaponComponent.ADVANCEDRIFLE_FLASH,
    WeaponComponent.ADVANCEDRIFLE_SUPP,
    WeaponComponent.ADVANCEDRIFLE_CLIP2,
    WeaponComponent.ADVANCEDRIFLE_SCOPE_SML,
    WeaponComponent.ADVANCEDRIFLE_CLIP1,
  ],
  [WeaponComponentBlueprint.RAYPISTOL_CS]: [WeaponComponent.RAYPISTOL_VAR_RAY18],
  [WeaponComponentBlueprint.MINISMG_CS]: [
    WeaponComponent.MINISMG_CLIP1,
    WeaponComponent.MINISMG_CLIP2,
  ],
  [WeaponComponentBlueprint.SNSPISTOL_CS]: [
    WeaponComponent.SNSPISTOL_CLIP2,
    WeaponComponent.SNSPISTOL_CLIP1,
  ],
  [WeaponComponentBlueprint.PISTOLMK2_CS]: [
    WeaponComponent.PISTOLMK2_COMP,
    WeaponComponent.PISTOLMK2_CLIP_TR,
    WeaponComponent.PISTOLMK2_CLIP_INC,
    WeaponComponent.PISTOLMK2_FLASH,
    WeaponComponent.PISTOLMK2_CLIP_FMJ,
    WeaponComponent.PISTOLMK2_CLIP2,
    WeaponComponent.PISTOLMK2_SUPP,
    WeaponComponent.PISTOLMK2_CLIP_HP,
    WeaponComponent.PISTOLMK2_SCOPE_PI,
    WeaponComponent.PISTOLMK2_CLIP1,
  ],
  [WeaponComponentBlueprint.ASSAULTRIFLE_CS]: [
    WeaponComponent.ASSAULTRIFLE_GRIP,
    WeaponComponent.ASSAULTRIFLE_FLASH,
    WeaponComponent.ASSAULTRIFLE_SCOPE_MAC,
    WeaponComponent.ASSAULTRIFLE_SUPP,
    WeaponComponent.ASSAULTRIFLE_CLIP2,
    WeaponComponent.ASSAULTRIFLE_CLIP1,
    WeaponComponent.ASSAULTRIFLE_CLIP_DRM,
  ],
  [WeaponComponentBlueprint.SPECIALCARBINE_CS]: [
    WeaponComponent.SPECIALCARBINE_GRIP,
    WeaponComponent.SPECIALCARBINE_CLIP_DRM,
    WeaponComponent.SPECIALCARBINE_FLASH,
    WeaponComponent.SPECIALCARBINE_CLIP2,
    WeaponComponent.SPECIALCARBINE_SCOPE_LRG,
    WeaponComponent.SPECIALCARBINE_SUPP,
    WeaponComponent.SPECIALCARBINE_CLIP1,
  ],
  [WeaponComponentBlueprint.MARKSMANRIFLE_CS]: [
    WeaponComponent.MARKSMANRIFLE_GRIP,
    WeaponComponent.MARKSMANRIFLE_SCOPE_LRG,
    WeaponComponent.MARKSMANRIFLE_FLASH,
    WeaponComponent.MARKSMANRIFLE_SUPP,
    WeaponComponent.MARKSMANRIFLE_CLIP2,
    WeaponComponent.MARKSMANRIFLE_CLIP1,
  ],
  [WeaponComponentBlueprint.HEAVYRIFLE_CS]: [
    WeaponComponent.HEAVYRIFLE_GRIP,
    WeaponComponent.HEAVYRIFLE_CLIP1,
    WeaponComponent.HEAVYRIFLE_CLIP2,
    WeaponComponent.HEAVYRIFLE_FLASH,
    WeaponComponent.HEAVYRIFLE_SUPP,
    WeaponComponent.HEAVYRIFLE_SCOPE_LRG,
    WeaponComponent.HEAVYRIFLE_HVYRFLE_SIG,
  ],
  [WeaponComponentBlueprint.REVOLVERMK2_CS]: [
    WeaponComponent.REVOLVERMK2_CLIP_INC,
    WeaponComponent.REVOLVERMK2_SCOPE_MAC2,
    WeaponComponent.REVOLVERMK2_CLIP_FMJ,
    WeaponComponent.REVOLVERMK2_CLIP_HP,
    WeaponComponent.REVOLVERMK2_COMP,
    WeaponComponent.REVOLVERMK2_FLASH,
    WeaponComponent.REVOLVERMK2_HOLO,
    WeaponComponent.REVOLVERMK2_CLIP1_RV,
    WeaponComponent.REVOLVERMK2_CLIP_TR,
  ],
  [WeaponComponentBlueprint.TACTICALRIFLE_CS]: [
    WeaponComponent.TACTICALRIFLE_GRIP,
    WeaponComponent.TACTICALRIFLE_CLIP1,
    WeaponComponent.TACTICALRIFLE_CLIP2,
    WeaponComponent.TACTICALRIFLE_FLASH,
    WeaponComponent.TACTICALRIFLE_SUPP,
  ],
  [WeaponComponentBlueprint.HEAVYPISTOL_CS]: [
    WeaponComponent.HEAVYPISTOL_CLIP1,
    WeaponComponent.HEAVYPISTOL_FLASH,
    WeaponComponent.HEAVYPISTOL_CLIP2,
    WeaponComponent.HEAVYPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.MACHINEPISTOL_CS]: [
    WeaponComponent.MACHINEPISTOL_CLIP1,
    WeaponComponent.MACHINEPISTOL_CLIP_DRM,
    WeaponComponent.MACHINEPISTOL_CLIP2,
    WeaponComponent.MACHINEPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.COMBATMGMK2_CS]: [
    WeaponComponent.COMBATMGMK2_MUZZ5,
    WeaponComponent.COMBATMGMK2_CLIP2,
    WeaponComponent.COMBATMGMK2_CLIP_AP,
    WeaponComponent.COMBATMGMK2_MUZZ6,
    WeaponComponent.COMBATMGMK2_SCOPE_SML2,
    WeaponComponent.COMBATMGMK2_HOLO,
    WeaponComponent.COMBATMGMK2_CLIP1,
    WeaponComponent.COMBATMGMK2_MUZZ7,
    WeaponComponent.COMBATMGMK2_CLIP_FMJ,
    WeaponComponent.COMBATMGMK2_GRIP,
    WeaponComponent.COMBATMGMK2_BARR2,
    WeaponComponent.COMBATMGMK2_MUZZ1,
    WeaponComponent.COMBATMGMK2_CLIP_INC,
    WeaponComponent.COMBATMGMK2_BARR,
    WeaponComponent.COMBATMGMK2_SCOPE_MED2,
    WeaponComponent.COMBATMGMK2_MUZZ2,
    WeaponComponent.COMBATMGMK2_MUZZ3,
    WeaponComponent.COMBATMGMK2_MUZZ4,
    WeaponComponent.COMBATMGMK2_CLIP_TR,
  ],
  [WeaponComponentBlueprint.ASSAULTSHOTGUN_CS]: [
    WeaponComponent.ASSAULTSHOTGUN_GRIP,
    WeaponComponent.ASSAULTSHOTGUN_FLASH,
    WeaponComponent.ASSAULTSHOTGUN_SUPP,
    WeaponComponent.ASSAULTSHOTGUN_CLIP2,
    WeaponComponent.ASSAULTSHOTGUN_CLIP1,
  ],
  [WeaponComponentBlueprint.ASSAULTSMG_CS]: [
    WeaponComponent.ASSAULTSMG_FLASH,
    WeaponComponent.ASSAULTSMG_SCOPE_MAC,
    WeaponComponent.ASSAULTSMG_SUPP,
  ],
  [WeaponComponentBlueprint.CARBINERIFLEMK2_CS]: [
    WeaponComponent.CARBINERIFLEMK2_MUZZ5,
    WeaponComponent.CARBINERIFLEMK2_SCOPE_MAC2,
    WeaponComponent.CARBINERIFLEMK2_CLIP_TR,
    WeaponComponent.CARBINERIFLEMK2_CLIP_AP,
    WeaponComponent.CARBINERIFLEMK2_MUZZ6,
    WeaponComponent.CARBINERIFLEMK2_CLIP_INC,
    WeaponComponent.CARBINERIFLEMK2_HOLO,
    WeaponComponent.CARBINERIFLEMK2_CLIP_FMJ,
    WeaponComponent.CARBINERIFLEMK2_CLIP1,
    WeaponComponent.CARBINERIFLEMK2_MUZZ7,
    WeaponComponent.CARBINERIFLEMK2_CLIP2,
    WeaponComponent.CARBINERIFLEMK2_FLASH,
    WeaponComponent.CARBINERIFLEMK2_BARR,
    WeaponComponent.CARBINERIFLEMK2_SUPP,
    WeaponComponent.CARBINERIFLEMK2_BARR2,
    WeaponComponent.CARBINERIFLEMK2_GRIP,
    WeaponComponent.CARBINERIFLEMK2_MUZZ1,
    WeaponComponent.CARBINERIFLEMK2_SCOPE_MED2,
    WeaponComponent.CARBINERIFLEMK2_MUZZ2,
    WeaponComponent.CARBINERIFLEMK2_MUZZ3,
    WeaponComponent.CARBINERIFLEMK2_MUZZ4,
  ],
  [WeaponComponentBlueprint.RAILGUNXM3_CS]: [WeaponComponent.RAILGUNXM3_CLIP1],
}).forEach(([key, components]) => {
  const weaponItemKey = key.replace("_cs", "") as string as WeaponItemKey;
  registerBlueprint({
    key,
    name: `${getItemName(weaponItemKey)} components blueprint`,
    description: `Lets you craft weapon components for ${getItemName(weaponItemKey)}`,
    recipes: components.map((component) => ({
      key: component,
      durationSeconds: 2,
      item: {
        key: component,
      },
      parts: [
        {
          key: Metal.METAL,
          grade: ItemGrade.COMMON,
          amount: 5 * (+component[component.length - 1] || 1),
        },
        {
          key: Scrap.SCRAP,
          grade: ItemGrade.COMMON,
          amount: 5 * (+component[component.length - 1] || 1),
        },
      ],
    })),
  });
});
