import { makeKeys } from "@shared/utility/make-keys";
import { Scrap } from "@shared/modules/items/registry/materials/scrap.items";
import { WeaponComponent } from "@shared/modules/items/registry/weapon-components/weapon-component.items";
import { getItemName } from "@shared/modules/items/lib";
import { WeaponItemKey } from "@shared/modules/items/registry/weapons/weapon.items";
import { Metal } from "@shared/modules/items/registry/materials/metal.items";
import { registerBlueprint } from "../blueprints.registry";

export const WeaponComponentBlueprint = makeKeys<WeaponComponentBlueprintKey>()({
  COMBATSHOTGUN: "combatshotgun_cs",
  SNIPERRIFLE: "sniperrifle_cs",
  VINTAGEPISTOL: "vintagepistol_cs",
  COMBATPDW: "combatpdw_cs",
  HEAVYSNIPERMK2: "heavysnipermk2_cs",
  HEAVYSNIPER: "heavysniper_cs",
  MICROSMG: "microsmg_cs",
  PISTOL: "pistol_cs",
  PISTOLXM3: "pistolxm3_cs",
  PUMPSHOTGUN: "pumpshotgun_cs",
  APPISTOL: "appistol_cs",
  CERAMICPISTOL: "ceramicpistol_cs",
  SMG: "smg_cs",
  ASSAULTRIFLEMK2: "assaultriflemk2_cs",
  HEAVYSHOTGUN: "heavyshotgun_cs",
  GRENADELAUNCHERSMOKE: "grenadelaunchersmoke_cs",
  PUMPSHOTGUNMK2: "pumpshotgunmk2_cs",
  COMBATPISTOL: "combatpistol_cs",
  GUSENBERG: "gusenberg_cs",
  COMPACTRIFLE: "compactrifle_cs",
  MARKSMANRIFLEMK2: "marksmanriflemk2_cs",
  RAILGUN: "railgun_cs",
  PRECISIONRIFLE: "precisionrifle_cs",
  SMGMK2: "smgmk2_cs",
  BULLPUPRIFLE: "bullpuprifle_cs",
  FIREWORK: "firework_cs",
  COMBATMG: "combatmg_cs",
  CARBINERIFLE: "carbinerifle_cs",
  BULLPUPRIFLEMK2: "bullpupriflemk2_cs",
  SNSPISTOLMK2: "snspistolmk2_cs",
  FLASHLIGHT: "flashlight_cs",
  SPECIALCARBINEMK2: "specialcarbinemk2_cs",
  DOUBLEACTION: "doubleaction_cs",
  PISTOL50: "pistol50_cs",
  MG: "mg_cs",
  MILITARYRIFLE: "militaryrifle_cs",
  BULLPUPSHOTGUN: "bullpupshotgun_cs",
  GRENADELAUNCHER: "grenadelauncher_cs",
  MUSKET: "musket_cs",
  ADVANCEDRIFLE: "advancedrifle_cs",
  RAYPISTOL: "raypistol_cs",
  MINISMG: "minismg_cs",
  SNSPISTOL: "snspistol_cs",
  PISTOLMK2: "pistolmk2_cs",
  ASSAULTRIFLE: "assaultrifle_cs",
  SPECIALCARBINE: "specialcarbine_cs",
  MARKSMANRIFLE: "marksmanrifle_cs",
  HEAVYRIFLE: "heavyrifle_cs",
  REVOLVERMK2: "revolvermk2_cs",
  TACTICALRIFLE: "tacticalrifle_cs",
  HEAVYPISTOL: "heavypistol_cs",
  MACHINEPISTOL: "machinepistol_cs",
  COMBATMGMK2: "combatmgmk2_cs",
  ASSAULTSHOTGUN: "assaultshotgun_cs",
  ASSAULTSMG: "assaultsmg_cs",
  CARBINERIFLEMK2: "carbineriflemk2_cs",
  RAILGUNXM3: "railgunxm3_cs",
});

export type WeaponComponentBlueprintKey = Brand<string, "WeaponComponentBlueprintKey">;

Object.entries({
  [WeaponComponentBlueprint.COMBATSHOTGUN]: [
    WeaponComponent.COMBATSHOTGUN_FLASH,
    WeaponComponent.COMBATSHOTGUN_SUPP,
    WeaponComponent.COMBATSHOTGUN_SHELL,
  ],
  [WeaponComponentBlueprint.SNIPERRIFLE]: [
    WeaponComponent.SNIPERRIFLE_SUPP,
    WeaponComponent.SNIPERRIFLE_SCOPE_MAX,
    WeaponComponent.SNIPERRIFLE_SCOPE_LRG,
  ],
  [WeaponComponentBlueprint.VINTAGEPISTOL]: [
    WeaponComponent.VINTAGEPISTOL_CLIP2,
    WeaponComponent.VINTAGEPISTOL_CLIP1,
    WeaponComponent.VINTAGEPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.COMBATPDW]: [
    WeaponComponent.COMBATPDW_GRIP,
    WeaponComponent.COMBATPDW_CLIP2,
    WeaponComponent.COMBATPDW_CLIP1,
    WeaponComponent.COMBATPDW_CLIP_DRM,
    WeaponComponent.COMBATPDW_FLASH,
    WeaponComponent.COMBATPDW_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.HEAVYSNIPERMK2]: [
    WeaponComponent.HEAVYSNIPERMK2_CLIP_INC,
    WeaponComponent.HEAVYSNIPERMK2_BARR2,
    WeaponComponent.HEAVYSNIPERMK2_CLIP2,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_TH,
    WeaponComponent.HEAVYSNIPERMK2_CLIP_FMJ,
    WeaponComponent.HEAVYSNIPERMK2_MUZZ8,
    WeaponComponent.HEAVYSNIPERMK2_MUZZ9,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_LRG2,
    WeaponComponent.HEAVYSNIPERMK2_CLIP_EX,
    WeaponComponent.HEAVYSNIPERMK2_BARR,
    WeaponComponent.HEAVYSNIPERMK2_SUPP,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_NV,
    WeaponComponent.HEAVYSNIPERMK2_SCOPE_MAX,
    WeaponComponent.HEAVYSNIPERMK2_CLIP_AP,
    WeaponComponent.HEAVYSNIPERMK2_CLIP1,
  ],
  [WeaponComponentBlueprint.HEAVYSNIPER]: [
    WeaponComponent.HEAVYSNIPER_SCOPE_MAX,
    WeaponComponent.HEAVYSNIPER_SCOPE_LRG,
  ],
  [WeaponComponentBlueprint.MICROSMG]: [
    WeaponComponent.MICROSMG_CLIP2,
    WeaponComponent.MICROSMG_FLASH,
    WeaponComponent.MICROSMG_SCOPE_MAC,
    WeaponComponent.MICROSMG_SUPP,
    WeaponComponent.MICROSMG_CLIP1,
  ],
  [WeaponComponentBlueprint.PISTOL]: [
    WeaponComponent.PISTOL_FLASH,
    WeaponComponent.PISTOL_SUPP,
    WeaponComponent.PISTOL_CLIP2,
    WeaponComponent.PISTOL_CLIP1,
  ],
  [WeaponComponentBlueprint.PISTOLXM3]: [
    WeaponComponent.PISTOLXM3_CLIP1,
    WeaponComponent.PISTOLXM3_SUPP,
  ],
  [WeaponComponentBlueprint.PUMPSHOTGUN]: [
    WeaponComponent.PUMPSHOTGUN_FLASH,
    WeaponComponent.PUMPSHOTGUN_SUPP,
  ],
  [WeaponComponentBlueprint.APPISTOL]: [
    WeaponComponent.APPISTOL_CLIP2,
    WeaponComponent.APPISTOL_CLIP1,
    WeaponComponent.APPISTOL_FLASH,
    WeaponComponent.APPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.CERAMICPISTOL]: [
    WeaponComponent.CERAMICPISTOL_CLIP1,
    WeaponComponent.CERAMICPISTOL_CLIP2,
    WeaponComponent.CERAMICPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.SMG]: [
    WeaponComponent.SMG_CLIP1,
    WeaponComponent.SMG_CLIP2,
    WeaponComponent.SMG_SCOPE_MAC,
    WeaponComponent.SMG_CLIP_DRM,
    WeaponComponent.SMG_FLASH,
    WeaponComponent.SMG_SUPP,
  ],
  [WeaponComponentBlueprint.ASSAULTRIFLEMK2]: [
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ5,
    WeaponComponent.ASSAULTRIFLEMK2_SCOPE_MAC2,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ6,
    WeaponComponent.ASSAULTRIFLEMK2_HOLO,
    WeaponComponent.ASSAULTRIFLEMK2_BARR,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ7,
    WeaponComponent.ASSAULTRIFLEMK2_BARR2,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_FMJ,
    WeaponComponent.ASSAULTRIFLEMK2_FLASH,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP1,
    WeaponComponent.ASSAULTRIFLEMK2_GRIP,
    WeaponComponent.ASSAULTRIFLEMK2_SUPP,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_AP,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ1,
    WeaponComponent.ASSAULTRIFLEMK2_SCOPE_MED2,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ2,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP2,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ3,
    WeaponComponent.ASSAULTRIFLEMK2_MUZZ4,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_TR,
    WeaponComponent.ASSAULTRIFLEMK2_CLIP_INC,
  ],
  [WeaponComponentBlueprint.HEAVYSHOTGUN]: [
    WeaponComponent.HEAVYSHOTGUN_GRIP,
    WeaponComponent.HEAVYSHOTGUN_CLIP1,
    WeaponComponent.HEAVYSHOTGUN_FLASH,
    WeaponComponent.HEAVYSHOTGUN_CLIP_DRM,
    WeaponComponent.HEAVYSHOTGUN_CLIP2,
    WeaponComponent.HEAVYSHOTGUN_SUPP,
  ],
  [WeaponComponentBlueprint.GRENADELAUNCHERSMOKE]: [
    WeaponComponent.GRENADELAUNCHERSMOKE_GRIP,
    WeaponComponent.GRENADELAUNCHERSMOKE_FLASH,
    WeaponComponent.GRENADELAUNCHERSMOKE_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.PUMPSHOTGUNMK2]: [
    WeaponComponent.PUMPSHOTGUNMK2_SCOPE_MAC2,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_EX,
    WeaponComponent.PUMPSHOTGUNMK2_SCOPE_SML2,
    WeaponComponent.PUMPSHOTGUNMK2_HOLO,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_AP,
    WeaponComponent.PUMPSHOTGUNMK2_MUZZ8,
    WeaponComponent.PUMPSHOTGUNMK2_FLASH,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_INC,
    WeaponComponent.PUMPSHOTGUNMK2_SUPP,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL,
    WeaponComponent.PUMPSHOTGUNMK2_SHELL_HP,
  ],
  [WeaponComponentBlueprint.COMBATPISTOL]: [
    WeaponComponent.COMBATPISTOL_CLIP1,
    WeaponComponent.COMBATPISTOL_FLASH,
    WeaponComponent.COMBATPISTOL_SUPP,
    WeaponComponent.COMBATPISTOL_CLIP2,
  ],
  [WeaponComponentBlueprint.GUSENBERG]: [
    WeaponComponent.GUSENBERG_CLIP1,
    WeaponComponent.GUSENBERG_CLIP2,
  ],
  [WeaponComponentBlueprint.COMPACTRIFLE]: [
    WeaponComponent.COMPACTRIFLE_CLIP1,
    WeaponComponent.COMPACTRIFLE_CLIP2,
    WeaponComponent.COMPACTRIFLE_CLIP_DRM,
  ],
  [WeaponComponentBlueprint.MARKSMANRIFLEMK2]: [
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ5,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ6,
    WeaponComponent.MARKSMANRIFLEMK2_BARR,
    WeaponComponent.MARKSMANRIFLEMK2_HOLO,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ7,
    WeaponComponent.MARKSMANRIFLEMK2_SCOPE_LRG2,
    WeaponComponent.MARKSMANRIFLEMK2_BARR2,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_INC,
    WeaponComponent.MARKSMANRIFLEMK2_FLASH,
    WeaponComponent.MARKSMANRIFLEMK2_SUPP,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP1,
    WeaponComponent.MARKSMANRIFLEMK2_GRIP,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ1,
    WeaponComponent.MARKSMANRIFLEMK2_SCOPE_MED2,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ2,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_TR,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ3,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_FMJ,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP2,
    WeaponComponent.MARKSMANRIFLEMK2_MUZZ4,
    WeaponComponent.MARKSMANRIFLEMK2_CLIP_AP,
  ],
  [WeaponComponentBlueprint.RAILGUN]: [WeaponComponent.RAILGUN_CLIP1],
  [WeaponComponentBlueprint.PRECISIONRIFLE]: [WeaponComponent.PRECISIONRIFLE_CLIP1],
  [WeaponComponentBlueprint.SMGMK2]: [
    WeaponComponent.SMGMK2_MUZZ5,
    WeaponComponent.SMGMK2_CLIP_FMJ,
    WeaponComponent.SMGMK2_MUZZ6,
    WeaponComponent.SMGMK2_CLIP_HP,
    WeaponComponent.SMGMK2_SCOPE_SML2,
    WeaponComponent.SMGMK2_CLIP1,
    WeaponComponent.SMGMK2_MUZZ7,
    WeaponComponent.SMGMK2_FLASH,
    WeaponComponent.SMGMK2_CLIP_TR,
    WeaponComponent.SMGMK2_HOLO,
    WeaponComponent.SMGMK2_BARR2,
    WeaponComponent.SMGMK2_CLIP2,
    WeaponComponent.SMGMK2_MUZZ1,
    WeaponComponent.SMGMK2_SUPP,
    WeaponComponent.SMGMK2_MUZZ2,
    WeaponComponent.SMGMK2_BARR,
    WeaponComponent.SMGMK2_CLIP_INC,
    WeaponComponent.SMGMK2_MUZZ3,
    WeaponComponent.SMGMK2_SCOPE_MAC2,
    WeaponComponent.SMGMK2_MUZZ4,
  ],
  [WeaponComponentBlueprint.BULLPUPRIFLE]: [
    WeaponComponent.BULLPUPRIFLE_GRIP,
    WeaponComponent.BULLPUPRIFLE_FLASH,
    WeaponComponent.BULLPUPRIFLE_SUPP,
    WeaponComponent.BULLPUPRIFLE_SCOPE_SML,
    WeaponComponent.BULLPUPRIFLE_CLIP2,
    WeaponComponent.BULLPUPRIFLE_CLIP1,
  ],
  [WeaponComponentBlueprint.FIREWORK]: [WeaponComponent.FIREWORK_CLIP1],
  [WeaponComponentBlueprint.COMBATMG]: [
    WeaponComponent.COMBATMG_GRIP,
    WeaponComponent.COMBATMG_SCOPE_LRG,
    WeaponComponent.COMBATMG_CLIP2,
    WeaponComponent.COMBATMG_CLIP1,
  ],
  [WeaponComponentBlueprint.CARBINERIFLE]: [
    WeaponComponent.CARBINERIFLE_GRIP,
    WeaponComponent.CARBINERIFLE_FLASH,
    WeaponComponent.CARBINERIFLE_SUPP,
    WeaponComponent.CARBINERIFLE_CLIP2,
    WeaponComponent.CARBINERIFLE_CLIP1,
    WeaponComponent.CARBINERIFLE_SCOPE_LRG,
    WeaponComponent.CARBINERIFLE_CLIP_BOX,
  ],
  [WeaponComponentBlueprint.BULLPUPRIFLEMK2]: [
    WeaponComponent.BULLPUPRIFLEMK2_CLIP1,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ5,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ6,
    WeaponComponent.BULLPUPRIFLEMK2_BARR2,
    WeaponComponent.BULLPUPRIFLEMK2_SCOPE_SML2,
    WeaponComponent.BULLPUPRIFLEMK2_HOLO,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_FMJ,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ7,
    WeaponComponent.BULLPUPRIFLEMK2_BARR,
    WeaponComponent.BULLPUPRIFLEMK2_FLASH,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_TR,
    WeaponComponent.BULLPUPRIFLEMK2_SUPP,
    WeaponComponent.BULLPUPRIFLEMK2_GRIP,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_INC,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ1,
    WeaponComponent.BULLPUPRIFLEMK2_SCOPE_MAC2,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ2,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ3,
    WeaponComponent.BULLPUPRIFLEMK2_MUZZ4,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP2,
    WeaponComponent.BULLPUPRIFLEMK2_CLIP_AP,
  ],
  [WeaponComponentBlueprint.SNSPISTOLMK2]: [
    WeaponComponent.SNSPISTOLMK2_CLIP1,
    WeaponComponent.SNSPISTOLMK2_SCOPE_PI,
    WeaponComponent.SNSPISTOLMK2_FLASH,
    WeaponComponent.SNSPISTOLMK2_SUPP,
    WeaponComponent.SNSPISTOLMK2_CLIP_HP,
    WeaponComponent.SNSPISTOLMK2_CLIP_TR,
    WeaponComponent.SNSPISTOLMK2_COMP,
    WeaponComponent.SNSPISTOLMK2_CLIP_FMJ,
    WeaponComponent.SNSPISTOLMK2_CLIP2,
    WeaponComponent.SNSPISTOLMK2_CLIP_INC,
  ],
  [WeaponComponentBlueprint.FLASHLIGHT]: [WeaponComponent.FLASHLIGHT_FLASH],
  [WeaponComponentBlueprint.SPECIALCARBINEMK2]: [
    WeaponComponent.SPECIALCARBINEMK2_MUZZ5,
    WeaponComponent.SPECIALCARBINEMK2_SCOPE_MAC2,
    WeaponComponent.SPECIALCARBINEMK2_CLIP1,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ6,
    WeaponComponent.SPECIALCARBINEMK2_HOLO,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ7,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_FMJ,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_AP,
    WeaponComponent.SPECIALCARBINEMK2_FLASH,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_TR,
    WeaponComponent.SPECIALCARBINEMK2_GRIP,
    WeaponComponent.SPECIALCARBINEMK2_SUPP,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ1,
    WeaponComponent.SPECIALCARBINEMK2_SCOPE_MED2,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ2,
    WeaponComponent.SPECIALCARBINEMK2_CLIP_INC,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ3,
    WeaponComponent.SPECIALCARBINEMK2_CLIP2,
    WeaponComponent.SPECIALCARBINEMK2_BARR,
    WeaponComponent.SPECIALCARBINEMK2_MUZZ4,
    WeaponComponent.SPECIALCARBINEMK2_BARR2,
  ],
  [WeaponComponentBlueprint.DOUBLEACTION]: [WeaponComponent.DOUBLEACTION_CLIP1],
  [WeaponComponentBlueprint.PISTOL50]: [
    WeaponComponent.PISTOL50_CLIP1,
    WeaponComponent.PISTOL50_FLASH,
    WeaponComponent.PISTOL50_SUPP,
    WeaponComponent.PISTOL50_CLIP2,
  ],
  [WeaponComponentBlueprint.MG]: [
    WeaponComponent.MG_SCOPE_SML,
    WeaponComponent.MG_CLIP2,
    WeaponComponent.MG_CLIP1,
  ],
  [WeaponComponentBlueprint.MILITARYRIFLE]: [
    WeaponComponent.MILITARYRIFLE_CLIP1,
    WeaponComponent.MILITARYRIFLE_CLIP2,
    WeaponComponent.MILITARYRIFLE_MRFL_SIGHT,
    WeaponComponent.MILITARYRIFLE_FLASH,
    WeaponComponent.MILITARYRIFLE_SUPP,
    WeaponComponent.MILITARYRIFLE_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.BULLPUPSHOTGUN]: [
    WeaponComponent.BULLPUPSHOTGUN_GRIP,
    WeaponComponent.BULLPUPSHOTGUN_FLASH,
    WeaponComponent.BULLPUPSHOTGUN_SUPP,
  ],
  [WeaponComponentBlueprint.GRENADELAUNCHER]: [
    WeaponComponent.GRENADELAUNCHER_GRIP,
    WeaponComponent.GRENADELAUNCHER_FLASH,
    WeaponComponent.GRENADELAUNCHER_SCOPE_SML,
  ],
  [WeaponComponentBlueprint.MUSKET]: [WeaponComponent.MUSKET_CLIP1],
  [WeaponComponentBlueprint.ADVANCEDRIFLE]: [
    WeaponComponent.ADVANCEDRIFLE_FLASH,
    WeaponComponent.ADVANCEDRIFLE_SUPP,
    WeaponComponent.ADVANCEDRIFLE_CLIP2,
    WeaponComponent.ADVANCEDRIFLE_SCOPE_SML,
    WeaponComponent.ADVANCEDRIFLE_CLIP1,
  ],
  [WeaponComponentBlueprint.RAYPISTOL]: [WeaponComponent.RAYPISTOL_VAR_RAY18],
  [WeaponComponentBlueprint.MINISMG]: [
    WeaponComponent.MINISMG_CLIP1,
    WeaponComponent.MINISMG_CLIP2,
  ],
  [WeaponComponentBlueprint.SNSPISTOL]: [
    WeaponComponent.SNSPISTOL_CLIP2,
    WeaponComponent.SNSPISTOL_CLIP1,
  ],
  [WeaponComponentBlueprint.PISTOLMK2]: [
    WeaponComponent.PISTOLMK2_COMP,
    WeaponComponent.PISTOLMK2_CLIP_TR,
    WeaponComponent.PISTOLMK2_CLIP_INC,
    WeaponComponent.PISTOLMK2_FLASH,
    WeaponComponent.PISTOLMK2_CLIP_FMJ,
    WeaponComponent.PISTOLMK2_CLIP2,
    WeaponComponent.PISTOLMK2_SUPP,
    WeaponComponent.PISTOLMK2_CLIP_HP,
    WeaponComponent.PISTOLMK2_SCOPE_PI,
    WeaponComponent.PISTOLMK2_CLIP1,
  ],
  [WeaponComponentBlueprint.ASSAULTRIFLE]: [
    WeaponComponent.ASSAULTRIFLE_GRIP,
    WeaponComponent.ASSAULTRIFLE_FLASH,
    WeaponComponent.ASSAULTRIFLE_SCOPE_MAC,
    WeaponComponent.ASSAULTRIFLE_SUPP,
    WeaponComponent.ASSAULTRIFLE_CLIP2,
    WeaponComponent.ASSAULTRIFLE_CLIP1,
    WeaponComponent.ASSAULTRIFLE_CLIP_DRM,
  ],
  [WeaponComponentBlueprint.SPECIALCARBINE]: [
    WeaponComponent.SPECIALCARBINE_GRIP,
    WeaponComponent.SPECIALCARBINE_CLIP_DRM,
    WeaponComponent.SPECIALCARBINE_FLASH,
    WeaponComponent.SPECIALCARBINE_CLIP2,
    WeaponComponent.SPECIALCARBINE_SCOPE_LRG,
    WeaponComponent.SPECIALCARBINE_SUPP,
    WeaponComponent.SPECIALCARBINE_CLIP1,
  ],
  [WeaponComponentBlueprint.MARKSMANRIFLE]: [
    WeaponComponent.MARKSMANRIFLE_GRIP,
    WeaponComponent.MARKSMANRIFLE_SCOPE_LRG,
    WeaponComponent.MARKSMANRIFLE_FLASH,
    WeaponComponent.MARKSMANRIFLE_SUPP,
    WeaponComponent.MARKSMANRIFLE_CLIP2,
    WeaponComponent.MARKSMANRIFLE_CLIP1,
  ],
  [WeaponComponentBlueprint.HEAVYRIFLE]: [
    WeaponComponent.HEAVYRIFLE_GRIP,
    WeaponComponent.HEAVYRIFLE_CLIP1,
    WeaponComponent.HEAVYRIFLE_CLIP2,
    WeaponComponent.HEAVYRIFLE_FLASH,
    WeaponComponent.HEAVYRIFLE_SUPP,
    WeaponComponent.HEAVYRIFLE_SCOPE_LRG,
    WeaponComponent.HEAVYRIFLE_HVYRFLE_SIG,
  ],
  [WeaponComponentBlueprint.REVOLVERMK2]: [
    WeaponComponent.REVOLVERMK2_CLIP_INC,
    WeaponComponent.REVOLVERMK2_SCOPE_MAC2,
    WeaponComponent.REVOLVERMK2_CLIP_FMJ,
    WeaponComponent.REVOLVERMK2_CLIP_HP,
    WeaponComponent.REVOLVERMK2_COMP,
    WeaponComponent.REVOLVERMK2_FLASH,
    WeaponComponent.REVOLVERMK2_HOLO,
    WeaponComponent.REVOLVERMK2_CLIP1_RV,
    WeaponComponent.REVOLVERMK2_CLIP_TR,
  ],
  [WeaponComponentBlueprint.TACTICALRIFLE]: [
    WeaponComponent.TACTICALRIFLE_GRIP,
    WeaponComponent.TACTICALRIFLE_CLIP1,
    WeaponComponent.TACTICALRIFLE_CLIP2,
    WeaponComponent.TACTICALRIFLE_FLASH,
    WeaponComponent.TACTICALRIFLE_SUPP,
  ],
  [WeaponComponentBlueprint.HEAVYPISTOL]: [
    WeaponComponent.HEAVYPISTOL_CLIP1,
    WeaponComponent.HEAVYPISTOL_FLASH,
    WeaponComponent.HEAVYPISTOL_CLIP2,
    WeaponComponent.HEAVYPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.MACHINEPISTOL]: [
    WeaponComponent.MACHINEPISTOL_CLIP1,
    WeaponComponent.MACHINEPISTOL_CLIP_DRM,
    WeaponComponent.MACHINEPISTOL_CLIP2,
    WeaponComponent.MACHINEPISTOL_SUPP,
  ],
  [WeaponComponentBlueprint.COMBATMGMK2]: [
    WeaponComponent.COMBATMGMK2_MUZZ5,
    WeaponComponent.COMBATMGMK2_CLIP2,
    WeaponComponent.COMBATMGMK2_CLIP_AP,
    WeaponComponent.COMBATMGMK2_MUZZ6,
    WeaponComponent.COMBATMGMK2_SCOPE_SML2,
    WeaponComponent.COMBATMGMK2_HOLO,
    WeaponComponent.COMBATMGMK2_CLIP1,
    WeaponComponent.COMBATMGMK2_MUZZ7,
    WeaponComponent.COMBATMGMK2_CLIP_FMJ,
    WeaponComponent.COMBATMGMK2_GRIP,
    WeaponComponent.COMBATMGMK2_BARR2,
    WeaponComponent.COMBATMGMK2_MUZZ1,
    WeaponComponent.COMBATMGMK2_CLIP_INC,
    WeaponComponent.COMBATMGMK2_BARR,
    WeaponComponent.COMBATMGMK2_SCOPE_MED2,
    WeaponComponent.COMBATMGMK2_MUZZ2,
    WeaponComponent.COMBATMGMK2_MUZZ3,
    WeaponComponent.COMBATMGMK2_MUZZ4,
    WeaponComponent.COMBATMGMK2_CLIP_TR,
  ],
  [WeaponComponentBlueprint.ASSAULTSHOTGUN]: [
    WeaponComponent.ASSAULTSHOTGUN_GRIP,
    WeaponComponent.ASSAULTSHOTGUN_FLASH,
    WeaponComponent.ASSAULTSHOTGUN_SUPP,
    WeaponComponent.ASSAULTSHOTGUN_CLIP2,
    WeaponComponent.ASSAULTSHOTGUN_CLIP1,
  ],
  [WeaponComponentBlueprint.ASSAULTSMG]: [
    WeaponComponent.ASSAULTSMG_FLASH,
    WeaponComponent.ASSAULTSMG_SCOPE_MAC,
    WeaponComponent.ASSAULTSMG_SUPP,
  ],
  [WeaponComponentBlueprint.CARBINERIFLEMK2]: [
    WeaponComponent.CARBINERIFLEMK2_MUZZ5,
    WeaponComponent.CARBINERIFLEMK2_SCOPE_MAC2,
    WeaponComponent.CARBINERIFLEMK2_CLIP_TR,
    WeaponComponent.CARBINERIFLEMK2_CLIP_AP,
    WeaponComponent.CARBINERIFLEMK2_MUZZ6,
    WeaponComponent.CARBINERIFLEMK2_CLIP_INC,
    WeaponComponent.CARBINERIFLEMK2_HOLO,
    WeaponComponent.CARBINERIFLEMK2_CLIP_FMJ,
    WeaponComponent.CARBINERIFLEMK2_CLIP1,
    WeaponComponent.CARBINERIFLEMK2_MUZZ7,
    WeaponComponent.CARBINERIFLEMK2_CLIP2,
    WeaponComponent.CARBINERIFLEMK2_FLASH,
    WeaponComponent.CARBINERIFLEMK2_BARR,
    WeaponComponent.CARBINERIFLEMK2_SUPP,
    WeaponComponent.CARBINERIFLEMK2_BARR2,
    WeaponComponent.CARBINERIFLEMK2_GRIP,
    WeaponComponent.CARBINERIFLEMK2_MUZZ1,
    WeaponComponent.CARBINERIFLEMK2_SCOPE_MED2,
    WeaponComponent.CARBINERIFLEMK2_MUZZ2,
    WeaponComponent.CARBINERIFLEMK2_MUZZ3,
    WeaponComponent.CARBINERIFLEMK2_MUZZ4,
  ],
  [WeaponComponentBlueprint.RAILGUNXM3]: [WeaponComponent.RAILGUNXM3_CLIP1],
}).forEach(([key, components]) => {
  const weaponItemKey = key.replace("_cs", "") as string as WeaponItemKey;
  registerBlueprint({
    key,
    name: `${getItemName(weaponItemKey)} components blueprint`,
    description: `Lets you craft weapon components for ${getItemName(weaponItemKey)}`,
    recipes: components.map((component) => ({
      durationSeconds: 2,
      item: {
        key: component,
      },
      parts: [
        { key: Metal.COMMON_METAL, amount: 5 },
        { key: Scrap.COMMON_SCRAP, amount: 5 },
      ],
    })),
  });
});
