export const Events = {
  Server: {
    BEGIN_CONNECTION: "BEGIN_CONNECTION",
    START_GAME: "START_GAME",
    SCREENSHOT_POPULATE_DATA: "SCREENSHOT_POPULATE_DATA",
    DISCORD_AUTH_DONE: "DISCORD_AUTH_DONE",
    REQUEST_ITEM: "REQUEST_ITEM",
    SYNC_NPC: "SYNC_NPC",
    STOP_NPC_TASK: "STOP_NPC_TASK",
  },
  Client: {
    DISCORD_BEGIN_AUTH: "DISCORD_BEGIN_AUTH",

    START_CHARACTER_CREATION_SCENE: "START_CHARACTER_CREATION_SCENE",
    END_CHARACTER_CREATION_SCENE: "END_CHARACTER_CREATION_SCENE",
    START_CHARACTER_SELECTION_SCENE: "START_CHARACTER_SELECTION_SCENE",
    UPDATE_CHARACTER_APPEARANCE: "UPDATE_CHARACTER_APPEARANCE",
    CANCEL_CHARACTER_CREATION: "CANCEL_CHARACTER_CREATION",
    CHARACTER_CREATED: "CHARACTER_CREATED",
    SET_PLAYER_DECORATIONS: "SET_PLAYER_DECORATIONS",

    START_GAME: "START_GAME",

    SETUP_WEBVIEW: "WEBVIEW_INFO",
    PLAYER_EMIT_SPINNER: "PLAYER_EMIT_SPINNER",
    PLAYER_EMIT_SPINNER_CLEAR: "PLAYER_EMIT_SPINNER_CLEAR",
    SCREENSHOT_CREATE: "SCREENSHOT_CREATE",
    PLAYER_RELOAD: "PLAYER_RELOAD",
    PLAYER_EMIT_NOTIFICATION: "PLAYER_EMIT_NOTIFICATION",
    PLAYER_EMIT_MISSION_TEXT: "PLAYER_EMIT_MISSION_TEXT",
    PLAYER_EMIT_TEMP_OBJECT_LERP: "PLAYER_EMIT_TEMP_OBJECT_LERP",
    IPL_LOAD: "IPL_LOAD",
    IPL_UNLOAD: "IPL_UNLOAD",
    PLAYER_EMIT_ERROR_SCREEN: "PLAYER_EMIT_ERROR_SCREEN",
    PLAYER_EMIT_ERROR_SCREEN_CLEAR: "PLAYER_EMIT_ERROR_SCREEN_CLEAR",
    ENTITYSET_ACTIVATE: "ENTITYSET_ACTIVATE",
    ENTITYSET_DEACTIVATE: "ENTITYSET_DEACTIVATE",

    SET_STATE: "SET_STATE",
    UPDATE_STATE: "UPDATE_STATE",

    INPUT_FOCUS: "INPUT_FOCUS",
  },

  Webview: {
    VIEW_READY: "VIEW_READY",
    PLAY_SOUND: "PLAY_SOUND",
    DEBUG: "DEBUG",
    CAMERA_MOVE_START: "CAMERA_MOVE_START",
    CAMERA_MOVE: "CAMERA_MOVE",
    CAMERA_MOVE_END: "CAMERA_MOVE_END",

    TOGGLE_ELEMENT: "TOGGLE_ELEMENT",

    UPDATE_STATE: "UPDATE_STATE",
  },
} as const;
