export const RPC = {
  Server: {
    CREATE_CHARACTER: "CREATE_CHARACTER",
    USE_ITEM: "USE_ITEM",
    EQUIP_ITEM: "EQUIP_ITEM",
    DROP_ITEM: "DROP_ITEM",
    MOVE_ITEM: "MOVE_ITEM",
    APPLY_NPC_DAMAGE: "APPLY_NPC_DAMAGE",
  },
  Client: {
    CREATE_CHARACTER: "CREATE_CHARACTER",
    ENTITYSET_IS_ACTIVE: "ENTITYSET_IS_ACTIVE",
    USE_ITEM: "USE_ITEM",
    EQUIP_ITEM: "EQUIP_ITEM",
    DROP_ITEM: "DROP_ITEM",
    MOVE_ITEM: "MOVE_ITEM",
  },
} as const;
