export const TreeTypes = {
  h4_prop_tree_beech_lrg_if_01: {
    key: "h4_prop_tree_beech_lrg_if_01",
    name: "Large Beech Tree",
    level: 20,
    logs: "large_beech_logs",
  },
  h4_prop_tree_blk_mgrv_lrg_01: {
    key: "h4_prop_tree_blk_mgrv_lrg_01",
    name: "Black Mangrove (Large)",
    level: 40,
    logs: "black_mangrove_logs_large",
  },
  h4_prop_tree_blk_mgrv_lrg_02: {
    key: "h4_prop_tree_blk_mgrv_lrg_02",
    name: "Black Mangrove (Large)",
    level: 40,
    logs: "black_mangrove_logs_large",
  },
  h4_prop_tree_blk_mgrv_med_01: {
    key: "h4_prop_tree_blk_mgrv_med_01",
    name: "Black Mangrove (Medium)",
    level: 20,
    logs: "black_mangrove_logs_medium",
  },
  h4_prop_tree_frangipani_lrg_01: {
    key: "h4_prop_tree_frangipani_lrg_01",
    name: "Frangipani (Large)",
    level: 10,
    logs: "frangipani_logs_large",
  },
  h4_prop_tree_palm_fan_bea_03b: {
    key: "h4_prop_tree_palm_fan_bea_03b",
    name: "Palm Fan Tree",
    level: 10,
    logs: "palm_fan_logs",
  },
  h4_prop_tree_umbrella_med_01: {
    key: "h4_prop_tree_umbrella_med_01",
    name: "Umbrella Tree (Medium)",
    level: 20,
    logs: "umbrella_logs_medium",
  },
  h4_prop_tree_umbrella_sml_01: {
    key: "h4_prop_tree_umbrella_sml_01",
    name: "Umbrella Tree (Small)",
    level: 10,
    logs: "umbrella_logs_small",
  },
  prop_joshua_tree_01a: {
    key: "prop_joshua_tree_01a",
    name: "Joshua Tree",
    level: 70,
    logs: "joshua_tree_logs",
  },
  prop_joshua_tree_02e: {
    key: "prop_joshua_tree_02e",
    name: "Joshua Tree",
    level: 70,
    logs: "joshua_tree_logs",
  },
  prop_palm_med_01a: {
    key: "prop_palm_med_01a",
    name: "Medium Palm Tree",
    level: 10,
    logs: "medium_palm_logs",
  },
  prop_palm_sm_01a: {
    key: "prop_palm_sm_01a",
    name: "Small Palm Tree",
    level: 1,
    logs: "small_palm_logs",
  },
  prop_palm_sm_01d: {
    key: "prop_palm_sm_01d",
    name: "Small Palm Tree",
    level: 1,
    logs: "small_palm_logs",
  },
  prop_palm_sm_01f: {
    key: "prop_palm_sm_01f",
    name: "Small Palm Tree",
    level: 1,
    logs: "small_palm_logs",
  },
  prop_rus_olive_wint: {
    key: "prop_rus_olive_wint",
    name: "Russian Olive (Winter)",
    level: 40,
    logs: "russian_olive_logs_winter",
  },
  prop_s_pine_dead_01: {
    key: "prop_s_pine_dead_01",
    name: "Dead Pine Tree",
    level: 1,
    logs: "dead_pine_logs",
  },
  prop_tree_birch_02: {
    key: "prop_tree_birch_02",
    name: "Birch Tree",
    level: 20,
    logs: "birch_logs",
  },
  prop_tree_birch_03b: {
    key: "prop_tree_birch_03b",
    name: "Birch Tree",
    level: 20,
    logs: "birch_logs",
  },
  prop_tree_birch_04: {
    key: "prop_tree_birch_04",
    name: "Birch Tree",
    level: 20,
    logs: "birch_logs",
  },
  prop_tree_cedar_02: {
    key: "prop_tree_cedar_02",
    name: "Cedar Tree",
    level: 40,
    logs: "cedar_logs",
  },
  prop_tree_cedar_03: {
    key: "prop_tree_cedar_03",
    name: "Cedar Tree",
    level: 40,
    logs: "cedar_logs",
  },
  prop_tree_cedar_04: {
    key: "prop_tree_cedar_04",
    name: "Cedar Tree",
    level: 40,
    logs: "cedar_logs",
  },
  prop_tree_cedar_s_01: {
    key: "prop_tree_cedar_s_01",
    name: "Small Cedar Tree",
    level: 20,
    logs: "small_cedar_logs",
  },
  prop_tree_cedar_s_02: {
    key: "prop_tree_cedar_s_02",
    name: "Small Cedar Tree",
    level: 20,
    logs: "small_cedar_logs",
  },
  prop_tree_eng_oak_01: {
    key: "prop_tree_eng_oak_01",
    name: "English Oak",
    level: 70,
    logs: "english_oak_logs",
  },
  prop_tree_eucalip_01: {
    key: "prop_tree_eucalip_01",
    name: "Eucalyptus Tree",
    level: 40,
    logs: "eucalyptus_logs",
  },
  prop_tree_jacada_01: {
    key: "prop_tree_jacada_01",
    name: "Jacada Tree",
    level: 20,
    logs: "jacada_logs",
  },
  prop_tree_jacada_02: {
    key: "prop_tree_jacada_02",
    name: "Jacada Tree",
    level: 20,
    logs: "jacada_logs",
  },
  prop_tree_lficus_02: {
    key: "prop_tree_lficus_02",
    name: "Ficus Tree",
    level: 10,
    logs: "ficus_logs",
  },
  prop_tree_lficus_03: {
    key: "prop_tree_lficus_03",
    name: "Ficus Tree",
    level: 10,
    logs: "ficus_logs",
  },
  prop_tree_lficus_05: {
    key: "prop_tree_lficus_05",
    name: "Ficus Tree",
    level: 10,
    logs: "ficus_logs",
  },
  prop_tree_lficus_06: {
    key: "prop_tree_lficus_06",
    name: "Ficus Tree",
    level: 10,
    logs: "ficus_logs",
  },
  prop_tree_maple_02: {
    key: "prop_tree_maple_02",
    name: "Maple Tree",
    level: 40,
    logs: "maple_logs",
  },
  prop_tree_maple_03: {
    key: "prop_tree_maple_03",
    name: "Maple Tree",
    level: 40,
    logs: "maple_logs",
  },
  prop_tree_mquite_01: {
    key: "prop_tree_mquite_01",
    name: "Mesquite Tree",
    level: 20,
    logs: "mesquite_logs",
  },
  prop_tree_oak_01: {
    key: "prop_tree_oak_01",
    name: "Oak Tree",
    level: 70,
    logs: "oak_logs",
  },
  prop_tree_pine_01: {
    key: "prop_tree_pine_01",
    name: "Pine Tree",
    level: 20,
    logs: "pine_logs",
  },
  prop_tree_pine_02: {
    key: "prop_tree_pine_02",
    name: "Pine Tree",
    level: 20,
    logs: "pine_logs",
  },
  prop_w_r_cedar_01: {
    key: "prop_w_r_cedar_01",
    name: "Wild Red Cedar",
    level: 40,
    logs: "wild_red_cedar_logs",
  },
  prop_w_r_cedar_dead: {
    key: "prop_w_r_cedar_dead",
    name: "Dead Wild Red Cedar",
    level: 1,
    logs: "dead_wild_red_cedar_logs",
  },
} as const;
