host = "0.0.0.0"
name = "rift.lt"
port = 7_788
password = ""
announce = false
useEarlyAuth = false
useCdn = false
debug = true
modules = [ "js-module-v2" ]
resources = [ "ipls/*", "weapons/*", "resource-control", "main" ]
