// Ped Config flags, used to control ped behaviour/setup
export enum PED_CONFIG_FLAG {
  CreatedByFactory = 0,
  NoCriticalHits = 2,
  DrownsInWater = 3,
  DisableReticuleFixedLockon = 4,
  DiesInstantlyWhenSwimming = 5,
  UpperBodyDamageAnimsOnly = 7,
  NeverLeavesGroup = 13,
  DoesntDropWeaponsWhenDead = 14,
  KeepTasksAfterCleanUp = 16,
  BlockNonTemporaryEvents = 17,
  WaitingForScriptBrainToLoad = 19,
  AllowMedicsToAttend = 20, // If this ped dies medics will be dispatched, false by default for mission peds, the ped wont be revived
  MoneyHasBeenGivenByScript = 21,
  NotAllowedToCrouch = 22,
  IgnoreSeenMelee = 24,
  DontAllowToBeDraggedOutOfVehicle = 26, // Prevents a ped from being able to be dragged out of a car
  GetOutUndriveableVehicle = 29, // Script can stop peds automatically getting out of car when it's upside down or undrivable, defaults to true
  DontStoreAsPersistent = 31,
  WillFlyThroughWindscreen = 32, // Ped will fly through the vehicle windscreen upon a forward impact at high velocity
  DieWhenRagdoll = 33, // If set, this ped will die when in ragdoll
  HasHelmet = 34, // Ped has a helmet (/ The PedHelmetComponent has put the helmet on the ped via "put on" animations)
  UseHelmet = 35,
  DontTakeOffHelmet = 36, // Disable the ped taking off his helmet automatically
  HideInCutscene = 37,
  DisableEvasiveDives = 39,
  DontInfluenceWantedLevel = 42, // Can do any crime against this character and the cops turn a blind eye (no crime reported)
  DisablePlayerLockOn = 43,
  DisableLockonToRandomPeds = 44, // Disable lockon to random ambient peds
  AllowLockonToFriendlyPlayers = 45,
  DisableHornAudioWhenDead = 46, // Disable horn audio when the ped dies and rests his head on top of the steering wheel
  PedBeingDeleted = 47,
  BlockWeaponSwitching = 48,
  ConstrainToNavMesh = 56,
  IsFiring = 58,
  WasFiring = 59,
  IsStanding = 60,
  WasStanding = 61,
  InVehicle = 62,
  OnMount = 63,
  AttachedToVehicle = 64,
  IsSwimming = 65,
  WasSwimming = 66,
  IsSkiing = 67,
  IsSitting = 68,
  KilledByStealth = 69,
  KilledByTakedown = 70,
  Knockedout = 71,
  ClearRadarBlipOnDeath = 72,
  UsingCoverPoint = 75,
  IsInTheAir = 76,
  KnockedUpIntoAir = 77,
  IsAimingGun = 78, // Is set when a ped is performing an aim task
  HasJustLeftCar = 79,
  CurrLeftFootCollNM = 81,
  PrevLeftFootCollNM = 82,
  CurrRightFootCollNM = 83,
  PrevRightFootCollNM = 84,
  DontActivateRagdollFromAnyPedImpact = 89,
  ForcePedLoadCover = 93,
  VaultFromCover = 97,
  UsingCrouchedPedCapsule = 99,
  ForcedAim = 101, // If set, we will always behave like we have the aim trigger pressed, also works for AI in cars
  OpenDoorArmIK = 104, // Set if the ped should enable open door arm IK
  ForceReload = 105,
  DontActivateRagdollFromVehicleImpact = 106, // Blocks ragdoll activation when hit by a vehicle
  DontActivateRagdollFromBulletImpact = 107, // Blocks ragdoll activation when hit by a bullet
  DontActivateRagdollFromExplosions = 108, // Blocks ragdoll activation when hit by an explosive
  DontActivateRagdollFromFire = 109, // Blocks ragdoll activation when set on fire
  DontActivateRagdollFromElectrocution = 110, // Blocks ragdoll activation when electrocuted
  IsBeingDraggedToSafety = 111,
  KeepWeaponHolsteredUnlessFired = 113, // Will keep the peds weapon holstered until they shoot or change weapons
  ForceControlledKnockout = 114, // Forces a melee knockout state for the victim ped
  FallsOutOfVehicleWhenKilled = 115, // Forces a ped in a vehicle to collapse out onto the floor (TaskDyingDead launches TaskExitVehicle)
  GetOutBurningVehicle = 116, // If set, a ped will escape a burning vehicle they are inside, defaults to true
  BumpedByPlayer = 117,
  RunFromFiresAndExplosions = 118, // If set, a ped will escape a burning vehicle they are inside, defaults to true
  TreatAsPlayerDuringTargeting = 119, // If set, the ped will be given the same boost a player gets in the targeting scoring system
  IsHandCuffed = 120,
  IsAnkleCuffed = 121,
  DisableMelee = 122, // Disable melee for a ped (only supported for player right now)
  DisableUnarmedDrivebys = 123, // Disable unarmed driveby taunts for a ped
  JustGetsPulledOutWhenElectrocuted = 124, // MP only - if this ped is tased or rubber bulleted in a vehicle and a ped jacks them, the jacker will only pull the ped out
  WillNotHotwireLawEnforcementVehicle = 126, // If set, the ped won't hotwire a lawenforcement vehicle
  WillCommandeerRatherThanJack = 127, // If set, the ped will play commandeering anims rather than jacking if available
  CanBeAgitated = 128, // If set, the ped can be agitated
  ForcePedToFaceLeftInCover = 129, // If set ped will turn to face left in cover
  ForcePedToFaceRightInCover = 130, // If set ped will turn to face right in cover
  BlockPedFromTurningInCover = 131, // If set ped will not turn in cover, unless one of the force flags is set
  KeepRelationshipGroupAfterCleanUp = 132, // Ped keeps their relationship group when the mission is cleaned up or they are marked as no longer needed
  ForcePedToBeDragged = 133, // Ped will loop the try locked door anim when they get to the door in order for them to automatically be dragged along
  PreventPedFromReactingToBeingJacked = 134, // Ped doesn't react when being jacked
  IsScuba = 135,
  WillArrestRatherThanJack = 136,
  RemoveDeadExtraFarAway = 137, // We must be further away before ped polulation remove this ped when it is dead
  RidingTrain = 138,
  ArrestResult = 139, // If set, the ped arrest task completed successfully
  CanAttackFriendly = 140, // True allows this ped to attack peds they are friendly with
  WillJackAnyPlayer = 141, // MP only, if set this ped will be allowed to jack any player peds, regardless of relationship
  WillJackWantedPlayersRatherThanStealCar = 144, //MP only, True if this player will jack hated players rather than try to steal a car (cops arresting crims)
  DisableLadderClimbing = 146, // If this flag is set on a ped it will not scan for or climb ladders
  StairsDetected = 147,
  SlopeDetected = 148,
  HelmetHasBeenShot = 149,
  CowerInsteadOfFlee = 150, // If set the ped should cower instead of fleeing
  CanActivateRagdollWhenVehicleUpsideDown = 151, //If set the ped will be allowed to ragdoll when the vehicle they are in gets turned upside down if the seat supports it
  AlwaysRespondToCriesForHelp = 152, // If set the ped will respond to cries for help even if not friends with the injured ped.
  DisableBloodPoolCreation = 153, // If set the ped will not create a blood pool when dead
  ShouldFixIfNoCollision = 154, // If set, the ped will be fixed if there is no collision around.
  CanPerformArrest = 155, // If set, the ped can perform arrests on peds that can be arrested
  CanPerformUncuff = 156, // If set, the ped can uncuff peds that are handcuffed
  CanBeArrested = 157, // If set, the ped can be arrested
  MoverConstrictedByOpposingCollisions = 158,
  PlayerPreferFrontSeatMP = 159, // When true, Prefer the front seat when getting in a car with buddies.
  DontActivateRagdollFromImpactObject = 160,
  DontActivateRagdollFromMelee = 161,
  DontActivateRagdollFromWaterJet = 162,
  DontActivateRagdollFromDrowning = 163,
  DontActivateRagdollFromFalling = 164,
  DontActivateRagdollFromRubberBullet = 165,
  IsInjured = 166,
  DontEnterVehiclesInPlayersGroup = 167, // When true, will follow the player around if in their group but wont enter vehicles.
  SwimmingTasksRunning = 168,
  CannotBeTargeted = 169, // DEPRECATED - Use the reset flag instead
  PreventAllMeleeTaunts = 169, // Disable all melee taunts for this particular ped
  ForceDirectEntry = 170, // Will force this ped to use the direct entry point for any vehicle they try to enter, or warp in
  AlwaysSeeApproachingVehicles = 171, // This ped will always see approaching vehicles (even from behind).
  CanDiveAwayFromApproachingVehicles = 172, // This ped can dive away from approaching vehicles.
  AllowPlayerToInterruptVehicleEntryExit = 173, // Will allow player to interrupt a peds scripted entry/exit task as if they had triggered it themselves
  OnlyAttackLawIfPlayerIsWanted = 174, // This ped will only attack cops if the player is wanted
  PlayerInContactWithKinematicPed = 175,
  PlayerInContactWithSomethingOtherThanKinematicPed = 176,
  PedsJackingMeDontGetIn = 177, // If set the ped will not get in as part of the jack
  PedIgnoresAnimInterruptEvents = 179, // AI peds only, will not early out of anims, default behaviour is to exit as early as possible
  IsInCustody = 180, // Any targeting LoS checks will fail if any materials with 'see through' materials found.
  ForceStandardBumpReactionThresholds = 181, // Setting this on an armed or buddy ped will make him more likely to perform an nm reaction when bumped by a player, friendly vehicle or ragdolling ped.
  LawWillOnlyAttackIfPlayerIsWanted = 182, // If set on a ped, law peds will only attack if the local player is wanted
  IsAgitated = 183,
  PreventAutoShuffleToDriversSeat = 184, // Prevents passenger from auto shuffling over to drivers seat if it becomes free
  UseKinematicModeWhenStationary = 185, // When enabled, the ped will continually set the kinematic mode reset flag when stationary.
  EnableWeaponBlocking = 186,
  HasHurtStarted = 187,
  DisableHurt = 188, // Set to disable the combat hurt mode
  PlayerIsWeird = 189, // Should this player ped periodically generate shocking events for being weird
  WarpIntoLeadersVehicle = 192,
  DoNothingWhenOnFootByDefault = 193, // Do nothing when on foot, by default
  UsingScenario = 194,
  VisibleOnScreen = 195,
  ActivateOnSwitchFromLowPhysicsLod = 197,
  DontReactivateRagdollOnPedCollisionWhenDead = 198, // Peds with this flag set won't be allowed to reactivate their ragdoll when hit by another ragdoll.
  DontReactivateRagdollOnVehicleCollisionWhenDead = 199, // Peds with this flag set won't be allowed to reactivate their ragdoll when hit by a vehicle.
  HasBeenInArmedCombat = 200, // True if we've ever been in non-melee combat
  UseDiminishingAmmoRate = 201,
  AvoidanceIgnoreAll = 202, // True if the ped never steer around other peds.
  AvoidanceIgnoredbyAll = 203, // True if other peds never steer around the ped.
  AvoidanceIgnoreGroup1 = 204, // True if the ped steer around other peds that are members of group 1.
  AvoidanceMemberofGroup1 = 205, // True if the ped are members of avoidance group 1.
  ForcedToUseSpecificGroupSeatIndex = 206, // Ped is forced to use specific seat index set by SET_PED_GROUP_MEMBER_PASSENGER_INDEX
  LowPhysicsLodMayPlaceOnNavMesh = 207,
  DisableExplosionReactions = 208, // If set, ped will ignore explosion events
  WaitingForPlayerControlInterrupt = 210, // Set when player switches to an ai ped and keeps the scripted task of the ai ped, if unset we won't check for interrupts or time out
  ForcedToStayInCover = 211, // If set, ped will stay in cover (won't come out to fire or move out during combat)
  GeneratesSoundEvents = 212, // Does this ped generate sound events?
  ListensToSoundEvents = 213, // Does this ped have the ability to respond to sound events?
  AllowToBeTargetedInAVehicle = 214, // Ped can be targeting inside a vehicle
  WaitForDirectEntryPointToBeFreeWhenExiting = 215, // When exiting a vehicle, the ped will wait for the direct entry point to be clear before exiting
  OnlyRequireOnePressToExitVehicle = 216, // Player doesn't need to hold exit button to exit vehicles
  ForceExitToSkyDive = 217, // Force the skydive exit if we're exiting the vehicle
  AllowPedInVehiclesOverrideTaskFlags = 219,
  DisableExitToSkyDive = 221, // Disable the skydive exit if we're exiting the vehicle
  ScriptHasDisabledCollision = 222,
  UseAmbientModelScaling = 223,
  DisablePotentialToBeWalkedIntoResponse = 225,
  DisablePedAvoidance = 226, // This ped will not avoid other peds whilst navigating
  ForceRagdollUponDeath = 227, // When the ped dies, it will ragdoll instead of potentially choosing an animated death
  DisablePanicInVehicle = 229, // Disable panic in vehicle
  AllowedToDetachTrailer = 230, // Allow this ped to detach trailers from vehicles
  AllowBlockDeadPedRagdollActivation = 235,
  IsHoldingProp = 236,
  ForceSkinCharacterCloth = 240, // ForceSkin character cloth on creation when flag is set
  LeaveEngineOnWhenExitingVehicles = 241, // Player will leave the engine on when exiting a vehicle normally
  PhoneDisableTextingAnimations = 242, // tells taskmobile phone to not texting animations.  Currently don't play these in MP
  PhoneDisableTalkingAnimations = 243, // tells taskmobile phone to not talking animations.  Currently don't play these in MP
  PhoneDisableCameraAnimations = 244, // tells taskmobile phone to not camera animations.  Currently don't play these in SP
  DisableBlindFiringInShotReactions = 245, // Stops the ped from accidentally firing his weapon when shot.
  AllowNearbyCoverUsage = 246, // This makes it so that OTHER peds are allowed to take cover at points that would otherwise be rejected due to proximity
  CanAttackNonWantedPlayerAsLaw = 249, // If this ped is a law enforcement ped then we will NOT quit combat due to a target player no longer having a wanted level
  WillTakeDamageWhenVehicleCrashes = 250, // If set, this ped will take damage if the car they are in crashes
  AICanDrivePlayerAsRearPassenger = 251, // If this ai ped is driving the vehicle, if the player taps to enter, they will enter as a rear passenger, if they hold, they'll jack the driver
  PlayerCanJackFriendlyPlayers = 252, // If a friendly player is driving the vehicle, if the player taps to enter, they will enter as a passenger, if they hold, they'll jack the driver
  OnStairs = 253,
  AIDriverAllowFriendlyPassengerSeatEntry = 255, // If this ai ped is driving the vehicle, allow players to get in passenger seats
  ParentCarIsBeingRemoved = 256,
  AllowMissionPedToUseInjuredMovement = 259, // Set the target ped to be allowed to use Injured movement clips
  PreventUsingLowerPrioritySeats = 261, // Don't use certain seats (like hanging on the side of a vehicle)
  JustLeftVehicleNeedsReset = 262,
  TeleportToLeaderVehicle = 268, // If set, teleport if ped is not in the leader's vehicle before TaskEnterVehicle::m_SecondsBeforeWarpToLeader.
  AvoidanceIgnoreWeirdPedBuffer = 269, // Don't walk extra far around weird peds like trevor.
  OnStairSlope = 270,
  DontBlipCop = 272, // Don't add a blip for this cop
  KillWhenTrapped = 275, // Kill this ped if it becomes trapped and cannot get up
  EdgeDetected = 276,
  AlwaysWakeUpPhysicsOfIntersectedPeds = 277,
  AvoidTearGas = 279, // If set, this ped will avoid tear gas
  StoppedSpeechUponFreezing = 280,
  DisableGoToWritheWhenInjured = 281, // If set, CPed::DAMAGED_GOTOWRITHE will no longer get set.  In particular, tazer hits wil no longer kill this ped in one hit
  OnlyUseForcedSeatWhenEnteringHeliInGroup = 282, // If set this ped will only use their forced seat index if the vehicle they're entering is a heli as part of a group
  ThrownFromVehicleDueToExhaustion = 283,
  DisableWeirdPedEvents = 285, // Disables weird ped events
  ShouldChargeNow = 286, // This ped should charge if in combat right away, for use by scripts, cleared once ped charges
  RagdollingOnBoat = 287,
  HasBrandishedWeapon = 288,
  PedHasBeenSeen = 291,
  PedIsInReusePool = 292,
  DisableShockingEvents = 294, // This ped should ignore shocking events.
  MovedUsingLowLodPhysicsSinceLastActive = 295,
  NeverReactToPedOnRoof = 296, // If true, this ped will not react to a ped standing on the roof
  DisableShockingDrivingOnPavementEvents = 299, // If true, this ped will not react to peds driving on pavement
  ShouldThrowSmokeGrenadeNow = 300, // This ped should throw a smoke grenade in combat right away, for use by scripts, cleared once ped throws
  DisablePedConstraints = 301,
  ForceInitialPeekInCover = 302, // If set, ped will peek once before firing in cover. Cleared upon peeking.
  DisableJumpingFromVehiclesAfterLeader = 305, // If true, disable followers jumping out of cars after their group leader
  DontActivateRagdollFromPlayerPedImpact = 306,
  DontActivateRagdollFromAiRagdollImpact = 307,
  DontActivateRagdollFromPlayerRagdollImpact = 308,
  DisableQuadrupedSpring = 309,
  IsInCluster = 310,
  ShoutToGroupOnPlayerMelee = 311, // If set, ped will shout target position when melee attacked by a player
  IgnoredByAutoOpenDoors = 312, // Set this for a ped to be ignored by the auto opened doors when checking to see if the door should be opened.
  PreferInjuredGetup = 313,
  ForceIgnoreMeleeActiveCombatant = 314, // Purposely ignore the melee active combatant role and push them into a support or inactive combatant role
  CheckLoSForSoundEvents = 315, // If set, ped will ignore sound events generated by entites it can't see.
  JackedAbandonedCar = 316,
  CanSayFollowedByPlayerAudio = 317, // If set, ped can play FRIEND_FOLLOWED_BY_PLAYER lines.
  ActivateRagdollFromMinorPlayerContact = 318, // If set, the ped will activate ragdoll much more easily on contact with the player
  ForcePoseCharacterCloth = 320, // Default cloth pose will be applied if is available in the character cloth when the cloth is created
  HasClothCollisionBounds = 321, // Ped has cloth collision bounds
  HasHighHeels = 322,
  DontBehaveLikeLaw = 324, // If set on a non-law ped that has law like behavior (i.e. security) then that ped will not use the law like behaviors/logic
  SpawnedAtScenario = 325,
  DisablePoliceInvestigatingBody = 326, // If set, police will not perform the CTaskShockingPoliceInvestigate behavior on the ped
  DisableWritheShootFromGround = 327, // If set, the ped will no longer shoot while writhing
  LowerPriorityOfWarpSeats = 328, // If set the ped will only just the warp entry points if there are no animated entry points available
  DisableTalkTo = 329, // If set the ped can't be talked to
  DontBlip = 330, // If set the ped will not be blipped by the wanted system
  IsSwitchingWeapon = 331,
  IgnoreLegIkRestrictions = 332, // If set, the ped will ignore leg IK request restrictions for non-player peds
  ForceNoTimesliceIntelligenceUpdate = 333, // If set, the ped will never have their intelligence update time sliced across frames.
  JackedOutOfMyVehicle = 334,
  WentIntoCombatAfterBeingJacked = 335,
  DontActivateRagdollForVehicleGrab = 336,
  AllowTaskDoNothingTimeslicing = 339, // If set, this ped will timeslice it's DoNothing Task when computing default task.
  ForcedToStayInCoverDueToPlayerSwitch = 340,
  NotAllowedToJackAnyPlayers = 342, // If set, this ped will not be allowed to jack any other players (not synced)
  KilledByStandardMelee = 344,
  AlwaysLeaveTrainUponArrival = 345, // If set, this ped will always exit the train when it stops at a station.
  OnlyWritheFromWeaponDamage = 347, // If set, Only allow ped to wrothe from weapon damage, not from other stuff, like small vehicle impacts
  UseSloMoBloodVfx = 348, // If set, this ped will use slo mo blood vfx instead of the normal ones (these effects must be included in the script particle asset)
  EquipJetpack = 349,
  PreventDraggedOutOfCarThreatResponse = 350, // Don't do threat response when dragged out of a car
  ScriptHasCompletelyDisabledCollision = 351,
  ForceDeepSurfaceCheck = 356, // Don't do distance from camera culling of the deep surface check, needed for detecting snow, mud, etc.
  DisableDeepSurfaceAnims = 357, // Disable deep surface anims to prevent them slowing ped down.
  DontBlipNotSynced = 358, // If set the ped will not be blipped by the wanted system, this will not be synced and be set on clones so the behaviour can be changed per player
  IsDuckingInVehicle = 359, // Query only, see if the ped is ducking in a vehicle
  PreventAutoShuffleToTurretSeat = 360, // If set the ped will not automatically shuffle to the turret seat when it becomes free
  DisableEventInteriorStatusCheck = 361, // Disables the ignore events based on interior status check which normally has peds inside ignore events from outside
  HasReserveParachute = 362,
  UseReserveParachute = 363,
  TreatDislikeAsHateWhenInCombat = 364, // If the ped this is set on is in combat then any dislike feeling they have towards other peds will be treated as a hate feeling
  OnlyUpdateTargetWantedIfSeen = 365, // Law with this set will only update the WL is the target player is seen. This includes on combat initialization as well as during normal LOS checks (ignoring "last known position" reports)
  AllowAutoShuffleToDriversSeat = 366, // Allows this ped to auto shuffle to the driver seat of a vehicle if the driver is dead (law and MP peds would do this normally)
  DontActivateRagdollFromSmokeGrenade = 367,
  PreventReactingToSilencedCloneBullets = 372, // If set prevents the ped from reacting to silenced bullets fired from network clone peds (use for peds where stealth kills are important)
  DisableInjuredCryForHelpEvents = 373, // Blocks ped from creating the injured cry for help events (run over, tazed or melee would usually do this)
  NeverLeaveTrain = 374, // Prevents peds riding trains from getting off them
  DontDropJetpackOnDeath = 375, // Prevents ped dropping jetpack when they die
  DisableAutoEquipHelmetsInBikes = 380, // Prevents ped from auto-equipping helmets when entering a bike (includes quadbikes)
  DisableAutoEquipHelmetsInAircraft = 381, // Prevents ped from auto-equipping helmets when entering an aircraft.
  PreferNoPriorityRemoval = 384,
  IsClimbingLadder = 388,
  HasBareFeet = 389, // Flag to indicate that player has no shoes(used for first person aiming camera)
  UNUSED_REPLACE_ME_2 = 390, //
  GoOnWithoutVehicleIfItIsUnableToGetBackToRoad = 391, // It will force the ped to abandon its vehicle (when using TaskGoToPointAnyMeans) if it is unable to get back to road
  BlockDroppingHealthSnacksOnDeath = 392, // This will block health pickups from being created when the ped dies.
  ResetLastVehicleOnVehicleExit = 393,
  ForceThreatResponseToNonFriendToFriendMeleeActions = 394, // Forces threat response to melee actions from non friend to friend peds.
  DontRespondToRandomPedsDamage = 395, // Do not respond to random peds damage.
  AllowContinuousThreatResponseWantedLevelUpdates = 396, // Shares the same logic of OnlyUpdateTargetWantedIfSeen but will continue to check even after the initial WL is set
  KeepTargetLossResponseOnCleanup = 397, // The target loss response will not be reset to exit task on cleanup if this is set
  PlayersDontDragMeOutOfCar = 398, // Similar to DontDragMeOutCar except it will still allow AI to drag the ped out of a vehicle
  BroadcastRespondedToThreatWhenGoingToPointShooting = 399, // Whenever the ped starts shooting while going to a point, it trigger a responded to threat broadcast.
  IgnorePedTypeForIsFriendlyWith = 400, // If this is set then IsFriendlyWith will ignore the ped type checks (i.e. two PEDTYPE_COP peds are not automatically friendly)
  TreatNonFriendlyAsHateWhenInCombat = 401, // Any non friendly ped will be considered as hated instead when in combat
  DontLeaveVehicleIfLeaderNotInVehicle = 402, // Supresses "LeaderExistedCarAsDriver" events. Ped won't exit vehicle if leader isn't in it as well.
  AllowMeleeReactionIfMeleeProofIsOn = 404, //Allow melee reaction to come through even if proof is on
  UseNormalExplosionDamageWhenBlownUpInVehicle = 407, // If this is set, ped won't be instantly killed if vehicle is blown up. Instead, they will take normal explosive damage and be forced to exit the vehicle if they're still alive.
  DisableHomingMissileLockForVehiclePedInside = 408, // Blocks locking on of the vehicle that the ped is inside.
  DisableTakeOffScubaGear = 409, // Disable taking off the scuba gear. Same as DisableTakeOffScubaGear but on a config flag.
  IgnoreMeleeFistWeaponDamageMult = 410, // Melee fist weapons (ie knuckle duster) won't apply relative health damage scaler (MeleeRightFistTargetHealthDamageScaler in weapon info).
  LawPedsCanFleeFromNonWantedPlayer = 411, // Law peds will be triggered to flee if player triggers an appropriate event (even if ped is not wanted) instead of entering combat. NB: Only synced over the network when set on players.
  ForceBlipSecurityPedsIfPlayerIsWanted = 412, // Forces security peds (not cop peds) to be blipped on the minimap if the player is wanted. Set this on the local player.
  UseGoToPointForScenarioNavigation = 414, // Don't use nav mesh for navigating to scenario points. DLC Hack for yachts
  DontClearLocalPassengersWantedLevel = 415, // Don't clear local ped's wanted level when remote ped in the same car has his wanted level cleared by script.
  BlockAutoSwapOnWeaponPickups = 416, // Block auto weapon swaps for weapon pickups.
  ThisPedIsATargetPriorityForAI = 417, // Increase AI targeting score for peds with this flag.
  IsSwitchingHelmetVisor = 418, // Indicates ped is using switch helmet visor up/down anim
  ForceHelmetVisorSwitch = 419, // Indicates ped is using switch helmet visor up/down anim
  UseOverrideFootstepPtFx = 421, // Overrides ped footstep particle effects with the overriden footstep effect
  DisableVehicleCombat = 422, // Disables vehicle combat.
  TreatAsFriendlyForTargetingAndDamage = 423,
  AllowBikeAlternateAnimations = 424, // Allows transition into bike alternate animations (PI menu option)
  TreatAsFriendlyForTargetingAndDamageNonSynced = 425,
  UseLockPickVehicleEntryAnimations = 426, // Use Franklin's alternate lock picking animations for forced entry.
  IgnoreInteriorCheckForSprinting = 427, // When set, player will be able to sprint inside interriors even if it is tagged to prevent it.
  SwatHeliSpawnWithinLastSpottedLocation = 428, // When set, swat helicopters will spawn within last spotted location instead of actual ped location (and target is a player)
  DisableStartEngine = 429, // Prevents ped from playing start engine anims (and turning engine on)
  IgnoreBeingOnFire = 430, // Makes ped ignore being on fire (fleeing, reacting to CEventOnFire event)
  DisableTurretOrRearSeatPreference = 431, // Disables turret seat and activity seat preference for vehicle entry for local player
  DisableWantedHelicopterSpawning = 432, // Will not spawn wanted helicopters to chase after this target
  UseTargetPerceptionForCreatingAimedAtEvents = 433, // Will only create aimed at events if player is within normal perception of the target
  DisableHomingMissileLockOn = 434, // Will prevent homing lockon on the ped.
  ForceIgnoreMaxMeleeActiveSupportCombatants = 435, //Ignore max number of active support combatants and let ped join them as such
  StayInDefensiveAreaWhenInVehicle = 436, // Will try to stay within set defensive area while driving a vehicle
  DontShoutTargetPosition = 437, // Will prevent the ped from communicating target position to all other friendly peds
  DisableHelmetArmor = 438, // Will apply full headshot damage, regardless if ped has a helmet (or armored one)
  PreventVehExitDueToInvalidWeapon = 441, // Will prevent ped from automatically being forced out of vehicle due to weapon being invalid (e.g. turret seats after going into water)
  IgnoreNetSessionFriendlyFireCheckForAllowDamage = 442, // Will ignore the friendly fire setting set by NETWORK_SET_FRIENDLY_FIRE_OPTION when checking if ped can be damaged
  DontLeaveCombatIfTargetPlayerIsAttackedByPolice = 443, // Will make ped stay in combat even if the player hes targeting starts being attacked by cops
  CheckLockedBeforeWarp = 444, // Will check when entering a vehicle if it is locked before warping
  DontShuffleInVehicleToMakeRoom = 445, // Will prevent a player from shuffling across to make room if another player is entering from the same side
  GiveWeaponOnGetup = 446, // Will give the ped a weapon to use once their weapon is removed for getups
  DontHitVehicleWithProjectiles = 447, // Ped fired projectiles will ignore the vehicle they are in
  DisableForcedEntryForOpenVehiclesFromTryLockedDoor = 448, // Will prevent ped from forcing entry into cars that are open from TryLockedDoor state
  FiresDummyRockets = 449, // his ped will fire rockets that explode when close to its target, and won't affect it
  DecoyPed = 451, // Will make this ped a decoy ped that will focus targeting
  HasEstablishedDecoy = 452, // This ped has created a decoy
  BlockDispatchedHelicoptersFromLanding = 453, // Will prevent dispatched helicopters from landing and dropping off peds
  DontCryForHelpOnStun = 454, // Will prevent peds from crying for help when shot with the stun gun
  CanBeIncapacitated = 456, // If set, the ped may be incapacitated
  DontChangeTargetFromMelee = 458, // If set, we wont set a new target after a melee attack
  RagdollFloatsIndefinitely = 460, // Prevents a dead ped from sinking
  BlockElectricWeaponDamage = 461, // Blocks electric weapon damage
}

// These flags are reset every frame
// match these with the enum in PedFlagsMeta.h
export enum PED_RESET_FLAG {
  DisablePlayerJumping = 46, // Disable jumping (exclusive from climbing).
  DisablePlayerVaulting = 47, // Disable climbing / vaulting (but not auto-vault, that's a seperate flag).
  AllowUpdateIfNoCollisionLoaded = 55, // Don't freeze this ped for not having bounds loaded around it
  DisableSecondaryAnimationTasks = 58, // Disable upper body animtion tasks such as shove ped and open door anims
  SearchForClosestDoor = 60, // Will check for the closest door in proximity and store it off
  SupressGunfireEvents = 62, // Supresses AI generating fire events, so civilians wont be shocked or react, for use in a shooting range for example
  InfiniteStamina = 63, // Currently just for mounts, but could be expanded to anything with stamina
  BlockWeaponReactionsUnlessDead = 64, // Stops the ped from reacting to damage events (such as shots / fires, etc). The ped will still take damage while this flag is active. Note: this does not block explosion reactions.
  ForcePlayerFiring = 65, // Forces player to fire even if they aren't pressing fire
  ForcePeekFromCover = 67, // Forces an actor that is in cover to continue (or start if they haven't yet) peeking
  ForcePedToStrafe = 69, // Forces an actor to strafe
  UseKinematicPhysics = 71, // Enables kinematic physics mode on this ped. This stops other physical objects from pushing the ped around, and causes the ped to push any physical objects out of its way when it moves into them.
  ClearLockonTarget = 72, // Clear the players lockon target next frame
  ForcePedToUseScriptCamHeading = 77, // forces a ped to the scripted camera heading instead of gameplay
  IgnoreTargetsCoverForLOS = 85, // When doing LOS checks to other peds we won't use the cover vantage position as the "target" position
  DisableCrouchWhileInCover = 88, // Force the crouch flag to return true while in cover.
  ForceRunningSpeedForFragSmashing = 91, // Forces a ped to apply forces to frags as if running on contact, to guarantee peds will smash through frag objects when playing custom anims
  ExtraLongWeaponRange = 95, // Force the bullets gun range to increase to 250m
  ForcePlayerToEnterVehicleThroughDirectDoorOnly = 96, // Forces the player to only use direct access when entering vehicles
  TaskCullExtraFarAway = 97, // Disable a ped getting cull from a vehicle from pretend occupants.
  DisablePlayerAutoVaulting = 102, // If this flag is set on a ped it will not attempt to autovault
  UseBulletPenetration = 107, // If this flag is set on a ped it will use the bullet shoot through code
  ForceAimAtHead = 108, // Force all attackers to target the head of this ped
  IsInStationaryScenario = 109, // Inform avoidance code that this ped isn't going anywhere and should be steered around rather than waited for
  DisableSeeThroughChecksWhenTargeting = 112, // Any targeting LoS checks will fail if any materials with 'see through' materials found.
  PuttingOnHelmet = 113, // When set, the ped is putting on a helmet. DONT SET THIS only query it
  PanicInVehicle = 120, // When set, the ped will play panic animations if in a vehicle
  DisableMelee = 122,
  CannotBeTargetedByAI = 124, // When set, this ped cannot be added to the targeting list of AI peds, will be removed if already in the list and is thought of as not able to be attacked
  ForceInjuryAfterStunned = 126, // Forces this ped to the injured state after being stunned
  BlockWeaponFire = 128, // Prevent the ped from shooting a weapon
  ExpandPedCapsuleFromSkeleton = 129, // Set the ped capsule radius based on skeleton
  DisableWeaponLaserSight = 130, // Toggle the weapon laser sight off for this frame
  SuspendInitiatedMeleeActions = 149, // Temporarily suspend any melee actions this frame (does not include hit reactions). Use DisableMelee to turn it off completely
  SuppressInAirEvent = 150, // Prevents ped from getting the in air event the next frame
  AllowTasksIncompatibleWithMotion = 151, // If set, allows ped to have tasks incompatible with its current motion
  SuppressLethalMeleeActions = 155, // This will suppress any melee action that is considered lethal (RA_IS_LETHAL, defined in action_table.meta)
  InstantBlendToAim = 156, // Blend straight into an aim instantly, if starting a gun task this frame
  MakeHeadInvisble = 166, // If set, scale the head of the ped to 0.001
  NoAutoRunWhenFiring = 167, // Don't auto run when NoAutoRunWhenFiring is set
  DisableSteeringAroundNavMeshEdges = 172, // Don't let this ped take navmesh edges into account when performing their low-level steering/avoidance code
  DisableTakeOffParachutePack = 177, // Disable taking off the parachute pack
  ForceCombatTaunt = 179, // If this ped has the INSULT special ability, and this flag is set, he will always use the combat taunt when the special is activated
  IgnoreCombatTaunts = 180, // This ped will ignore combat taunts
  PreventAllMeleeTakedowns = 187, // Will temporarily prevent any takedown from being performed on this ped
  PreventFailedMeleeTakedowns = 188, // Will temporarily prevent any failed takedown from being performed on this ped
  UseTighterAvoidanceSettings = 190, // Will temporarily force min avoidance on this ped.  will brush other peds but avoid a bit
  DisableDropDowns = 195, // Disable drop downs for this ped
  DisableTakeOffScubaGear = 197, // Disable taking off the scuba gear
  DisableActionMode = 200, // Disable combat anims for ped.
  UseHeadOrientationForPerception = 206, // Use the ped's head orientation for perception tests
  DisableJumpRagdollOnCollision = 210, // The player will no longer auto-ragdoll when colliding with objects, peds, etc. while jumping
  DisableParachuting = 217, // Disable parachuting for the ped
  KeepParachutePackOnAfterTeleport = 222, // Keep the parachute pack on after a teleport
  DontRaiseFistsWhenLockedOn = 223, // Whether or not you want the player ped to use the new front melee logic in TODO #981120
  PreferMeleeBodyIkHitReaction = 224, // This will prefer all melee hit reactions to use body ik hit reactions if ragdoll is not selected
  DisableFriendlyGunReactAudio = 227, // If set, disables friendly responses to gunshots/being aimed at.
  DisableAgitationTriggers = 228, // Disables agitation triggers
  DisableNMForRiverRapids = 234, // Disable NM reactions to fast moving water for this ped
  PreventGoingIntoStillInVehicleState = 236, // If set, the ped will not go into the still in vehicle pose
  UseFastEnterExitVehicleRates = 237, // If set, the ped will get in and out of vehicles faster (same as in mp)
  DisableAgitation = 239, // Disables agitation
  DisableTalk = 240, // Disables talking
  UseProbeSlopeStairsDetection = 247, // Uses more expensive slope/stairs detection
  DisableVehicleDamageReactions = 248, // Disables vehicle damage reactions
  DisablePotentialBlastReactions = 249, // Disables potential blast reactions
  OnlyAllowLeftArmDoorIk = 250, // When set along side open door ik, will only use the left hand
  OnlyAllowRightArmDoorIk = 251, // When set along side open door ik, will only use the left hand
  DisableFlashLight = 253, // When set, the flash light on a Ai weapon will be turned off
  ForceEnableFlashLightForAI = 258, // When set, the ai ped will enable their flash light
  DisableCombatAudio = 262, // Disables combat audio
  DisableCoverAudio = 263, // Disables cover audio
  EnablePressAndReleaseDives = 271, // Player has to press and hold dive button to dive in water
  OnlyExitVehicleOnButtonRelease = 272, // Only allows player to exit vehicle when button is released rather than pressed or held
  ConsiderAsPlayerCoverThreatWithoutLOS = 282, // Considered as a threat as part of player cover search even if they can't see the player
  BlockCustomAIEntryAnims = 283, // Disables ped from using custom ai cover entry animations
  IgnoreVehicleEntryCollisionTests = 284, // Ignore the vehicle entry collision tests for this ped
  PreventGoingIntoShuntInVehicleState = 287, // If set, the ped will not go into the shunt in vehicle pose
  EnableVoiceDrivenMouthMovement = 302, // If set, turn on the voice driven mouth movement
  UseTighterEnterVehicleSettings = 304, // To have peds do better vehicle entries when in a group and interfered by other peds, use carefully though
  InRaceMode = 305, // Set when the player is in the races to make the player more interesting to look at.
  DisableAmbientMeleeMoves = 306, // Disable ambient (initial) melee moves
  AllowSpecialAbilityInVehicle = 308, // Allows the player to trigger the special ability while in a vehicle
  DisableInVehicleActions = 309, // Prevents ped from doing in vehicle actions like closing door, hotwiring, starting engine, putting on helmet etc
  ForceInstantSteeringWheelIkBlendIn = 310, // Forces ped to blend in steering wheel ik instantly rather than over time
  IgnoreThreatEngagePlayerCoverBonus = 311, // Ignores the bonus score for selecting cover that the player can engage the enemy at
  DontCloseVehicleDoor = 313, // Prevents the ped from closing the vehicle door of the car they're inside
  SkipExplosionOcclusion = 314, // Explosions can't be blocked by map collision when damaging this ped
  MeleeStrikeAgainstNonPed = 316, // Set when the ped has performed a melee strike and hit any non ped material
  IgnoreNavigationForDoorArmIK = 317, // We will not attempt to walk around doors when using arm IK
  DisableAimingWhileParachuting = 318, // Disable aiming while parachuting
  DisablePedCollisionWithPedEvent = 319, // Disable hit reaction due to colliding with a ped
  IgnoreVelocityWhenClosingVehicleDoor = 320, // Will ignore the vehicle speed threshold and close the door anyway
  SkipOnFootIdleIntro = 321, // Skip idle intro
  DontWalkRoundObjects = 322, // Don't walk round objects that we collide with whilst moving
  DisablePedEnteredMyVehicleEvents = 323, // Disable ped entered my vehicle events
  DisableInVehiclePedVariationBlocking = 326, // Will allow ped variations to be rendered in vehicles, even if marked otherwise
  ReduceEffectOfVehicleRamControlLoss = 327, // When on a mission this reset flag will slightly reduce the amount of time the player loses control of their vehicle when hit by an AI ped
  DisablePlayerMeleeFriendlyAttacks = 328, // Another flag to disable friendly attack from the player. Set on the opponent you would like it to be disabled on.
  IsMeleeTargetUnreachable = 330, // Set when the melee target has been deemed unreachable (AI only)
  DisableAutoForceOutWhenBlowingUpCar = 331, // Disable automatically forcing player to exit a vehicle in a network game when blowing up vehicle
  DisableDustOffAnims = 334, // Disable amient dust off animations
  DisableMeleeHitReactions = 335, // This ped will refrain from ever performing a melee hit reaction
  AllowHeadPropInVehicle = 337, // This overrides PV_FLAG_NOT_IN_CAR set on any head prop and stops it from being removed when getting into the vehicle
  DontQuitMotionAiming = 339,
  OpenDoorArmIK = 342, // Reset version of OpenDoorArmIK, which sets if the ped should enable open door arm IK.
  UseTighterTurnSettingsForScript = 343, // Force use of tighter turn settings in locomotion task
  DisableVoiceDrivenMouthMovement = 346, // If set, turn off the voice driven mouth movement (overrides EnableVoiceDrivenMouthMovement)
  SteerIntoSkids = 347, // If set, steer into skids while driving
  AllowOpenDoorIkBeforeFullMovement = 348, // When set, code will ignore the logic that requires the ped to be in CTaskHumanLocomotion::State_Moving
  AllowHomingMissileLockOnInVehicle = 349, // When set, code will bypass rel settings and allow a homing lock on to this ped when they are in a vehicle
  AllowCloneForcePostCameraAIUpdate = 350,
  DisableHighHeels = 351, // Force the high heels DOF to be 0
  DontUseSprintEnergy = 353, // Player does not get tired when sprinting
  DisableMaterialCollisionDamage = 355, // Don't be damaged by touching dangerous material (e.g. electic generator)
  DisableMPFriendlyLockon = 356, // Don't target friendly players in MP
  DisableMPFriendlyLethalMeleeActions = 357, // Don't melee kill friendly players in MP
  IfLeaderStopsSeekCover = 358, // If our leader stops, try and seek cover if we can
  UseInteriorCapsuleSettings = 362, // Use Interior capsule settings
  IsClosingVehicleDoor = 363, // Ped is closing a vehicle door
  DisableWallHitAnimation = 371, // Disable stuck wall hit animation for the ped this frame
  PlayAgitatedAnimsInVehicle = 372, // When set, the ped will play panic animations if in a vehicle
  IsSeatShuffling = 373, // Ped is shuffling seat
  AllowControlRadioInAnySeatInMP = 376, // Allows ped in any seat to control the radio (in MP only)
  DisableSpycarTransformation = 377, // Blocks ped from manually transforming spycar to/from car/sub modes
  BlockHeadbobbingToRadio = 379, //Blocks ped from headbobbing to radio music in vehicles
  ForceExtraLongBlendInForPedSkipIdleCoverTransition = 381, //When putting a ped directly into cover, the ped will blend in the new cover anims slowly to prevent a pose pop, see B*1788366
  DisableAssistedAimLockon = 390, // Don't ever try to lock on to this ped with cinematic aim
  NoCollisionDamageFromOtherPeds = 394, // Any ped this is set on won't register damage from collisions against other peds.
  DontSuppressUseNavMeshToNavigateToVehicleDoorWhenVehicleInWater = 398, // For thing that inherit from boats only
  InstantBlendToAimNoSettle = 401, // If true it avoids playing the settle anim when aiming
  ForceScriptedCameraLowCoverAngleWhenEnteringCover = 406, // For first person mode, when the player enters low cover, will orientate camera to face left or right rather than into cover
  DisableMeleeWeaponSelection = 417,
  WaypointPlaybackSlowMoreForCorners = 418, // Allows peds following waypoint recordings to slow down more for corners. (Achieves same effect as the EWAYPOINT_SUPPRESS_EXACTSTOP flag, which is passed into TASK_FOLLOW_WAYPOINT_RECORDING).
  UseBulletPenetrationForGlass = 420, //Ped will use bullet penetration code when glass material is hit.
  CanBePinnedByFriendlyBullets = 423, // If set on a ped then they are allowed to be pinned by bullets from friendly peds
  DisableSpikeStripRoadBlocks = 425, // Blocks road blocks with spike strips from spawning
  IsLowerPriorityMeleeTarget = 428, // Peds marked with this flag will only be able to be hit by the player if the player explicitly presses the melee button
  ForceScanForEventsThisFrame = 429, // Disable timeslicing of event scanning this frame (see url:bugstar:2100836 for an example situation where this is useful)
  ForceAutoEquipHelmetsInAicraft = 432, // Forces ped to auto-equip a helmet when entering an aircraft. Overrides DisableAutoEquipHelmetsInAicraft which is set in the interaction menu.
  BlockRemotePlayerRecording = 433, // Flag used by replay editor to disable recording specified remote players (for url:bugstar:2218297).
  UseFirstPersonVehicleAnimsIfFPSCamNotDominant = 435, // allow FPS vehicle anims even if FPS camera isn't dominant
  ForceIntoStandPoseOnJetski = 436, // allow FPS vehicle anims even if FPS camera isn't dominant
  SuppressTakedownMeleeActions = 438, // This will suppress all takedown melee actions (RA_IS_TAKEDOWN or RA_IS_STEALTH_KILL, defined in action_table.meta)
  InvertLookAroundControls = 439, // Inverts lookaround controls (right stick / mouse) for this player
  IgnoreCombatManager = 440, // Allows attacking ped to engage another entity without waiting for its turn (if there's multiple attackers)
  UseBlendedCamerasOnUpdateFpsCameraRelativeMatrix = 441, //Check if there is an active camera blending and use the blended camera frame when compute the FPS camera relative matrix.
  ForceMeleeCounter = 442, //Forces the ped to perform a dodge and a counter move if it's attacked.
  SuppressNavmeshForEnterVehicleTask = 444, //Suppress navmesh navigation in TaskEnterVehicle. Will use gotopoint or bail if cant use that
  DisableShallowWaterBikeJumpOutThisFrame = 445, // Prevents the ped from jumping out of the vehicle in shallow water if the bike is submerged
  DisablePlayerCombatRoll = 446, // Prevents the player from performing a combat roll.
  IgnoreDetachSafePositionCheck = 447, // Will ignore safe position check on detaching the ped
  DisableEasyLadderConditions = 448, // Prevents the more forgiving MP ladder detection settings from being used, and forces SP settings.
  PlayerIgnoresScenarioSpawnRestrictions = 449, // Makes local player ignore certain scenario spawn restrictions on scenarios that respect this flag
  UsingDrone = 450, // Indicates player is using Drone from Battle DLC
  UseScriptedWeaponFirePosition = 452, // Will use scripted firing position on the clones of this ped on other machines
  UseExtendedRagdollCollisionCalculator = 454, // Use extended logic for determining damage instigator for ragdoll collisions
  PreventLockonToFriendlyPlayers = 455, // Prevent the player locking on to friendly players
  OnlyAbortScriptedAnimOnMovementByInput = 456, //  Modifies AF_ABORT_ON_PED_MOVEMENT to only trigger an abort when movement would be caused by player input
  PreventAllStealthKills = 457, // Prevents stealth take downs from being preformed on a ped
  BlockFallTaskFromExplosionDamage = 458, // Prevent peds from entering a fall task if affected by explosion damage
  AllowPedRearEntry = 459, // Mimics the behaviour of boss peds by holding the button for entering the rear seats
}

export enum FLEE_ATTRIBUTE { //Set a specific flee attribute
  FA_USE_COVER = 1,
  FA_USE_VEHICLE = 2,
  FA_CAN_SCREAM = 4,
  FA_PREFER_PAVEMENTS = 8,
  FA_WANDER_AT_END = 16,
  FA_LOOK_FOR_CROWDS = 32,
  FA_RETURN_TO_ORIGNAL_POSITION_AFTER_FLEE = 64,
  FA_DISABLE_HANDS_UP = 128,
  FA_UPDATE_TO_NEAREST_HATED_PED = 256,
  FA_NEVER_FLEE = 512,
  FA_DISABLE_COWER = 1024,
  FA_DISABLE_EXIT_VEHICLE = 2048,
  FA_DISABLE_REVERSE_IN_VEHICLE = 4096,
  FA_DISABLE_ACCELERATE_IN_VEHICLE = 8192,
  FA_DISABLE_FLEE_FROM_INDIRECT_THREATS = 16384,
  FA_COWER_INSTEAD_OF_FLEE = 32768,
  FA_FORCE_EXIT_VEHICLE = 65536,
  FA_DISABLE_HESITATE_IN_VEHICLE = 131072,
  FA_DISABLE_AMBIENT_CLIPS = 262144,
}

export enum COMBAT_ATTRIBUTE { //Set a specific combat attribute
  CA_INVALID = -1,
  CA_USE_COVER = 0, // AI will only use cover if this is set
  CA_USE_VEHICLE = 1, // AI will only use vehicles if this is set
  CA_DO_DRIVEBYS = 2, // AI will only driveby from a vehicle if this is set
  CA_LEAVE_VEHICLES = 3, // Will be forced to stay in a ny vehicel if this isn't set
  CA_CAN_USE_DYNAMIC_STRAFE_DECISIONS = 4, // This ped can make decisions on whether to strafe or not based on distance to destination, recent bullet events, etc.
  CA_ALWAYS_FIGHT = 5, // Ped will always fight upon getting threat response task
  CA_FLEE_WHILST_IN_VEHICLE = 6, // If in combat and in a vehicle, the ped will flee rather than attacking
  CA_JUST_FOLLOW_VEHICLE = 7, // If in combat and chasing in a vehicle, the ped will keep a distance behind rather than ramming
  CA_PLAY_REACTION_ANIMS = 8, // Deprecated
  CA_WILL_SCAN_FOR_DEAD_PEDS = 9, // Peds will scan for and react to dead peds found
  CA_IS_A_GUARD = 10, // Deprecated
  CA_JUST_SEEK_COVER = 11, // The ped will seek cover only
  CA_BLIND_FIRE_IN_COVER = 12, // Ped will only blind fire when in cover
  CA_AGGRESSIVE = 13, // Ped may advance
  CA_CAN_INVESTIGATE = 14, // Ped can investigate events such as distant gunfire, footsteps, explosions etc
  CA_CAN_USE_RADIO = 15, // Ped can use a radio to call for backup (happens after a reaction)
  CA_CAN_CAPTURE_ENEMY_PEDS = 16, // Deprecated
  CA_ALWAYS_FLEE = 17, // Ped will always flee upon getting threat response task
  CA_CAN_TAUNT_IN_VEHICLE = 20, // Ped can do unarmed taunts in vehicle
  CA_CAN_CHASE_TARGET_ON_FOOT = 21, // Ped will be able to chase their targets if both are on foot and the target is running away
  CA_WILL_DRAG_INJURED_PEDS_TO_SAFETY = 22, // Ped can drag injured peds to safety
  CA_REQUIRES_LOS_TO_SHOOT = 23, // Ped will require LOS to the target it is aiming at before shooting
  CA_USE_PROXIMITY_FIRING_RATE = 24, // Ped is allowed to use proximity based fire rate (increasing fire rate at closer distances)
  CA_DISABLE_SECONDARY_TARGET = 25, // Normally peds can switch briefly to a secondary target in combat, setting this will prevent that
  CA_DISABLE_ENTRY_REACTIONS = 26, // This will disable the flinching combat entry reactions for peds, instead only playing the turn and aim anims
  CA_PERFECT_ACCURACY = 27, // Force ped to be 100% accurate in all situations (added by Jay Reinebold)
  CA_CAN_USE_FRUSTRATED_ADVANCE = 28, // If we don't have cover and can't see our target it's possible we will advance, even if the target is in cover
  CA_MOVE_TO_LOCATION_BEFORE_COVER_SEARCH = 29, // This will have the ped move to defensive areas and within attack windows before performing the cover search
  CA_CAN_SHOOT_WITHOUT_LOS = 30, // Allow shooting of our weapon even if we don't have LOS (this isn't X-ray vision as it only affects weapon firing)
  CA_MAINTAIN_MIN_DISTANCE_TO_TARGET = 31, // Ped will try to maintain a min distance to the target, even if using defensive areas (currently only for cover finding + usage)
  CA_CAN_USE_PEEKING_VARIATIONS = 34, // Allows ped to use steamed variations of peeking anims
  CA_DISABLE_PINNED_DOWN = 35, // Disables pinned down behaviors
  CA_DISABLE_PIN_DOWN_OTHERS = 36, // Disables pinning down others
  CA_OPEN_COMBAT_WHEN_DEFENSIVE_AREA_IS_REACHED = 37, // When defensive area is reached the area is cleared and the ped is set to use defensive combat movement
  CA_DISABLE_BULLET_REACTIONS = 38, // Disables bullet reactions
  CA_CAN_BUST = 39, // Allows ped to bust the player
  CA_IGNORED_BY_OTHER_PEDS_WHEN_WANTED = 40, // This ped is ignored by other peds when wanted
  CA_CAN_COMMANDEER_VEHICLES = 41, // Ped is allowed to "jack" vehicles when needing to chase a target in combat
  CA_CAN_FLANK = 42, // Ped is allowed to flank
  CA_SWITCH_TO_ADVANCE_IF_CANT_FIND_COVER = 43, // Ped will switch to advance if they can't find cover
  CA_SWITCH_TO_DEFENSIVE_IF_IN_COVER = 44, // Ped will switch to defensive if they are in cover
  CA_CLEAR_PRIMARY_DEFENSIVE_AREA_WHEN_REACHED = 45, // Ped will clear their primary defensive area when it is reached
  CA_CAN_FIGHT_ARMED_PEDS_WHEN_NOT_ARMED = 46, // Ped is allowed to fight armed peds when not armed
  CA_ENABLE_TACTICAL_POINTS_WHEN_DEFENSIVE = 47, // Ped is not allowed to use tactical points if set to use defensive movement (will only use cover)
  CA_DISABLE_COVER_ARC_ADJUSTMENTS = 48, // Ped cannot adjust cover arcs when testing cover safety (atm done on corner cover points when  ped usingdefensive area + no LOS)
  CA_USE_ENEMY_ACCURACY_SCALING = 49, // Ped may use reduced accuracy with large number of enemies attacking the same local player target
  CA_CAN_CHARGE = 50, // Ped is allowed to charge the enemy position
  CA_REMOVE_AREA_SET_WILL_ADVANCE_WHEN_DEFENSIVE_AREA_REACHED = 51, // When defensive area is reached the area is cleared and the ped is set to use will advance movement
  CA_USE_VEHICLE_ATTACK = 52, // Use the vehicle attack mission during combat (only works on driver)
  CA_USE_VEHICLE_ATTACK_IF_VEHICLE_HAS_MOUNTED_GUNS = 53, // Use the vehicle attack mission during combat if the vehicle has mounted guns (only works on driver)
  CA_ALWAYS_EQUIP_BEST_WEAPON = 54, // Always equip best weapon in combat
  CA_CAN_SEE_UNDERWATER_PEDS = 55, // Ignores in water at depth visibility check
  CA_DISABLE_AIM_AT_AI_TARGETS_IN_HELIS = 56, // Will prevent this ped from aiming at any AI targets that are in helicopters
  CA_DISABLE_SEEK_DUE_TO_LINE_OF_SIGHT = 57, // Disables peds seeking due to no clear line of sight
  CA_DISABLE_FLEE_FROM_COMBAT = 58, // To be used when releasing missions peds if we don't want them fleeing from combat (mission peds already prevent flee)
  CA_DISABLE_TARGET_CHANGES_DURING_VEHICLE_PURSUIT = 59, // Disables target changes during vehicle pursuit
  CA_CAN_THROW_SMOKE_GRENADE = 60, // Ped may throw a smoke grenade at player loitering in combat
  CA_CLEAR_AREA_SET_DEFENSIVE_IF_DEFENSIVE_CANNOT_BE_REACHED = 62, // Will clear a set defensive area if that area cannot be reached
  CA_DISABLE_BLOCK_FROM_PURSUE_DURING_VEHICLE_CHASE = 64, // Disable block from pursue during vehicle chases
  CA_DISABLE_SPIN_OUT_DURING_VEHICLE_CHASE = 65, // Disable spin out during vehicle chases
  CA_DISABLE_CRUISE_IN_FRONT_DURING_BLOCK_DURING_VEHICLE_CHASE = 66, // Disable cruise in front during block during vehicle chases
  CA_CAN_IGNORE_BLOCKED_LOS_WEIGHTING = 67, // Makes it more likely that the ped will continue targeting a target with blocked los for a few seconds
  CA_DISABLE_REACT_TO_BUDDY_SHOT = 68, // Disables the react to buddy shot behaviour.
  CA_PREFER_NAVMESH_DURING_VEHICLE_CHASE = 69, // Prefer pathing using navmesh over road nodes
  CA_ALLOWED_TO_AVOID_OFFROAD_DURING_VEHICLE_CHASE = 70, // Ignore road edges when avoiding
  CA_PERMIT_CHARGE_BEYOND_DEFENSIVE_AREA = 71, // Permits ped to charge a target outside the assigned defensive area.
  CA_USE_ROCKETS_AGAINST_VEHICLES_ONLY = 72, // This ped will switch to an RPG if target is in a vehicle, otherwise will use alternate weapon.
  CA_DISABLE_TACTICAL_POINTS_WITHOUT_CLEAR_LOS = 73, // Disables peds moving to a tactical point without clear los
  CA_DISABLE_PULL_ALONGSIDE_DURING_VEHICLE_CHASE = 74, // Disables pull alongside during vehicle chase
  CA_DISABLE_ALL_RANDOMS_FLEE = 78, // If set on a ped, they will not flee when all random peds flee is set to TRUE (they are still able to flee due to other reasons)
  CA_WILL_GENERATE_DEAD_PED_SEEN_SCRIPT_EVENTS = 79, // This ped will send out a script DeadPedSeenEvent when they see a dead ped
  CA_USE_MAX_SENSE_RANGE_WHEN_RECEIVING_EVENTS = 80, // This will use the receiving peds sense range rather than the range supplied to the communicate event
  CA_RESTRICT_IN_VEHICLE_AIMING_TO_CURRENT_SIDE = 81, // When aiming from a vehicle the ped will only aim at targets on his side of the vehicle
  CA_USE_DEFAULT_BLOCKED_LOS_POSITION_AND_DIRECTION = 82, // LOS to the target is blocked we return to our default position and direction until we have LOS (no aiming)
  CA_REQUIRES_LOS_TO_AIM = 83, // LOS to the target is blocked we return to our default position and direction until we have LOS (no aiming)
  CA_CAN_CRUISE_AND_BLOCK_IN_VEHICLE = 84, // Allow vehicles spawned infront of target facing away to enter cruise and wait to block approaching target
  CA_PREFER_AIR_COMBAT_WHEN_IN_AIRCRAFT = 85, // Peds flying aircraft will prefer to target other aircraft over entities on the ground
  CA_ALLOW_DOG_FIGHTING = 86, //Allow peds flying aircraft to use dog fighting behaviours
  CA_PREFER_NON_AIRCRAFT_TARGETS = 87, // This will make the weight of targets who aircraft vehicles be reduced greatly compared to targets on foot or in ground based vehicles
  CA_PREFER_KNOWN_TARGETS_WHEN_COMBAT_CLOSEST_TARGET = 88, //When peds are tasked to go to combat, they keep searching for a known target for a while before forcing an unknown one
  CA_FORCE_CHECK_ATTACK_ANGLE_FOR_MOUNTED_GUNS = 89, // Only allow mounted weapons to fire if within the correct attack angle (default 25-degree cone). On a flag in order to keep exiting behaviour and only fix in specific cases.
  CA_BLOCK_FIRE_FOR_VEHICLE_PASSENGER_MOUNTED_GUNS = 90, // Blocks the firing state for passenger-controlled mounted weapons. Existing flags CA_USE_VEHICLE_ATTACK and CA_USE_VEHICLE_ATTACK_IF_VEHICLE_HAS_MOUNTED_GUNS only work for drivers.
}
