import { Item } from "@shared/interfaces";
import { ItemFlags } from "../item-flags";
import { getWeaponData } from "../weapons";
import { ItemKey } from "../types";
import { AmmoItemKey } from "../ammo";
import { AmmoGroup, WeaponGroup } from "./weapon-groups";

export const FirearmWeapon = {
  ADVANCEDRIFLE: "advancedrifle",
  APPISTOL: "appistol",
  ASSAULTRIFLE: "assaultrifle",
  ASSAULTRIFLEMK2: "assaultriflemk2",
  ASSAULTSHOTGUN: "assaultshotgun",
  ASSAULTSMG: "assaultsmg",
  AUTOSHOTGUN: "autoshotgun",
  BULLPUPRIFLE: "bullpuprifle",
  BULLPUPRIFLEMK2: "bullpupriflemk2",
  BULLPUPSHOTGUN: "bullpupshotgun",
  CARBINERIFLE: "carbinerifle",
  CARBINERIFLEMK2: "carbineriflemk2",
  CERAMICPISTOL: "ceramicpistol",
  COMBATMG: "combatmg",
  COMBATMGMK2: "combatmgmk2",
  COMBATPDW: "combatpdw",
  COMBATPISTOL: "combatpistol",
  COMPACTLAUNCHER: "compactlauncher",
  COMPACTRIFLE: "compactrifle",
  DBSHOTGUN: "dbshotgun",
  DOUBLEACTION: "doubleaction",
  FIREEXTINGUISHER: "fireextinguisher",
  FIREWORK: "firework",
  FLAREGUN: "flaregun",
  GRENADELAUNCHER: "grenadelauncher",
  SMOKELAUNCHER: "smokelauncher",
  GUSENBERG: "gusenberg",
  HEAVYPISTOL: "heavypistol",
  HEAVYSHOTGUN: "heavyshotgun",
  HEAVYSNIPER: "heavysniper",
  HEAVYSNIPERMK2: "heavysnipermk2",
  HOMINGLAUNCHER: "hominglauncher",
  MACHINEPISTOL: "machinepistol",
  MARKSMANPISTOL: "marksmanpistol",
  MARKSMANRIFLE: "marksmanrifle",
  MARKSMANRIFLEMK2: "marksmanriflemk2",
  MG: "mg",
  MICROSMG: "microsmg",
  MINIGUN: "minigun",
  MINISMG: "minismg",
  MUSKET: "musket",
  NAVYREVOLVER: "navyrevolver",
  PISTOL: "pistol",
  PISTOL50: "pistol50",
  PISTOLMK2: "pistolmk2",
  PUMPSHOTGUN: "pumpshotgun",
  PUMPSHOTGUNMK2: "pumpshotgunmk2",
  RAILGUN: "railgun",
  RAYCARBINE: "raycarbine",
  RAYMINIGUN: "rayminigun",
  RAYPISTOL: "raypistol",
  REVOLVER: "revolver",
  REVOLVERMK2: "revolvermk2",
  RPG: "rpg",
  SAWNOFFSHOTGUN: "sawnoffshotgun",
  SMG: "smg",
  SMGMK2: "smgmk2",
  SNIPERRIFLE: "sniperrifle",
  SNSPISTOL: "snspistol",
  SNSPISTOLMK2: "snspistolmk2",
  SPECIALCARBINE: "specialcarbine",
  SPECIALCARBINEMK2: "specialcarbinemk2",
  STUNGUN: "stungun",
  VINTAGEPISTOL: "vintagepistol",
} as const;

export type FirearmWeaponItemKey = (typeof FirearmWeapon)[keyof typeof FirearmWeapon];

export type EquipedAmmo = {
  key: AmmoItemKey;
  clip: number;
  rest: number;
};

export type FirearmWeaponItem = {
  key: FirearmWeaponItemKey;

  customName?: string | null;
  durability: number;
  tint: number;
  components: number[];
  ammo?: EquipedAmmo | null;
};

export type FirearmWeaponItemInfo = {
  key: FirearmWeaponItemKey;
  hash: number;
  name: string;
  description: string;
  flags: ItemFlags;
  group: WeaponGroup;
  ammoGroup: AmmoGroup;
  clipSize: number;
  price: number;
  stats: {
    damage: number;
    rate: number;
    accuracy?: number;
    range: number;
    overall: number;
  };
};

export const firearmWeapons: Record<FirearmWeaponItemKey, FirearmWeaponItemInfo> = {
  advancedrifle: {
    key: "advancedrifle",
    hash: 2937143193,
    name: getWeaponData(2937143193).Name,
    description: getWeaponData(2937143193).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 14250,
    stats: {
      damage: 24,
      rate: 70,
      accuracy: 50,
      range: 45,
      overall: 47.8,
    },
  },
  appistol: {
    key: "appistol",
    hash: 584646201,
    name: getWeaponData(584646201).Name,
    description: getWeaponData(584646201).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 18,
    price: 5000,
    stats: {
      damage: 26,
      rate: 80,
      accuracy: 35,
      range: 30,
      overall: 38.2,
    },
  },
  assaultrifle: {
    key: "assaultrifle",
    hash: 3220176749,
    name: getWeaponData(3220176749).Name,
    description: getWeaponData(3220176749).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 8550,
    stats: {
      damage: 30,
      rate: 60,
      accuracy: 45,
      range: 45,
      overall: 44,
    },
  },
  assaultriflemk2: {
    key: "assaultriflemk2",
    hash: 961495388,
    name: getWeaponData(961495388).Name,
    description: getWeaponData(961495388).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 98750,
    stats: {
      damage: 33,
      rate: 60,
      accuracy: 45,
      range: 45,
      overall: 44.6,
    },
  },
  assaultshotgun: {
    key: "assaultshotgun",
    hash: 3800352039,
    name: getWeaponData(3800352039).Name,
    description: getWeaponData(3800352039).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 8,
    price: 10000,
    stats: {
      damage: 77,
      rate: 50,
      accuracy: 25,
      range: 15,
      overall: 35.4,
    },
  },
  assaultsmg: {
    key: "assaultsmg",
    hash: 4024951519,
    name: getWeaponData(4024951519).Name,
    description: getWeaponData(4024951519).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 30,
    price: 12550,
    stats: {
      damage: 23,
      rate: 55,
      accuracy: 45,
      range: 40,
      overall: 40.6,
    },
  },
  autoshotgun: {
    key: "autoshotgun",
    hash: 317205821,
    name: getWeaponData(317205821).Name,
    description: getWeaponData(317205821).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 10,
    price: 10000,
    stats: {
      damage: 77,
      rate: 50,
      accuracy: 25,
      range: 15,
      overall: 35.4,
    },
  },
  bullpuprifle: {
    key: "bullpuprifle",
    hash: 2132975508,
    name: getWeaponData(2132975508).Name,
    description: getWeaponData(2132975508).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 14500,
    stats: {
      damage: 32,
      rate: 70,
      accuracy: 45,
      range: 45,
      overall: 46,
    },
  },
  bullpupriflemk2: {
    key: "bullpupriflemk2",
    hash: 2228681469,
    name: getWeaponData(2228681469).Name,
    description: getWeaponData(2228681469).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 14500,
    stats: {
      damage: 35,
      rate: 72,
      accuracy: 45,
      range: 45,
      overall: 47.4,
    },
  },
  bullpupshotgun: {
    key: "bullpupshotgun",
    hash: 2640438543,
    name: getWeaponData(2640438543).Name,
    description: getWeaponData(2640438543).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 14,
    price: 8000,
    stats: {
      damage: 67,
      rate: 20,
      accuracy: 30,
      range: 20,
      overall: 31.4,
    },
  },
  carbinerifle: {
    key: "carbinerifle",
    hash: 2210333304,
    name: getWeaponData(2210333304).Name,
    description: getWeaponData(2210333304).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 13000,
    stats: {
      damage: 32,
      rate: 65,
      accuracy: 55,
      range: 45,
      overall: 47.4,
    },
  },
  carbineriflemk2: {
    key: "carbineriflemk2",
    hash: 4208062921,
    name: getWeaponData(4208062921).Name,
    description: getWeaponData(4208062921).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 107500,
    stats: {
      damage: 36,
      rate: 65,
      accuracy: 55,
      range: 45,
      overall: 48.2,
    },
  },
  ceramicpistol: {
    key: "ceramicpistol",
    hash: 727643628,
    name: getWeaponData(727643628).Name,
    description: getWeaponData(727643628).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 12,
    price: 20000,
    stats: {
      damage: 32,
      rate: 44,
      accuracy: 36,
      range: 20,
      overall: 27.6,
    },
  },
  combatmg: {
    key: "combatmg",
    hash: 2144741730,
    name: getWeaponData(2144741730).Name,
    description: getWeaponData(2144741730).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 100,
    price: 14800,
    stats: {
      damage: 55,
      rate: 65,
      accuracy: 45,
      range: 60,
      overall: 59,
    },
  },
  combatmgmk2: {
    key: "combatmgmk2",
    hash: 3686625920,
    name: getWeaponData(3686625920).Name,
    description: getWeaponData(3686625920).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 100,
    price: 119000,
    stats: {
      damage: 57,
      rate: 65,
      accuracy: 45,
      range: 60,
      overall: 59.4,
    },
  },
  combatpdw: {
    key: "combatpdw",
    hash: 171789620,
    name: getWeaponData(171789620).Name,
    description: getWeaponData(171789620).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 30,
    price: 11750,
    stats: {
      damage: 25,
      rate: 50,
      accuracy: 45,
      range: 38,
      overall: 39.6,
    },
  },
  combatpistol: {
    key: "combatpistol",
    hash: 1593441988,
    name: getWeaponData(1593441988).Name,
    description: getWeaponData(1593441988).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 12,
    price: 3200,
    stats: {
      damage: 27,
      rate: 40,
      accuracy: 50,
      range: 30,
      overall: 31.4,
    },
  },
  compactlauncher: {
    key: "compactlauncher",
    hash: 125959754,
    name: getWeaponData(125959754).Name,
    description: getWeaponData(125959754).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.GRENADE_LAUNCHER,
    clipSize: 1,
    price: 45000,
    stats: {
      damage: 95,
      rate: 10,
      accuracy: 15,
      range: 55,
      overall: 39,
    },
  },
  compactrifle: {
    key: "compactrifle",
    hash: 1649403952,
    name: getWeaponData(1649403952).Name,
    description: getWeaponData(1649403952).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 14650,
    stats: {
      damage: 36,
      rate: 60,
      accuracy: 35,
      range: 45,
      overall: 43.2,
    },
  },
  dbshotgun: {
    key: "dbshotgun",
    hash: 4019527611,
    name: getWeaponData(4019527611).Name,
    description: getWeaponData(4019527611).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 2,
    price: 15450,
    stats: {
      damage: 98,
      rate: 25,
      accuracy: 15,
      range: 10,
      overall: 30,
    },
  },
  doubleaction: {
    key: "doubleaction",
    hash: 2548703416,
    name: getWeaponData(2548703416).Name,
    description: getWeaponData(2548703416).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 6,
    price: 75000,
    stats: {
      damage: 70,
      rate: 35,
      accuracy: 65,
      range: 20,
      overall: 39.2,
    },
  },
  fireextinguisher: {
    key: "fireextinguisher",
    hash: 101631238,
    name: getWeaponData(101631238).Name,
    description: getWeaponData(101631238).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.UTILITY,
    ammoGroup: AmmoGroup.FIRE_EXTINGUISHER,
    clipSize: 2000,
    price: 200,
    stats: {
      damage: 0,
      rate: 100,
      accuracy: 10,
      range: 30,
      overall: 0,
    },
  },
  firework: {
    key: "firework",
    hash: 2138347493,
    name: getWeaponData(2138347493).Name,
    description: getWeaponData(2138347493).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.FIREWORK,
    clipSize: 1,
    price: 65000,
    stats: {
      damage: 45,
      rate: 5,
      accuracy: 12,
      range: 60,
      overall: 26.4,
    },
  },
  flaregun: {
    key: "flaregun",
    hash: 1198879012,
    name: getWeaponData(1198879012).Name,
    description: getWeaponData(1198879012).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 1,
    price: 3750,
    stats: {
      damage: 20,
      rate: 10,
      accuracy: 30,
      range: 10,
      overall: 16,
    },
  },
  grenadelauncher: {
    key: "grenadelauncher",
    hash: 2726580491,
    name: getWeaponData(2726580491).Name,
    description: getWeaponData(2726580491).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.GRENADE_LAUNCHER,
    clipSize: 10,
    price: 32400,
    stats: {
      damage: 95,
      rate: 20,
      accuracy: 10,
      range: 50,
      overall: 39,
    },
  },
  smokelauncher: {
    key: "smokelauncher",
    hash: 1305664598,
    name: getWeaponData(1305664598).Name,
    description: getWeaponData(1305664598).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.UTILITY,
    ammoGroup: AmmoGroup.SMOKE_GRANADES,
    clipSize: 10,
    price: 4200,
    stats: {
      damage: 20,
      rate: 20,
      accuracy: 10,
      range: 50,
      overall: 25,
    },
  },
  gusenberg: {
    key: "gusenberg",
    hash: 1627465347,
    name: getWeaponData(1627465347).Name,
    description: getWeaponData(1627465347).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 30,
    price: 14600,
    stats: {
      damage: 34,
      rate: 65,
      accuracy: 38,
      range: 56,
      overall: 46.6,
    },
  },
  heavypistol: {
    key: "heavypistol",
    hash: 3523564046,
    name: getWeaponData(3523564046).Name,
    description: getWeaponData(3523564046).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 18,
    price: 3750,
    stats: {
      damage: 40,
      rate: 40,
      accuracy: 50,
      range: 35,
      overall: 37,
    },
  },
  heavyshotgun: {
    key: "heavyshotgun",
    hash: 984333226,
    name: getWeaponData(984333226).Name,
    description: getWeaponData(984333226).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 6,
    price: 13550,
    stats: {
      damage: 85,
      rate: 45,
      accuracy: 30,
      range: 25,
      overall: 38.6,
    },
  },
  heavysniper: {
    key: "heavysniper",
    hash: 205991906,
    name: getWeaponData(205991906).Name,
    description: getWeaponData(205991906).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SNIPER_RIFLE,
    ammoGroup: AmmoGroup.SNIPER_RIFLE,
    clipSize: 6,
    price: 38150,
    stats: {
      damage: 98,
      rate: 20,
      accuracy: 90,
      range: 100,
      overall: 62.6,
    },
  },
  heavysnipermk2: {
    key: "heavysnipermk2",
    hash: 177293209,
    name: getWeaponData(177293209).Name,
    description: getWeaponData(177293209).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SNIPER_RIFLE,
    ammoGroup: AmmoGroup.SNIPER_RIFLE,
    clipSize: 6,
    price: 165375,
    stats: {
      damage: 98,
      rate: 20,
      accuracy: 90,
      range: 100,
      overall: 62.6,
    },
  },
  hominglauncher: {
    key: "hominglauncher",
    hash: 1672152130,
    name: getWeaponData(1672152130).Name,
    description: getWeaponData(1672152130).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.ROCKET_LAUNCHER,
    clipSize: 1,
    price: 165000,
    stats: {
      damage: 95,
      rate: 5,
      accuracy: 25,
      range: 75,
      overall: 42,
    },
  },
  machinepistol: {
    key: "machinepistol",
    hash: 3675956304,
    name: getWeaponData(3675956304).Name,
    description: getWeaponData(3675956304).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 12,
    price: 6250,
    stats: {
      damage: 28,
      rate: 70,
      accuracy: 40,
      range: 30,
      overall: 36,
    },
  },
  marksmanpistol: {
    key: "marksmanpistol",
    hash: 3696079510,
    name: getWeaponData(3696079510).Name,
    description: getWeaponData(3696079510).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 1,
    price: 4350,
    stats: {
      damage: 80,
      rate: 15,
      accuracy: 30,
      range: 35,
      overall: 32.4,
    },
  },
  marksmanrifle: {
    key: "marksmanrifle",
    hash: 3342088282,
    name: getWeaponData(3342088282).Name,
    description: getWeaponData(3342088282).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SNIPER_RIFLE,
    ammoGroup: AmmoGroup.SNIPER_RIFLE,
    clipSize: 8,
    price: 15750,
    stats: {
      damage: 70,
      rate: 40,
      accuracy: 80,
      range: 90,
      overall: 58,
    },
  },
  marksmanriflemk2: {
    key: "marksmanriflemk2",
    hash: 1785463520,
    name: getWeaponData(1785463520).Name,
    description: getWeaponData(1785463520).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SNIPER_RIFLE,
    ammoGroup: AmmoGroup.SNIPER_RIFLE,
    clipSize: 8,
    price: 149000,
    stats: {
      damage: 70,
      rate: 40,
      accuracy: 80,
      range: 90,
      overall: 58,
    },
  },
  mg: {
    key: "mg",
    hash: 2634544996,
    name: getWeaponData(2634544996).Name,
    description: getWeaponData(2634544996).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 54,
    price: 13500,
    stats: {
      damage: 50,
      rate: 60,
      accuracy: 40,
      range: 60,
      overall: 52,
    },
  },
  microsmg: {
    key: "microsmg",
    hash: 324215364,
    name: getWeaponData(324215364).Name,
    description: getWeaponData(324215364).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 16,
    price: 3750,
    stats: {
      damage: 21,
      rate: 60,
      accuracy: 30,
      range: 25,
      overall: 31.2,
    },
  },
  minigun: {
    key: "minigun",
    hash: 1119849093,
    name: getWeaponData(1119849093).Name,
    description: getWeaponData(1119849093).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 0,
    price: 470000,
    stats: {
      damage: 30,
      rate: 100,
      accuracy: 40,
      range: 55,
      overall: 63,
    },
  },
  minismg: {
    key: "minismg",
    hash: 3173288789,
    name: getWeaponData(3173288789).Name,
    description: getWeaponData(3173288789).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 20,
    price: 8900,
    stats: {
      damage: 22,
      rate: 84,
      accuracy: 33,
      range: 30,
      overall: 36.2,
    },
  },
  musket: {
    key: "musket",
    hash: 2828843422,
    name: getWeaponData(2828843422).Name,
    description: getWeaponData(2828843422).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 1,
    price: 21400,
    stats: {
      damage: 97,
      rate: 10,
      accuracy: 65,
      range: 85,
      overall: 53.4,
    },
  },
  navyrevolver: {
    key: "navyrevolver",
    hash: 2441047180,
    name: getWeaponData(2441047180).Name,
    description: getWeaponData(2441047180).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 6,
    price: 55000,
    stats: {
      damage: 70,
      rate: 25,
      accuracy: 60,
      range: 35,
      overall: 40,
    },
  },
  // parachute: {
  //   key: "parachute",
  //   hash: 4222310262,
  //   name: getWeaponData(4222310262).Name,
  //   description: getWeaponData(4222310262).Description,
  //   flags: ItemFlags.IsEquippable,
  //   type: WeaponType.UTILITY,
  //   price: 250,
  // },
  pistol: {
    key: "pistol",
    hash: 453432689,
    name: getWeaponData(453432689).Name,
    description: getWeaponData(453432689).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 12,
    price: 2500,
    stats: {
      damage: 26,
      rate: 40,
      accuracy: 40,
      range: 25,
      overall: 28.2,
    },
  },
  pistol50: {
    key: "pistol50",
    hash: 2578377531,
    name: getWeaponData(2578377531).Name,
    description: getWeaponData(2578377531).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 9,
    price: 3900,
    stats: {
      damage: 51,
      rate: 40,
      accuracy: 55,
      range: 35,
      overall: 37.8,
    },
  },
  pistolmk2: {
    key: "pistolmk2",
    hash: 3219281620,
    name: getWeaponData(3219281620).Name,
    description: getWeaponData(3219281620).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 12,
    price: 73750,
    stats: {
      damage: 38,
      rate: 40,
      accuracy: 40,
      range: 25,
      overall: 30.6,
    },
  },
  pumpshotgun: {
    key: "pumpshotgun",
    hash: 487013001,
    name: getWeaponData(487013001).Name,
    description: getWeaponData(487013001).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 8,
    price: 3500,
    stats: {
      damage: 67,
      rate: 20,
      accuracy: 30,
      range: 20,
      overall: 29.4,
    },
  },
  pumpshotgunmk2: {
    key: "pumpshotgunmk2",
    hash: 1432025498,
    name: getWeaponData(1432025498).Name,
    description: getWeaponData(1432025498).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 8,
    price: 82500,
    stats: {
      damage: 67,
      rate: 20,
      accuracy: 30,
      range: 20,
      overall: 29.4,
    },
  },
  railgun: {
    key: "railgun",
    hash: 1834241177,
    name: getWeaponData(1834241177).Name,
    description: getWeaponData(1834241177).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.PLASMA_RAYS,
    clipSize: 1,
    price: 250000,
    stats: {
      damage: 90,
      rate: 25,
      accuracy: 20,
      range: 70,
      overall: 44,
    },
  },
  raycarbine: {
    key: "raycarbine",
    hash: 1198256469,
    name: getWeaponData(1198256469).Name,
    description: getWeaponData(1198256469).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.PLASMA_RAYS,
    clipSize: 9999,
    price: 449000,
    stats: {
      damage: 55,
      rate: 65,
      accuracy: 45,
      range: 60,
      overall: 59,
    },
  },
  rayminigun: {
    key: "rayminigun",
    hash: 3056410471,
    name: getWeaponData(3056410471).Name,
    description: getWeaponData(3056410471).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.PLASMA_RAYS,
    clipSize: 15000,
    price: 449000,
    stats: {
      damage: 30,
      rate: 100,
      accuracy: 40,
      range: 55,
      overall: 63,
    },
  },
  raypistol: {
    key: "raypistol",
    hash: 2939590305,
    name: getWeaponData(2939590305).Name,
    description: getWeaponData(2939590305).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 1,
    price: 399000,
    stats: {
      damage: 80,
      rate: 10,
      accuracy: 10,
      range: 50,
      overall: 32,
    },
  },
  revolver: {
    key: "revolver",
    hash: 3249783761,
    name: getWeaponData(3249783761).Name,
    description: getWeaponData(3249783761).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 6,
    price: 5900,
    stats: {
      damage: 70,
      rate: 20,
      accuracy: 65,
      range: 35,
      overall: 39.2,
    },
  },
  revolvermk2: {
    key: "revolvermk2",
    hash: 3415619887,
    name: getWeaponData(3415619887).Name,
    description: getWeaponData(3415619887).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 6,
    price: 99000,
    stats: {
      damage: 75,
      rate: 30,
      accuracy: 65,
      range: 35,
      overall: 42.2,
    },
  },
  rpg: {
    key: "rpg",
    hash: 2982836145,
    name: getWeaponData(2982836145).Name,
    description: getWeaponData(2982836145).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HEAVY,
    ammoGroup: AmmoGroup.ROCKET_LAUNCHER,
    clipSize: 1,
    price: 26250,
    stats: {
      damage: 100,
      rate: 5,
      accuracy: 10,
      range: 70,
      overall: 39,
    },
  },
  sawnoffshotgun: {
    key: "sawnoffshotgun",
    hash: 2017895192,
    name: getWeaponData(2017895192).Name,
    description: getWeaponData(2017895192).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SHOTGUN,
    ammoGroup: AmmoGroup.SHOTGUN,
    clipSize: 8,
    price: 30000,
    stats: {
      damage: 96,
      rate: 20,
      accuracy: 20,
      range: 15,
      overall: 32.2,
    },
  },
  smg: {
    key: "smg",
    hash: 736523883,
    name: getWeaponData(736523883).Name,
    description: getWeaponData(736523883).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 30,
    price: 7500,
    stats: {
      damage: 22,
      rate: 55,
      accuracy: 40,
      range: 35,
      overall: 38.4,
    },
  },
  smgmk2: {
    key: "smgmk2",
    hash: 2024373456,
    name: getWeaponData(2024373456).Name,
    description: getWeaponData(2024373456).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MACHINE_GUN,
    ammoGroup: AmmoGroup.MACHINE_GUN,
    clipSize: 30,
    price: 85500,
    stats: {
      damage: 22,
      rate: 55,
      accuracy: 40,
      range: 35,
      overall: 38.4,
    },
  },
  sniperrifle: {
    key: "sniperrifle",
    hash: 100416529,
    name: getWeaponData(100416529).Name,
    description: getWeaponData(100416529).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.SNIPER_RIFLE,
    ammoGroup: AmmoGroup.SNIPER_RIFLE,
    clipSize: 10,
    price: 20000,
    stats: {
      damage: 96,
      rate: 25,
      accuracy: 70,
      range: 95,
      overall: 59.2,
    },
  },
  snspistol: {
    key: "snspistol",
    hash: 3218215474,
    name: getWeaponData(3218215474).Name,
    description: getWeaponData(3218215474).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 6,
    price: 2750,
    stats: {
      damage: 30,
      rate: 40,
      accuracy: 40,
      range: 20,
      overall: 26.6,
    },
  },
  snspistolmk2: {
    key: "snspistolmk2",
    hash: 2285322324,
    name: getWeaponData(2285322324).Name,
    description: getWeaponData(2285322324).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 6,
    price: 79575,
    stats: {
      damage: 30,
      rate: 40,
      accuracy: 40,
      range: 20,
      overall: 26.6,
    },
  },
  specialcarbine: {
    key: "specialcarbine",
    hash: 3231910285,
    name: getWeaponData(3231910285).Name,
    description: getWeaponData(3231910285).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 14750,
    stats: {
      damage: 34,
      rate: 65,
      accuracy: 55,
      range: 40,
      overall: 46.8,
    },
  },
  specialcarbinemk2: {
    key: "specialcarbinemk2",
    hash: 2526821735,
    name: getWeaponData(2526821735).Name,
    description: getWeaponData(2526821735).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.ASSAULT_RIFLE,
    ammoGroup: AmmoGroup.ASSAULT_RIFLE,
    clipSize: 30,
    price: 135000,
    stats: {
      damage: 34,
      rate: 65,
      accuracy: 55,
      range: 40,
      overall: 46.8,
    },
  },
  stungun: {
    key: "stungun",
    hash: 911657153,
    name: getWeaponData(911657153).Name,
    description: getWeaponData(911657153).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 1, // 2104529083
    price: 100,
    stats: {
      damage: 1,
      rate: 10,
      accuracy: 40,
      range: 5,
      overall: 31.2,
    },
  },
  vintagepistol: {
    key: "vintagepistol",
    hash: 137902532,
    name: getWeaponData(137902532).Name,
    description: getWeaponData(137902532).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.HANDGUN,
    ammoGroup: AmmoGroup.HANDGUN,
    clipSize: 7,
    price: 3450,
    stats: {
      damage: 35,
      rate: 40,
      accuracy: 40,
      range: 25,
      overall: 29.2,
    },
  },
};

export function isItemKeyFirearmWeapon(key: ItemKey): key is FirearmWeaponItemKey {
  return key in firearmWeapons;
}

export function isItemFirearmWeapon(item: Item): item is FirearmWeaponItem {
  return isItemKeyFirearmWeapon(item.key);
}
