import { ItemType } from "@prisma/client";
import { ItemFlags } from "../item-flags";
import { WeaponGroup } from "./weapon-groups";
import { getWeaponData } from ".";

export const MeleeWeapon = {
  BAT: "bat",
  BATTLEAXE: "battleaxe",
  BOTTLE: "bottle",
  CROWBAR: "crowbar",
  DAGGER: "dagger",
  FLASHLIGHT: "flashlight",
  GOLFCLUB: "golfclub",
  HAMMER: "hammer",
  HATCHET: "hatchet",
  KNIFE: "knife",
  KNUCKLE: "knuckle",
  MACHETE: "machete",
  NIGHTSTICK: "nightstick",
  PIPEWRENCH: "pipewrench",
  POOLCUE: "poolcue",
  STONEHATCHET: "stonehatchet",
  SWITCHBLADE: "switchblade",
  UNARMED: "unarmed",
} as const;

export type MeleeWeaponItemKey = (typeof MeleeWeapon)[keyof typeof MeleeWeapon];

export type MeleeItemInfo = {
  key: MeleeWeaponItemKey;
  itemType: typeof ItemType.MELEE_WEAPON;
  hash: number;
  name: string;
  description: string;
  flags: ItemFlags;
  group: typeof WeaponGroup.MELEE;
  price: number;
  stats: {
    damage: number;
    rate: number;
    range: number;
    overall: number;
  };
};

export const meleeWeapons: Record<MeleeWeaponItemKey, MeleeItemInfo> = {
  switchblade: {
    key: "switchblade",
    itemType: ItemType.MELEE_WEAPON,
    hash: 3756226112,
    name: getWeaponData(3756226112).Name,
    description: getWeaponData(3756226112).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 1950,
    stats: {
      damage: 76,
      rate: 20,
      range: 0,
      overall: 11.67,
    },
  },
  unarmed: {
    key: "unarmed",
    itemType: ItemType.MELEE_WEAPON,
    hash: 2725352035,
    name: getWeaponData(2725352035).Name,
    description: getWeaponData(2725352035).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 0,
    stats: {
      damage: 5,
      rate: 20,
      range: 1,
      overall: 8.67,
    },
  },
  stonehatchet: {
    key: "stonehatchet",
    itemType: ItemType.MELEE_WEAPON,
    hash: 940833800,
    name: getWeaponData(940833800).Name,
    description: getWeaponData(940833800).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 25000,
    stats: {
      damage: 30,
      rate: 15,
      range: 0,
      overall: 15,
    },
  },
  poolcue: {
    key: "poolcue",
    itemType: ItemType.MELEE_WEAPON,
    hash: 2484171525,
    name: getWeaponData(2484171525).Name,
    description: getWeaponData(2484171525).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 6250,
    stats: {
      damage: 20,
      rate: 10,
      range: 0,
      overall: 10,
    },
  },
  pipewrench: {
    key: "pipewrench",
    itemType: ItemType.MELEE_WEAPON,
    hash: 419712736,
    name: getWeaponData(419712736).Name,
    description: getWeaponData(419712736).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 7150,
    stats: {
      damage: 10,
      rate: 15,
      range: 0,
      overall: 8.33,
    },
  },
  nightstick: {
    key: "nightstick",
    itemType: ItemType.MELEE_WEAPON,
    hash: 1737195953,
    name: getWeaponData(1737195953).Name,
    description: getWeaponData(1737195953).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 400,
    stats: {
      damage: 10,
      rate: 15,
      range: 1,
      overall: 8.67,
    },
  },
  knife: {
    key: "knife",
    itemType: ItemType.MELEE_WEAPON,
    hash: 2578778090,
    name: getWeaponData(2578778090).Name,
    description: getWeaponData(2578778090).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 400,
    stats: {
      damage: 76,
      rate: 20,
      range: 1,
      overall: 12,
    },
  },
  knuckle: {
    key: "knuckle",
    itemType: ItemType.MELEE_WEAPON,
    hash: 3638508604,
    name: getWeaponData(3638508604).Name,
    description: getWeaponData(3638508604).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 7500,
    stats: {
      damage: 10,
      rate: 20,
      range: 1,
      overall: 1,
    },
  },
  machete: {
    key: "machete",
    itemType: ItemType.MELEE_WEAPON,
    hash: 3713923289,
    name: getWeaponData(3713923289).Name,
    description: getWeaponData(3713923289).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 8900,
    stats: {
      damage: 76,
      rate: 15,
      range: 0,
      overall: 10,
    },
  },
  hammer: {
    key: "hammer",
    itemType: ItemType.MELEE_WEAPON,
    hash: 1317494643,
    name: getWeaponData(1317494643).Name,
    description: getWeaponData(1317494643).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 500,
    stats: {
      damage: 10,
      rate: 15,
      range: 1,
      overall: 8.67,
    },
  },
  hatchet: {
    key: "hatchet",
    itemType: ItemType.MELEE_WEAPON,
    hash: 4191993645,
    name: getWeaponData(4191993645).Name,
    description: getWeaponData(4191993645).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 750,
    stats: {
      damage: 76,
      rate: 15,
      range: 0,
      overall: 10,
    },
  },
  flashlight: {
    key: "flashlight",
    itemType: ItemType.MELEE_WEAPON,
    hash: 2343591895,
    name: getWeaponData(2343591895).Name,
    description: getWeaponData(2343591895).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 250,
    stats: {
      damage: 10,
      rate: 15,
      range: 0,
      overall: 8.33,
    },
  },
  golfclub: {
    key: "golfclub",
    itemType: ItemType.MELEE_WEAPON,
    hash: 1141786504,
    name: getWeaponData(1141786504).Name,
    description: getWeaponData(1141786504).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 125,
    stats: {
      damage: 20,
      rate: 10,
      range: 1,
      overall: 10.33,
    },
  },
  crowbar: {
    key: "crowbar",
    itemType: ItemType.MELEE_WEAPON,
    hash: 2227010557,
    name: getWeaponData(2227010557).Name,
    description: getWeaponData(2227010557).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 55,
    stats: {
      damage: 10,
      rate: 15,
      range: 1,
      overall: 8.67,
    },
  },
  dagger: {
    key: "dagger",
    itemType: ItemType.MELEE_WEAPON,
    hash: 2460120199,
    name: getWeaponData(2460120199).Name,
    description: getWeaponData(2460120199).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 2000,
    stats: {
      damage: 20,
      rate: 20,
      range: 2,
      overall: 14,
    },
  },
  bat: {
    key: "bat",
    itemType: ItemType.MELEE_WEAPON,
    hash: 2508868239,
    name: getWeaponData(2508868239).Name,
    description: getWeaponData(2508868239).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 100,
    stats: {
      damage: 20,
      rate: 10,
      range: 1,
      overall: 10.33,
    },
  },
  battleaxe: {
    key: "battleaxe",
    itemType: ItemType.MELEE_WEAPON,
    hash: 3441901897,
    name: getWeaponData(3441901897).Name,
    description: getWeaponData(3441901897).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 300,
    stats: {
      damage: 76,
      rate: 15,
      range: 0,
      overall: 10,
    },
  },
  bottle: {
    key: "bottle",
    itemType: ItemType.MELEE_WEAPON,
    hash: 4192643659,
    name: getWeaponData(4192643659).Name,
    description: getWeaponData(4192643659).Description,
    flags: ItemFlags.IsEquippable,
    group: WeaponGroup.MELEE,
    price: 8,
    stats: {
      damage: 20,
      rate: 15,
      range: 1,
      overall: 12,
    },
  },
};
