// @index('./**/*.ts', f => `import "${f.path}";`)
import "./add-interval";
import "./characters/create-character";
import "./characters/delete-character";
import "./characters/get-characters";
import "./characters/load-character";
import "./characters/save-character";
import "./characters/start-game";
import "./characters/update-character-appearance";
import "./equipment/apply-equipment";
import "./equipment/get-equiped-item-in-slot";
import "./inventory/add-blueprint";
import "./inventory/add-item";
import "./inventory/equip-item";
import "./inventory/get-inventory-item-in-slot";
import "./inventory/has-item";
import "./inventory/remove-item";
import "./inventory/unequip-item";
import "./inventory/weapons/reload-weapon";
import "./load-user";
import "./quests/is-near-ped";
import "./setup-pinia";
import "./setup";
// @endindex
