name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: altv-rift-server
#
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      #
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          REDIRECT_IP: ${{ vars.REDIRECT_IP }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          ALTV_HOST: ${{ vars.ALTV_HOST }}
          ALTV_NAME: ${{ vars.ALTV_NAME }}
          ALTV_PORT: ${{ vars.ALTV_PORT }}
          ALTV_PASSWORD: ${{ vars.ALTV_PASSWORD }}
          ALTV_ANNOUNCE: ${{ vars.ALTV_ANNOUNCE }}
          ALTV_DEBUG: ${{ vars.ALTV_DEBUG }}
          ALTV_MODULES: ${{ vars.ALTV_MODULES }}
          ALTV_RESOURCES: ${{ vars.ALTV_RESOURCES }}
        run: COMPOSE_PROJECT_NAME=${IMAGE_NAME} docker-compose -f docker-compose.prod.yaml build

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Push image
        run: |
          echo "Image name: ${IMAGE_NAME}"
          echo "Full image tag: ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest"
          docker tag ${IMAGE_NAME}:latest ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest
          docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/altv-server:latest
            docker stop altv-server || true
            docker rm altv-server || true
            docker run -d --name altv-server \
              -p 7788:7788 \
              -p 7790:7790 \
              -p 7799:7799 \
              ghcr.io/${{ github.repository_owner }}/altv-server:latest
            docker image prune -f
