import { ItemGrade } from "../items";
import { TreeTypes } from "./tree-types";

export const TreeGrades = {
  h4_prop_tree_palm_fan_bea_03b: ItemGrade.COMMON,
  prop_palm_med_01a: ItemGrade.COMMON,
  prop_palm_sm_01a: ItemGrade.COMMON,
  prop_palm_sm_01d: ItemGrade.COMMON,
  prop_palm_sm_01e: ItemGrade.COMMON,
  prop_palm_sm_01f: ItemGrade.COMMON,
  h4_prop_tree_palm_thatch_01: ItemGrade.COMMON,
  prop_palm_huge_01a: ItemGrade.COMMON,
  prop_palm_huge_01b: ItemGrade.COMMON,
  prop_palm_med_01b: ItemGrade.COMMON,
  prop_palm_med_01c: ItemGrade.COMMON,
  prop_palm_med_01d: ItemGrade.COMMON,
  prop_plant_palm_01b: ItemGrade.COMMON,
  h4_prop_tree_beech_lrg_if_01: ItemGrade.COMMON,
  h4_prop_tree_blk_mgrv_lrg_01: ItemGrade.COMMON,
  h4_prop_tree_blk_mgrv_lrg_02: ItemGrade.COMMON,
  h4_prop_tree_blk_mgrv_med_01: ItemGrade.COMMON,
  prop_tree_jacada_01: ItemGrade.COMMON,
  prop_tree_jacada_02: ItemGrade.COMMON,
  prop_tree_birch_01: ItemGrade.UNCOMMON,
  prop_tree_birch_02: ItemGrade.UNCOMMON,
  prop_tree_birch_03: ItemGrade.UNCOMMON,
  prop_tree_birch_03b: ItemGrade.UNCOMMON,
  prop_tree_birch_04: ItemGrade.UNCOMMON,
  prop_tree_birch_05: ItemGrade.UNCOMMON,
  prop_bush_lrg_04b: ItemGrade.UNCOMMON,
  prop_bush_lrg_04c: ItemGrade.UNCOMMON,
  prop_bush_lrg_04d: ItemGrade.UNCOMMON,
  prop_tree_maple_02: ItemGrade.RARE,
  prop_tree_maple_03: ItemGrade.RARE,
  prop_tree_lficus_02: ItemGrade.UNCOMMON,
  prop_tree_lficus_03: ItemGrade.UNCOMMON,
  prop_tree_lficus_05: ItemGrade.UNCOMMON,
  prop_tree_lficus_06: ItemGrade.UNCOMMON,
  prop_tree_eucalip_01: ItemGrade.RARE,
  h4_prop_tree_umbrella_med_01: ItemGrade.RARE,
  h4_prop_tree_umbrella_sml_01: ItemGrade.RARE,
  prop_tree_eng_oak_01: ItemGrade.EPIC,
  prop_tree_oak_01: ItemGrade.EPIC,
  prop_tree_pine_01: ItemGrade.EPIC,
  prop_tree_pine_02: ItemGrade.EPIC,
  prop_s_pine_dead_01: ItemGrade.EPIC,
  prop_tree_cedar_02: ItemGrade.EPIC,
  prop_tree_cedar_03: ItemGrade.EPIC,
  prop_tree_cedar_04: ItemGrade.EPIC,
  prop_tree_cedar_s_01: ItemGrade.EPIC,
  prop_tree_cedar_s_02: ItemGrade.EPIC,
  prop_w_r_cedar_01: ItemGrade.EPIC,
  prop_w_r_cedar_dead: ItemGrade.LEGENDARY,
  prop_tree_mquite_01: ItemGrade.LEGENDARY,
  prop_rus_olive: ItemGrade.LEGENDARY,
  prop_rus_olive_wint: ItemGrade.LEGENDARY,
  h4_prop_tree_frangipani_lrg_01: ItemGrade.LEGENDARY,
  prop_joshua_tree_01a: ItemGrade.LEGENDARY,
  prop_joshua_tree_01b: ItemGrade.LEGENDARY,
  prop_joshua_tree_01c: ItemGrade.LEGENDARY,
  prop_joshua_tree_01d: ItemGrade.LEGENDARY,
  prop_joshua_tree_01e: ItemGrade.LEGENDARY,
  prop_joshua_tree_02a: ItemGrade.LEGENDARY,
  prop_joshua_tree_02b: ItemGrade.LEGENDARY,
  prop_joshua_tree_02c: ItemGrade.LEGENDARY,
  prop_joshua_tree_02d: ItemGrade.LEGENDARY,
  prop_joshua_tree_02e: ItemGrade.LEGENDARY,
} as const satisfies Record<keyof typeof TreeTypes, ItemGrade>;

export const TreeXPPerLog = {
  1: 11,
  5: 33,
  10: 63,
  15: 97,
  20: 136,
  25: 184,
  30: 248,
  35: 433,
  40: 560,
  45: 753,
  50: 1054,
  55: 1532,
  60: 2300,
  65: 3543,
  70: 5568,
  75: 8873,
  80: 14280,
} as const;
